package com.sysmedica.dao.postgresql;

import java.sql.Connection;
import java.sql.ResultSet;

import com.sysmedica.dao.FichaTosferinaDao;
import com.sysmedica.dao.sqlbase.SqlBaseFichaTosferinaDao;

public class PostgresqlFichaTosferinaDao implements FichaTosferinaDao {

	private String secuenciaStr = "SELECT nextval('epidemiologia.seq_fichas')";

	public int insertarFichaCompleta(Connection con,
								    		int numeroSolicitud,
											String login,
											int codigoPaciente,
											String codigoDiagnostico,
											int estado,
											int codigoAseguradora,
											String nombreProfesional,
										    
										    String sire,
											boolean notificar,
											
											int codigoFichaIntoxicacion,										    
										    String lugarProcedencia,
										    String fechaConsultaGeneral,
										    String fechaInicioSintomasGeneral,
										    int tipoCaso,
										    boolean hospitalizadoGeneral,
										    String fechaHospitalizacionGeneral,
										    boolean estaVivoGeneral,
										    String fechaDefuncion,
										    String lugarNoti,
										    int unidadGeneradora,
										    
										    String nombrePadre,
										    String fechaInvestigacion,
										    int identificacionCaso,
										    int contactoCaso,
										    int carneVacunacion,
										    int dosisAplicadas,
										    int tipoVacuna,
										    String cualVacuna,
										    String fechaUltimaDosis,
										    int etapaEnfermedad,
										    int tos,
										    String duracionTos,
										    int tosParoxistica,
										    int estridor,
										    int apnea,
										    int fiebre,
										    int vomitoPostusivo,
										    int complicaciones,
										    int tipoComplicacion,
										    int tratamientoAntibiotico,
										    String tipoAntibiotico,
										    String duracionTratamiento,
										    int investigacionCampo,
										    String fechaOperacionBarrido,
										    String numeroContactos,
										    int quimioprofilaxis,
										    int totalPoblacion1,
										    int totalPoblacion2,
										    int totalPoblacion3,
										    int totalPoblacion4,
										    int dosisDpt1Grupo1,
										    int dosisDpt1Grupo2,
										    int dosisDpt1Grupo3,
										    int dosisDpt1Grupo4,
										    int dosisDpt2Grupo1,
										    int dosisDpt2Grupo2,
										    int dosisDpt2Grupo3,
										    int dosisDpt2Grupo4,
										    int dosisDpt3Grupo1,
										    int dosisDpt3Grupo2,
										    int dosisDpt3Grupo3,
										    int dosisDpt3Grupo4,
										    int dosisRef1Grupo1,
										    int dosisRef1Grupo2,
										    int dosisRef1Grupo3,
										    int dosisRef1Grupo4,
										    int dosisRef2Grupo1,
										    int dosisRef2Grupo2,
										    int dosisRef2Grupo3,
										    int dosisRef2Grupo4,
										    String municipiosVacunados,
										    
										    boolean activa,
										    String pais,
										    int areaProcedencia
										   )
	{
		return SqlBaseFichaTosferinaDao.insertarFichaCompleta(con,
													    		numeroSolicitud,
																login,
																codigoPaciente,
																codigoDiagnostico,
																estado,
																codigoAseguradora,
																nombreProfesional,
															    secuenciaStr,
															    
															    sire,
																notificar,
																
																codigoFichaIntoxicacion,										    
															    lugarProcedencia,
															    fechaConsultaGeneral,
															    fechaInicioSintomasGeneral,
															    tipoCaso,
															    hospitalizadoGeneral,
															    fechaHospitalizacionGeneral,
															    estaVivoGeneral,
															    fechaDefuncion,
															    lugarNoti,
															    unidadGeneradora,
															    
															    nombrePadre,
															    fechaInvestigacion,
															    identificacionCaso,
															    contactoCaso,
															    carneVacunacion,
															    dosisAplicadas,
															    tipoVacuna,
															    cualVacuna,
															    fechaUltimaDosis,
															    etapaEnfermedad,
															    tos,
															    duracionTos,
															    tosParoxistica,
															    estridor,
															    apnea,
															    fiebre,
															    vomitoPostusivo,
															    complicaciones,
															    tipoComplicacion,
															    tratamientoAntibiotico,
															    tipoAntibiotico,
															    duracionTratamiento,
															    investigacionCampo,
															    fechaOperacionBarrido,
															    numeroContactos,
															    quimioprofilaxis,
															    totalPoblacion1,
															    totalPoblacion2,
															    totalPoblacion3,
															    totalPoblacion4,
															    dosisDpt1Grupo1,
															    dosisDpt1Grupo2,
															    dosisDpt1Grupo3,
															    dosisDpt1Grupo4,
															    dosisDpt2Grupo1,
															    dosisDpt2Grupo2,
															    dosisDpt2Grupo3,
															    dosisDpt2Grupo4,
															    dosisDpt3Grupo1,
															    dosisDpt3Grupo2,
															    dosisDpt3Grupo3,
															    dosisDpt3Grupo4,
															    dosisRef1Grupo1,
															    dosisRef1Grupo2,
															    dosisRef1Grupo3,
															    dosisRef1Grupo4,
															    dosisRef2Grupo1,
															    dosisRef2Grupo2,
															    dosisRef2Grupo3,
															    dosisRef2Grupo4,
															    municipiosVacunados,
															    
															    activa,
															    pais,
															    areaProcedencia);
	}
	
	
	
	

	public int modificarFicha(Connection con,
										String sire,
										boolean notificar,
									    String loginUsuario,
									    int codigoFichaTosferina,
									    int codigoPaciente,
									    String codigoDiagnostico,
									    int codigoNotificacion,
									    int numeroSolicitud,
									    int estado,
									    
									    String lugarProcedencia,
									    String fechaConsultaGeneral,
									    String fechaInicioSintomasGeneral,
									    int tipoCaso,
									    boolean hospitalizadoGeneral,
									    String fechaHospitalizacionGeneral,
									    boolean estaVivoGeneral,
									    String fechaDefuncion,
									    String lugarNoti,
									    int unidadGeneradora,

									    String nombrePadre,
									    String fechaInvestigacion,
									    int identificacionCaso,
									    int contactoCaso,
									    int carneVacunacion,
									    int dosisAplicadas,
									    int tipoVacuna,
									    String cualVacuna,
									    String fechaUltimaDosis,
									    int etapaEnfermedad,
									    int tos,
									    String duracionTos,
									    int tosParoxistica,
									    int estridor,
									    int apnea,
									    int fiebre,
									    int vomitoPostusivo,
									    int complicaciones,
									    int tipoComplicacion,
									    int tratamientoAntibiotico,
									    String tipoAntibiotico,
									    String duracionTratamiento,
									    int investigacionCampo,
									    String fechaOperacionBarrido,
									    String numeroContactos,
									    int quimioprofilaxis,
									    int totalPoblacion1,
									    int totalPoblacion2,
									    int totalPoblacion3,
									    int totalPoblacion4,
									    int dosisDpt1Grupo1,
									    int dosisDpt1Grupo2,
									    int dosisDpt1Grupo3,
									    int dosisDpt1Grupo4,
									    int dosisDpt2Grupo1,
									    int dosisDpt2Grupo2,
									    int dosisDpt2Grupo3,
									    int dosisDpt2Grupo4,
									    int dosisDpt3Grupo1,
									    int dosisDpt3Grupo2,
									    int dosisDpt3Grupo3,
									    int dosisDpt3Grupo4,
									    int dosisRef1Grupo1,
									    int dosisRef1Grupo2,
									    int dosisRef1Grupo3,
									    int dosisRef1Grupo4,
									    int dosisRef2Grupo1,
									    int dosisRef2Grupo2,
									    int dosisRef2Grupo3,
									    int dosisRef2Grupo4,
									    String municipiosVacunados,
										String pais,
									    int areaProcedencia
									    )
	{
		return SqlBaseFichaTosferinaDao.modificarFicha(con,
														sire,
														notificar,
													    loginUsuario,
													    codigoFichaTosferina,
													    codigoPaciente,
													    codigoDiagnostico,
													    codigoNotificacion,
													    numeroSolicitud,
													    estado,
													    
													    lugarProcedencia,
													    fechaConsultaGeneral,
													    fechaInicioSintomasGeneral,
													    tipoCaso,
													    hospitalizadoGeneral,
													    fechaHospitalizacionGeneral,
													    estaVivoGeneral,
													    fechaDefuncion,
													    lugarNoti,
													    unidadGeneradora,
										
													    nombrePadre,
													    fechaInvestigacion,
													    identificacionCaso,
													    contactoCaso,
													    carneVacunacion,
													    dosisAplicadas,
													    tipoVacuna,
													    cualVacuna,
													    fechaUltimaDosis,
													    etapaEnfermedad,
													    tos,
													    duracionTos,
													    tosParoxistica,
													    estridor,
													    apnea,
													    fiebre,
													    vomitoPostusivo,
													    complicaciones,
													    tipoComplicacion,
													    tratamientoAntibiotico,
													    tipoAntibiotico,
													    duracionTratamiento,
													    investigacionCampo,
													    fechaOperacionBarrido,
													    numeroContactos,
													    quimioprofilaxis,
													    totalPoblacion1,
													    totalPoblacion2,
													    totalPoblacion3,
													    totalPoblacion4,
													    dosisDpt1Grupo1,
													    dosisDpt1Grupo2,
													    dosisDpt1Grupo3,
													    dosisDpt1Grupo4,
													    dosisDpt2Grupo1,
													    dosisDpt2Grupo2,
													    dosisDpt2Grupo3,
													    dosisDpt2Grupo4,
													    dosisDpt3Grupo1,
													    dosisDpt3Grupo2,
													    dosisDpt3Grupo3,
													    dosisDpt3Grupo4,
													    dosisRef1Grupo1,
													    dosisRef1Grupo2,
													    dosisRef1Grupo3,
													    dosisRef1Grupo4,
													    dosisRef2Grupo1,
													    dosisRef2Grupo2,
													    dosisRef2Grupo3,
													    dosisRef2Grupo4,
													    municipiosVacunados,
														pais,
													    areaProcedencia);
	}
	
	
	
	
	

	public ResultSet consultaTodoFicha(Connection con, int codigo)
	{
		return SqlBaseFichaTosferinaDao.consultarTodoFichaTosferina(con,codigo);
	}
	
	
	
	public ResultSet consultarDatosPaciente(Connection con, int codigo, boolean empezarnuevo)
	{
		return SqlBaseFichaTosferinaDao.consultarDatosPaciente(con,codigo,empezarnuevo);
	}
	
	
	public ResultSet consultarDatosLaboratorio(Connection con, int codigo)
	{
		return SqlBaseFichaTosferinaDao.consultarDatosLaboratorio(con,codigo);
	}
}
