package com.sysmedica.dao.postgresql;

import java.sql.Connection;
import java.sql.ResultSet;
import java.util.HashMap;

import com.sysmedica.dao.FichaEasvDao;
import com.sysmedica.dao.sqlbase.SqlBaseFichaEasvDao;

public class PostgresqlFichaEasvDao implements FichaEasvDao {

	private String secuenciaStr = "SELECT nextval('epidemiologia.seq_fichas')";
	private String secuenciaVac = "SELECT nextval('epidemiologia.seq_vacunas_implicadas')";
	

	public int insertarFichaCompleta(Connection con,
						    		int numeroSolicitud,
									String login,
									int codigoPaciente,
									String codigoDiagnostico,
									int estado,
									int codigoAseguradora,
									String nombreProfesional,
								    
								    String sire,
									boolean notificar,
									
									int codigoFichaEasv,										    
								    String lugarProcedencia,
								    String fechaConsultaGeneral,
								    String fechaInicioSintomasGeneral,
								    int tipoCaso,
								    boolean hospitalizadoGeneral,
								    String fechaHospitalizacionGeneral,
								    boolean estaVivoGeneral,
								    String fechaDefuncion,
								    String lugarNoti,
								    int unidadGeneradora,
								    
								    int vacuna1,
								    int vacuna2,
								    int vacuna3,
								    int vacuna4,
								    int dosis1,
								    int dosis2,
								    int dosis3,
								    int dosis4,
								    int via1,
								    int via2,
								    int via3,
								    int via4,
								    int sitio1,
								    int sitio2,
								    int sitio3,
								    int sitio4,
								    String fechaVacunacion1,
								    String fechaVacunacion2,
								    String fechaVacunacion3,
								    String fechaVacunacion4,
								    String fabricante1,
								    String fabricante2,
								    String fabricante3,
								    String fabricante4,
								    String lote1,
								    String lote2,
								    String lote3,
								    String lote4,
								    String otroHallazgo,
								    String tiempo,
								    int unidadTiempo,
								    String lugarVacunacion,
								    String codDepVacunacion,
								    String codMunVacunacion,
								    int estadoSalud,
								    int recibiaMedicamentos,
								    String medicamentos,
								    int antPatologicos,
								    String cualesAntPatologicos,
								    int antAlergicos,
								    String cualesAntAlergicos,
								    int antEasv,
								    String cualesAntEasv,
								    int biologico1,
								    String fabricanteMuestra1,
								    String loteMuestra1,
								    String cantidadMuestra1,
								    String fechaEnvioMuestra1,
								    int biologico2,
								    String fabricanteMuestra2,
								    String loteMuestra2,
								    String cantidadMuestra2,
								    String fechaEnvioMuestra2,
								    int estadoFinal,
								    String telefonoContacto,
								    
								    boolean activa,
								    String pais,
								    int areaProcedencia,
								    
								    HashMap hallazgos,
								    HashMap vacunas,
								    String lugarVac
								   )
	{
		return SqlBaseFichaEasvDao.insertarFichaCompleta(con,
												    		numeroSolicitud,
															login,
															codigoPaciente,
															codigoDiagnostico,
															estado,
															codigoAseguradora,
															nombreProfesional,
														    secuenciaStr,
														    
														    sire,
															notificar,
															
															codigoFichaEasv,										    
														    lugarProcedencia,
														    fechaConsultaGeneral,
														    fechaInicioSintomasGeneral,
														    tipoCaso,
														    hospitalizadoGeneral,
														    fechaHospitalizacionGeneral,
														    estaVivoGeneral,
														    fechaDefuncion,
														    lugarNoti,
														    unidadGeneradora,
														    
														    vacuna1,
														    vacuna2,
														    vacuna3,
														    vacuna4,
														    dosis1,
														    dosis2,
														    dosis3,
														    dosis4,
														    via1,
														    via2,
														    via3,
														    via4,
														    sitio1,
														    sitio2,
														    sitio3,
														    sitio4,
														    fechaVacunacion1,
														    fechaVacunacion2,
														    fechaVacunacion3,
														    fechaVacunacion4,
														    fabricante1,
														    fabricante2,
														    fabricante3,
														    fabricante4,
														    lote1,
														    lote2,
														    lote3,
														    lote4,
														    otroHallazgo,
														    tiempo,
														    unidadTiempo,
														    lugarVacunacion,
														    codDepVacunacion,
														    codMunVacunacion,
														    estadoSalud,
														    recibiaMedicamentos,
														    medicamentos,
														    antPatologicos,
														    cualesAntPatologicos,
														    antAlergicos,
														    cualesAntAlergicos,
														    antEasv,
														    cualesAntEasv,
														    biologico1,
														    fabricanteMuestra1,
														    loteMuestra1,
														    cantidadMuestra1,
														    fechaEnvioMuestra1,
														    biologico2,
														    fabricanteMuestra2,
														    loteMuestra2,
														    cantidadMuestra2,
														    fechaEnvioMuestra2,
														    estadoFinal,
														    telefonoContacto,
														    
														    activa,
														    pais,
														    areaProcedencia,
														    
														    hallazgos,
														    vacunas,
														    secuenciaVac,
														    lugarVac);
	}
	
	
	

	public int modificarFicha(Connection con,
									String sire,
									boolean notificar,
								    String loginUsuario,
								    int codigoFichaEasv,
								    int codigoPaciente,
								    String codigoDiagnostico,
								    int codigoNotificacion,
								    int numeroSolicitud,
								    int estado,
								    
								    String lugarProcedencia,
								    String fechaConsultaGeneral,
								    String fechaInicioSintomasGeneral,
								    int tipoCaso,
								    boolean hospitalizadoGeneral,
								    String fechaHospitalizacionGeneral,
								    boolean estaVivoGeneral,
								    String fechaDefuncion,
								    String lugarNoti,
								    int unidadGeneradora,

								    int vacuna1,
								    int vacuna2,
								    int vacuna3,
								    int vacuna4,
								    int dosis1,
								    int dosis2,
								    int dosis3,
								    int dosis4,
								    int via1,
								    int via2,
								    int via3,
								    int via4,
								    int sitio1,
								    int sitio2,
								    int sitio3,
								    int sitio4,
								    String fechaVacunacion1,
								    String fechaVacunacion2,
								    String fechaVacunacion3,
								    String fechaVacunacion4,
								    String fabricante1,
								    String fabricante2,
								    String fabricante3,
								    String fabricante4,
								    String lote1,
								    String lote2,
								    String lote3,
								    String lote4,
								    String otroHallazgo,
								    String tiempo,
								    int unidadTiempo,
								    String lugarVacunacion,
								    String codDepVacunacion,
								    String codMunVacunacion,
								    int estadoSalud,
								    int recibiaMedicamentos,
								    String medicamentos,
								    int antPatologicos,
								    String cualesAntPatologicos,
								    int antAlergicos,
								    String cualesAntAlergicos,
								    int antEasv,
								    String cualesAntEasv,
								    int biologico1,
								    String fabricanteMuestra1,
								    String loteMuestra1,
								    String cantidadMuestra1,
								    String fechaEnvioMuestra1,
								    int biologico2,
								    String fabricanteMuestra2,
								    String loteMuestra2,
								    String cantidadMuestra2,
								    String fechaEnvioMuestra2,
								    int estadoFinal,
								    String telefonoContacto,
									String pais,
								    int areaProcedencia,
								    HashMap hallazgos,
								    HashMap vacunas,
								    String lugarVac
								    )
	{
		return SqlBaseFichaEasvDao.modificarFicha(con,
													sire,
													notificar,
												    loginUsuario,
												    codigoFichaEasv,
												    codigoPaciente,
												    codigoDiagnostico,
												    codigoNotificacion,
												    numeroSolicitud,
												    estado,
												    
												    lugarProcedencia,
												    fechaConsultaGeneral,
												    fechaInicioSintomasGeneral,
												    tipoCaso,
												    hospitalizadoGeneral,
												    fechaHospitalizacionGeneral,
												    estaVivoGeneral,
												    fechaDefuncion,
												    lugarNoti,
												    unidadGeneradora,
									
												    vacuna1,
												    vacuna2,
												    vacuna3,
												    vacuna4,
												    dosis1,
												    dosis2,
												    dosis3,
												    dosis4,
												    via1,
												    via2,
												    via3,
												    via4,
												    sitio1,
												    sitio2,
												    sitio3,
												    sitio4,
												    fechaVacunacion1,
												    fechaVacunacion2,
												    fechaVacunacion3,
												    fechaVacunacion4,
												    fabricante1,
												    fabricante2,
												    fabricante3,
												    fabricante4,
												    lote1,
												    lote2,
												    lote3,
												    lote4,
												    otroHallazgo,
												    tiempo,
												    unidadTiempo,
												    lugarVacunacion,
												    codDepVacunacion,
												    codMunVacunacion,
												    estadoSalud,
												    recibiaMedicamentos,
												    medicamentos,
												    antPatologicos,
												    cualesAntPatologicos,
												    antAlergicos,
												    cualesAntAlergicos,
												    antEasv,
												    cualesAntEasv,
												    biologico1,
												    fabricanteMuestra1,
												    loteMuestra1,
												    cantidadMuestra1,
												    fechaEnvioMuestra1,
												    biologico2,
												    fabricanteMuestra2,
												    loteMuestra2,
												    cantidadMuestra2,
												    fechaEnvioMuestra2,
												    estadoFinal,
												    telefonoContacto,
													pais,
												    areaProcedencia,
												    hallazgos,
												    vacunas,
												    secuenciaVac,
												    lugarVac);
	}
	
	
	
	
	public ResultSet consultaTodoFicha(Connection con, int codigo)
	{
		return SqlBaseFichaEasvDao.consultarTodoFichaEasv(con,codigo);
	}
	
	
	
	
	public ResultSet consultarDatosPaciente(Connection con, int codigo, boolean empezarnuevo)
	{
		return SqlBaseFichaEasvDao.consultarDatosPaciente(con,codigo,empezarnuevo);
	}
	
	
	
	
	public ResultSet consultarHallazgos(Connection con, int codigo)
	{
		return SqlBaseFichaEasvDao.consultarHallazgos(con,codigo);
	}
	
	
	
	
	public ResultSet consultarVacunas(Connection con, int codigo)
	{
		return SqlBaseFichaEasvDao.consultarVacunas(con,codigo);
	}
}
