//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.08.25 at 10:23:45 AM COT 
//


package com.princetonsa.autorizaciones.solicitudAutorizacionServicios;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EstructuraSolicitudAutorizacion complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EstructuraSolicitudAutorizacion">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="General" type="{}General"/>
 *         &lt;element name="Pagador" type="{}Pagador"/>
 *         &lt;element name="Paciente" type="{}Paciente"/>
 *         &lt;element name="CoberturaSalud" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="OrigenAtencion" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="UbicacionPaciente" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="ServicioHospitalizacion" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CamaHospitalizacion" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="GuiaManejoIntegral" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ServiciosSolicitados" type="{}ServicioSalud" maxOccurs="unbounded"/>
 *         &lt;element name="JustificacionClinica" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ImpresionDiagnostica" type="{}Diagnostico" maxOccurs="unbounded"/>
 *         &lt;element name="ProfesionalSolicitante" type="{}ProfesionalSalud"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EstructuraSolicitudAutorizacion", propOrder = {
    "general",
    "pagador",
    "paciente",
    "coberturaSalud",
    "origenAtencion",
    "ubicacionPaciente",
    "servicioHospitalizacion",
    "camaHospitalizacion",
    "guiaManejoIntegral",
    "serviciosSolicitados",
    "justificacionClinica",
    "impresionDiagnostica",
    "profesionalSolicitante"
})
public class EstructuraSolicitudAutorizacion {

    @XmlElement(name = "General", required = true)
    protected General general;
    @XmlElement(name = "Pagador", required = true)
    protected Pagador pagador;
    @XmlElement(name = "Paciente", required = true)
    protected Paciente paciente;
    @XmlElement(name = "CoberturaSalud", required = true)
    protected String coberturaSalud;
    @XmlElement(name = "OrigenAtencion", required = true)
    protected String origenAtencion;
    @XmlElement(name = "UbicacionPaciente")
    protected int ubicacionPaciente;
    @XmlElement(name = "ServicioHospitalizacion", required = true)
    protected String servicioHospitalizacion;
    @XmlElement(name = "CamaHospitalizacion", required = true)
    protected String camaHospitalizacion;
    @XmlElement(name = "GuiaManejoIntegral", required = true)
    protected String guiaManejoIntegral;
    @XmlElement(name = "ServiciosSolicitados", required = true)
    protected List<ServicioSalud> serviciosSolicitados;
    @XmlElement(name = "JustificacionClinica", required = true)
    protected String justificacionClinica;
    @XmlElement(name = "ImpresionDiagnostica", required = true)
    protected List<Diagnostico> impresionDiagnostica;
    @XmlElement(name = "ProfesionalSolicitante", required = true)
    protected ProfesionalSalud profesionalSolicitante;

    /**
     * Gets the value of the general property.
     * 
     * @return
     *     possible object is
     *     {@link General }
     *     
     */
    public General getGeneral() {
        return general;
    }

    /**
     * Sets the value of the general property.
     * 
     * @param value
     *     allowed object is
     *     {@link General }
     *     
     */
    public void setGeneral(General value) {
        this.general = value;
    }

    /**
     * Gets the value of the pagador property.
     * 
     * @return
     *     possible object is
     *     {@link Pagador }
     *     
     */
    public Pagador getPagador() {
        return pagador;
    }

    /**
     * Sets the value of the pagador property.
     * 
     * @param value
     *     allowed object is
     *     {@link Pagador }
     *     
     */
    public void setPagador(Pagador value) {
        this.pagador = value;
    }

    /**
     * Gets the value of the paciente property.
     * 
     * @return
     *     possible object is
     *     {@link Paciente }
     *     
     */
    public Paciente getPaciente() {
        return paciente;
    }

    /**
     * Sets the value of the paciente property.
     * 
     * @param value
     *     allowed object is
     *     {@link Paciente }
     *     
     */
    public void setPaciente(Paciente value) {
        this.paciente = value;
    }

    /**
     * Gets the value of the coberturaSalud property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCoberturaSalud() {
        return coberturaSalud;
    }

    /**
     * Sets the value of the coberturaSalud property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCoberturaSalud(String value) {
        this.coberturaSalud = value;
    }

    /**
     * Gets the value of the origenAtencion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrigenAtencion() {
        return origenAtencion;
    }

    /**
     * Sets the value of the origenAtencion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrigenAtencion(String value) {
        this.origenAtencion = value;
    }

    /**
     * Gets the value of the ubicacionPaciente property.
     * 
     */
    public int getUbicacionPaciente() {
        return ubicacionPaciente;
    }

    /**
     * Sets the value of the ubicacionPaciente property.
     * 
     */
    public void setUbicacionPaciente(int value) {
        this.ubicacionPaciente = value;
    }

    /**
     * Gets the value of the servicioHospitalizacion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServicioHospitalizacion() {
        return servicioHospitalizacion;
    }

    /**
     * Sets the value of the servicioHospitalizacion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServicioHospitalizacion(String value) {
        this.servicioHospitalizacion = value;
    }

    /**
     * Gets the value of the camaHospitalizacion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCamaHospitalizacion() {
        return camaHospitalizacion;
    }

    /**
     * Sets the value of the camaHospitalizacion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCamaHospitalizacion(String value) {
        this.camaHospitalizacion = value;
    }

    /**
     * Gets the value of the guiaManejoIntegral property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGuiaManejoIntegral() {
        return guiaManejoIntegral;
    }

    /**
     * Sets the value of the guiaManejoIntegral property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGuiaManejoIntegral(String value) {
        this.guiaManejoIntegral = value;
    }

    /**
     * Gets the value of the serviciosSolicitados property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the serviciosSolicitados property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getServiciosSolicitados().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ServicioSalud }
     * 
     * 
     */
    public List<ServicioSalud> getServiciosSolicitados() {
        if (serviciosSolicitados == null) {
            serviciosSolicitados = new ArrayList<ServicioSalud>();
        }
        return this.serviciosSolicitados;
    }

    /**
     * Gets the value of the justificacionClinica property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJustificacionClinica() {
        return justificacionClinica;
    }

    /**
     * Sets the value of the justificacionClinica property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJustificacionClinica(String value) {
        this.justificacionClinica = value;
    }

    /**
     * Gets the value of the impresionDiagnostica property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the impresionDiagnostica property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getImpresionDiagnostica().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Diagnostico }
     * 
     * 
     */
    public List<Diagnostico> getImpresionDiagnostica() {
        if (impresionDiagnostica == null) {
            impresionDiagnostica = new ArrayList<Diagnostico>();
        }
        return this.impresionDiagnostica;
    }

    /**
     * Gets the value of the profesionalSolicitante property.
     * 
     * @return
     *     possible object is
     *     {@link ProfesionalSalud }
     *     
     */
    public ProfesionalSalud getProfesionalSolicitante() {
        return profesionalSolicitante;
    }

    /**
     * Sets the value of the profesionalSolicitante property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProfesionalSalud }
     *     
     */
    public void setProfesionalSolicitante(ProfesionalSalud value) {
        this.profesionalSolicitante = value;
    }

	/**
	 * @param serviciosSolicitados the serviciosSolicitados to set
	 */
	public void setServiciosSolicitados(List<ServicioSalud> serviciosSolicitados) {
		this.serviciosSolicitados = serviciosSolicitados;
	}

	/**
	 * @param impresionDiagnostica the impresionDiagnostica to set
	 */
	public void setImpresionDiagnostica(List<Diagnostico> impresionDiagnostica) {
		this.impresionDiagnostica = impresionDiagnostica;
	}
    
}
