package com.sysmedica.dao.postgresql;

import java.sql.Connection;
import java.sql.ResultSet;

import com.sysmedica.dao.FichaIntoxicacionesDao;
import com.sysmedica.dao.sqlbase.SqlBaseFichaIntoxicacionesDao;

public class PostgresqlFichaIntoxicacionesDao implements FichaIntoxicacionesDao {

	private String secuenciaStr = "SELECT nextval('epidemiologia.seq_fichas')";
	
	public int insertarFichaCompleta(Connection con,
							    		int numeroSolicitud,
										String login,
										int codigoPaciente,
										String codigoDiagnostico,
										int estado,
										int codigoAseguradora,
										String nombreProfesional,
									    
									    String sire,
										boolean notificar,
										
										int codigoFichaIntoxicacion,										    
									    String lugarProcedencia,
									    String fechaConsultaGeneral,
									    String fechaInicioSintomasGeneral,
									    int tipoCaso,
									    boolean hospitalizadoGeneral,
									    String fechaHospitalizacionGeneral,
									    boolean estaVivoGeneral,
									    String fechaDefuncion,
									    String lugarNoti,
									    int unidadGeneradora,
									    
									    int tipoIntoxicacion,
									    String nombreProducto,
									    int tipoExposicion,
									    int produccion,
									    int almacenamiento,
									    int agricola,
									    int saludPublica,
									    int domiciliaria,
									    int tratHumano,
									    int tratVeterinario,
									    int transporte,
									    int mezcla,
									    int mantenimiento,
									    int cultivo,
									    int otros,
									    String otraActividad,
									    String fechaExposicion,
									    int horaExposicion,
									    int viaExposicion,
									    String otraViaExposicion,
									    int escolaridad,
									    int embarazada,
									    int vinculoLaboral,
									    int afiliadoArp,
									    String nombreArp,
									    int codgoArp,
									    int estCivil,
									    int alerta,
									    int investigacion,
									    String fechaInvestigacion,
									    String fechaInforma,
									    String nombreResponsable,
									    String telefonoResponsable,
									    String observaciones,
									    
									    boolean activa,
									    String pais,
									    int areaProcedencia
									   )
	{
		return SqlBaseFichaIntoxicacionesDao.insertarFichaCompleta(con,
														    		numeroSolicitud,
																	login,
																	codigoPaciente,
																	codigoDiagnostico,
																	estado,
																	codigoAseguradora,
																	nombreProfesional,
																    secuenciaStr,
																    
																    sire,
																	notificar,
																	
																	codigoFichaIntoxicacion,										    
																    lugarProcedencia,
																    fechaConsultaGeneral,
																    fechaInicioSintomasGeneral,
																    tipoCaso,
																    hospitalizadoGeneral,
																    fechaHospitalizacionGeneral,
																    estaVivoGeneral,
																    fechaDefuncion,
																    lugarNoti,
																    unidadGeneradora,
																    
																    tipoIntoxicacion,
																    nombreProducto,
																    tipoExposicion,
																    produccion,
																    almacenamiento,
																    agricola,
																    saludPublica,
																    domiciliaria,
																    tratHumano,
																    tratVeterinario,
																    transporte,
																    mezcla,
																    mantenimiento,
																    cultivo,
																    otros,
																    otraActividad,
																    fechaExposicion,
																    horaExposicion,
																    viaExposicion,
																    otraViaExposicion,
																    escolaridad,
																    embarazada,
																    vinculoLaboral,
																    afiliadoArp,
																    nombreArp,
																    codgoArp,
																    estCivil,
																    alerta,
																    investigacion,
																    fechaInvestigacion,
																    fechaInforma,
																    nombreResponsable,
																    telefonoResponsable,
																    observaciones,
																    
																    activa,
																    pais,
																    areaProcedencia);
	}


	public int modificarFicha(Connection con,
								String sire,
								boolean notificar,
								String loginUsuario,
								int codigoFichaIntoxicacion,
								int codigoPaciente,
								String codigoDiagnostico,
								int codigoNotificacion,
								int numeroSolicitud,
								int estado,
								
								String lugarProcedencia,
								String fechaConsultaGeneral,
								String fechaInicioSintomasGeneral,
								int tipoCaso,
								boolean hospitalizadoGeneral,
								String fechaHospitalizacionGeneral,
								boolean estaVivoGeneral,
								String fechaDefuncion,
								String lugarNoti,
								int unidadGeneradora,
								
								int tipoIntoxicacion,
								String nombreProducto,
								int tipoExposicion,
								int produccion,
								int almacenamiento,
								int agricola,
								int saludPublica,
								int domiciliaria,
								int tratHumano,
								int tratVeterinario,
								int transporte,
								int mezcla,
								int mantenimiento,
								int cultivo,
								int otros,
								String otraActividad,
								String fechaExposicion,
								int horaExposicion,
								int viaExposicion,
								String otraViaExposicion,
								int escolaridad,
								int embarazada,
								int vinculoLaboral,
							    int afiliadoArp,
							    String nombreArp,
							    int codgoArp,
							    int estCivil,
								int alerta,
								int investigacion,
								String fechaInvestigacion,
								String fechaInforma,
								String nombreResponsable,
								String telefonoResponsable,
								String observaciones,
								String pais,
								int areaProcedencia
								)
	{
		return SqlBaseFichaIntoxicacionesDao.modificarFicha(con,
															sire,
															notificar,
															loginUsuario,
															codigoFichaIntoxicacion,
															codigoPaciente,
															codigoDiagnostico,
															codigoNotificacion,
															numeroSolicitud,
															estado,
															
															lugarProcedencia,
															fechaConsultaGeneral,
															fechaInicioSintomasGeneral,
															tipoCaso,
															hospitalizadoGeneral,
															fechaHospitalizacionGeneral,
															estaVivoGeneral,
															fechaDefuncion,
															lugarNoti,
															unidadGeneradora,
															
															tipoIntoxicacion,
															nombreProducto,
															tipoExposicion,
															produccion,
															almacenamiento,
															agricola,
															saludPublica,
															domiciliaria,
															tratHumano,
															tratVeterinario,
															transporte,
															mezcla,
															mantenimiento,
															cultivo,
															otros,
															otraActividad,
															fechaExposicion,
															horaExposicion,
															viaExposicion,
															otraViaExposicion,
															escolaridad,
															embarazada,
															vinculoLaboral,
														    afiliadoArp,
														    nombreArp,
														    codgoArp,
														    estCivil,
															alerta,
															investigacion,
															fechaInvestigacion,
															fechaInforma,
															nombreResponsable,
															telefonoResponsable,
															observaciones,
															pais,
															areaProcedencia);
	}


	public ResultSet consultaTodoFicha(Connection con, int codigo)
	{
		return SqlBaseFichaIntoxicacionesDao.consultarTodoFichaIntoxicacion(con,codigo);
	}



	public ResultSet consultarDatosPaciente(Connection con, int codigo, boolean empezarnuevo)
	{
		return SqlBaseFichaIntoxicacionesDao.consultarDatosPaciente(con,codigo,empezarnuevo);
	}
}
