package com.sysmedica.dao;

import java.sql.Connection;
import java.sql.ResultSet;
import java.util.HashMap;

public interface FichaMortalidadDao {

	public int insertarFicha(Connection con,
								boolean notificar,
							    String loginUsuario,
							    int codigoFichaTuberculosis,
							    int codigoPaciente,
							    String codigoDiagnostico,
							    int codigoNotificacion,
							    int numeroSolicitud,
							    int codigoAseguradora,
								String nombreProfesional,
							    int estado
							    );
	
	
	public int modificarFicha(Connection con,
								String sire,
								String loginUsuario,
							    int codigoFichaMortalidad,
							    int estado,
							    
							    int sitioDefuncion,
								String descripcionSitio,
								int convivencia,
								String otroConvivencia,
								int escolaridad,
								int fecundidad,
								String gestaciones,
								String partos,
								String cesareas,
								String abortos,
								String sustanciasSico,
								String trastornoMental,
								String infecciones,
								String factoresRiesgo,
								int controlPrenatal,
								String cuantosControles,
								int trimInicio,
								int controlesRealizadosPor,
								int nivelAtencion,
								int clasificacionRiesgo,
								int remisionesOportunas,
								HashMap complicaciones,
								int momentoFallecimiento,
								String semanasGestacion,
								int tipoParto,
								int atendidoPor,
								int nivelAtencion2,
								int momentoMuerteRelacion,
								String edadGestacional,
								String pesoNacimiento,
								String tallaNacimiento,
								int sexo,
								String apgarNacimiento1,
								String apgarNacimiento5,
								String apgarNacimiento15,
								int nivelAtencion3,
								int adaptacionNeonatal,
								String causaDirectaDefuncion,
								String causaBasicaDefuncion,
								int muerteDemora,
								int causaMuerteDet,
							    
								String lugarProcedencia,
							    String fechaConsultaGeneral,
							    String fechaInicioSintomasGeneral,
							    int tipoCaso,
							    boolean hospitalizadoGeneral,
							    String fechaHospitalizacionGeneral,
							    boolean estaVivoGeneral,
							    String fechaDefuncion,
							    String lugarNoti,
							    int unidadGeneradora,
							    String complicacionesAntecedentes,
							    String muertos,
							    String vivos,
							    int semanaInicioCpn,
							    int quienClasificoRiesgo,
							    int remisionOportunaComplica,
							    String muerteDemora1,
							    String muerteDemora2,
							    String muerteDemora3,
							    String muerteDemora4,
							    HashMap antecedentes,
							    String pais,
							    int areaProcedencia
							    );
	
	
	public ResultSet consultaTodoFicha(Connection con, int codigo);
	
	
	public ResultSet consultarComplicaciones(Connection con, int codigo);
	
	
	public ResultSet consultarAntecedentes(Connection con, int codigo);
	
	
	public ResultSet consultaDatosPaciente(Connection con, int codigo,boolean empezarnuevo);
	
	
	public int insertarFichaCompleta(Connection con,
											int numeroSolicitud,
											String login,
											int codigoPaciente,
											String codigoDiagnostico,
											int estado,
											int codigoAseguradora,
											String nombreProfesional,
										    
										    String sire,
										    int sitioDefuncion,
											String descripcionSitio,
											int convivencia,
											String otroConvivencia,
											int escolaridad,
											int fecundidad,
											String gestaciones,
											String partos,
											String cesareas,
											String abortos,
											String sustanciasSico,
											String trastornoMental,
											String infecciones,
											String factoresRiesgo,
											int controlPrenatal,
											String cuantosControles,
											int trimInicio,
											int controlesRealizadosPor,
											int nivelAtencion,
											int clasificacionRiesgo,
											int remisionesOportunas,
											HashMap complicaciones,
											String complicacionesAntecedentes,
											int momentoFallecimiento,
											String semanasGestacion,
											int tipoParto,
											int atendidoPor,
											int nivelAtencion2,
											int momentoMuerteRelacion,
											String edadGestacional,
											String pesoNacimiento,
											String tallaNacimiento,
											int sexo,
											String apgarNacimiento1,
											String apgarNacimiento5,
											String apgarNacimiento15,
											int nivelAtencion3,
											int adaptacionNeonatal,
											String causaDirectaDefuncion,
											String causaBasicaDefuncion,
											int muerteDemora,
											int causaMuerteDet,
										    
											String lugarProcedencia,
										    String fechaConsultaGeneral,
										    String fechaInicioSintomasGeneral,
										    int tipoCaso,
										    boolean hospitalizadoGeneral,
										    String fechaHospitalizacionGeneral,
										    boolean estaVivoGeneral,
										    String fechaDefuncion,
										    String lugarNoti,
										    int unidadGeneradora,
										    boolean activa,
										    String muertos,
										    String vivos,
										    int semanaInicioCpn,
										    int quienClasificoRiesgo,
										    int remisionOportunaComplica,
										    String muerteDemora1,
										    String muerteDemora2,
										    String muerteDemora3,
										    String muerteDemora4,
										    HashMap antecedentes,
										    String pais,
										    int areaProcedencia
										   );
}
