//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.08.25 at 10:23:45 AM COT 
//


package com.princetonsa.autorizaciones.solicitudAutorizacionServicios;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ServicioSalud complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ServicioSalud">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="TipoServicio1" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CodigoCUPS1" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Cantidad1" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="Descripcion1" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="TipoServicio2" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CodigoCUPS2" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Cantidad2" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="Descripcion2" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="TipoServicio3" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CodigoCUPS3" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Cantidad3" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="Descripcion3" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="TipoServicio4" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CodigoCUPS4" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Cantidad4" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="Descripcion4" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="TipoServicio5" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CodigoCUPS5" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Cantidad5" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="Descripcion5" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="TipoServicio6" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CodigoCUPS6" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Cantidad6" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="Descripcion6" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="TipoServicio7" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CodigoCUPS7" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Cantidad7" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="Descripcion7" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="TipoServicio8" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CodigoCUPS8" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Cantidad8" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="Descripcion8" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="TipoServicio9" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CodigoCUPS9" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Cantidad9" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="Descripcion9" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="TipoServicio10" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CodigoCUPS10" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Cantidad10" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="Descripcion10" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="TipoServicio11" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CodigoCUPS11" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Cantidad11" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="Descripcion11" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="TipoServicio12" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CodigoCUPS12" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Cantidad12" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="Descripcion12" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ServicioSalud", propOrder = {
    "tipoServicio1",
    "codigoCUPS1",
    "cantidad1",
    "descripcion1",
    "tipoServicio2",
    "codigoCUPS2",
    "cantidad2",
    "descripcion2",
    "tipoServicio3",
    "codigoCUPS3",
    "cantidad3",
    "descripcion3",
    "tipoServicio4",
    "codigoCUPS4",
    "cantidad4",
    "descripcion4",
    "tipoServicio5",
    "codigoCUPS5",
    "cantidad5",
    "descripcion5",
    "tipoServicio6",
    "codigoCUPS6",
    "cantidad6",
    "descripcion6",
    "tipoServicio7",
    "codigoCUPS7",
    "cantidad7",
    "descripcion7",
    "tipoServicio8",
    "codigoCUPS8",
    "cantidad8",
    "descripcion8",
    "tipoServicio9",
    "codigoCUPS9",
    "cantidad9",
    "descripcion9",
    "tipoServicio10",
    "codigoCUPS10",
    "cantidad10",
    "descripcion10",
    "tipoServicio11",
    "codigoCUPS11",
    "cantidad11",
    "descripcion11",
    "tipoServicio12",
    "codigoCUPS12",
    "cantidad12",
    "descripcion12"
})
public class ServicioSalud {

    @XmlElement(name = "TipoServicio1", required = true)
    protected String tipoServicio1;
    @XmlElement(name = "CodigoCUPS1", required = true)
    protected String codigoCUPS1;
    @XmlElement(name = "Cantidad1")
    protected int cantidad1;
    @XmlElement(name = "Descripcion1", required = true)
    protected String descripcion1;
    @XmlElement(name = "TipoServicio2", required = true)
    protected String tipoServicio2;
    @XmlElement(name = "CodigoCUPS2", required = true)
    protected String codigoCUPS2;
    @XmlElement(name = "Cantidad2")
    protected int cantidad2;
    @XmlElement(name = "Descripcion2", required = true)
    protected String descripcion2;
    @XmlElement(name = "TipoServicio3", required = true)
    protected String tipoServicio3;
    @XmlElement(name = "CodigoCUPS3", required = true)
    protected String codigoCUPS3;
    @XmlElement(name = "Cantidad3")
    protected int cantidad3;
    @XmlElement(name = "Descripcion3", required = true)
    protected String descripcion3;
    @XmlElement(name = "TipoServicio4", required = true)
    protected String tipoServicio4;
    @XmlElement(name = "CodigoCUPS4", required = true)
    protected String codigoCUPS4;
    @XmlElement(name = "Cantidad4")
    protected int cantidad4;
    @XmlElement(name = "Descripcion4", required = true)
    protected String descripcion4;
    @XmlElement(name = "TipoServicio5", required = true)
    protected String tipoServicio5;
    @XmlElement(name = "CodigoCUPS5", required = true)
    protected String codigoCUPS5;
    @XmlElement(name = "Cantidad5")
    protected int cantidad5;
    @XmlElement(name = "Descripcion5", required = true)
    protected String descripcion5;
    @XmlElement(name = "TipoServicio6", required = true)
    protected String tipoServicio6;
    @XmlElement(name = "CodigoCUPS6", required = true)
    protected String codigoCUPS6;
    @XmlElement(name = "Cantidad6")
    protected int cantidad6;
    @XmlElement(name = "Descripcion6", required = true)
    protected String descripcion6;
    @XmlElement(name = "TipoServicio7", required = true)
    protected String tipoServicio7;
    @XmlElement(name = "CodigoCUPS7", required = true)
    protected String codigoCUPS7;
    @XmlElement(name = "Cantidad7")
    protected int cantidad7;
    @XmlElement(name = "Descripcion7", required = true)
    protected String descripcion7;
    @XmlElement(name = "TipoServicio8", required = true)
    protected String tipoServicio8;
    @XmlElement(name = "CodigoCUPS8", required = true)
    protected String codigoCUPS8;
    @XmlElement(name = "Cantidad8")
    protected int cantidad8;
    @XmlElement(name = "Descripcion8", required = true)
    protected String descripcion8;
    @XmlElement(name = "TipoServicio9", required = true)
    protected String tipoServicio9;
    @XmlElement(name = "CodigoCUPS9", required = true)
    protected String codigoCUPS9;
    @XmlElement(name = "Cantidad9")
    protected int cantidad9;
    @XmlElement(name = "Descripcion9", required = true)
    protected String descripcion9;
    @XmlElement(name = "TipoServicio10", required = true)
    protected String tipoServicio10;
    @XmlElement(name = "CodigoCUPS10", required = true)
    protected String codigoCUPS10;
    @XmlElement(name = "Cantidad10")
    protected int cantidad10;
    @XmlElement(name = "Descripcion10", required = true)
    protected String descripcion10;
    @XmlElement(name = "TipoServicio11", required = true)
    protected String tipoServicio11;
    @XmlElement(name = "CodigoCUPS11", required = true)
    protected String codigoCUPS11;
    @XmlElement(name = "Cantidad11")
    protected int cantidad11;
    @XmlElement(name = "Descripcion11", required = true)
    protected String descripcion11;
    @XmlElement(name = "TipoServicio12", required = true)
    protected String tipoServicio12;
    @XmlElement(name = "CodigoCUPS12", required = true)
    protected String codigoCUPS12;
    @XmlElement(name = "Cantidad12")
    protected int cantidad12;
    @XmlElement(name = "Descripcion12", required = true)
    protected String descripcion12;

    /**
     * Gets the value of the tipoServicio1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTipoServicio1() {
        return tipoServicio1;
    }

    /**
     * Sets the value of the tipoServicio1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTipoServicio1(String value) {
        this.tipoServicio1 = value;
    }

    /**
     * Gets the value of the codigoCUPS1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodigoCUPS1() {
        return codigoCUPS1;
    }

    /**
     * Sets the value of the codigoCUPS1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodigoCUPS1(String value) {
        this.codigoCUPS1 = value;
    }

    /**
     * Gets the value of the cantidad1 property.
     * 
     */
    public int getCantidad1() {
        return cantidad1;
    }

    /**
     * Sets the value of the cantidad1 property.
     * 
     */
    public void setCantidad1(int value) {
        this.cantidad1 = value;
    }

    /**
     * Gets the value of the descripcion1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescripcion1() {
        return descripcion1;
    }

    /**
     * Sets the value of the descripcion1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescripcion1(String value) {
        this.descripcion1 = value;
    }

    /**
     * Gets the value of the tipoServicio2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTipoServicio2() {
        return tipoServicio2;
    }

    /**
     * Sets the value of the tipoServicio2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTipoServicio2(String value) {
        this.tipoServicio2 = value;
    }

    /**
     * Gets the value of the codigoCUPS2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodigoCUPS2() {
        return codigoCUPS2;
    }

    /**
     * Sets the value of the codigoCUPS2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodigoCUPS2(String value) {
        this.codigoCUPS2 = value;
    }

    /**
     * Gets the value of the cantidad2 property.
     * 
     */
    public int getCantidad2() {
        return cantidad2;
    }

    /**
     * Sets the value of the cantidad2 property.
     * 
     */
    public void setCantidad2(int value) {
        this.cantidad2 = value;
    }

    /**
     * Gets the value of the descripcion2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescripcion2() {
        return descripcion2;
    }

    /**
     * Sets the value of the descripcion2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescripcion2(String value) {
        this.descripcion2 = value;
    }

    /**
     * Gets the value of the tipoServicio3 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTipoServicio3() {
        return tipoServicio3;
    }

    /**
     * Sets the value of the tipoServicio3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTipoServicio3(String value) {
        this.tipoServicio3 = value;
    }

    /**
     * Gets the value of the codigoCUPS3 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodigoCUPS3() {
        return codigoCUPS3;
    }

    /**
     * Sets the value of the codigoCUPS3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodigoCUPS3(String value) {
        this.codigoCUPS3 = value;
    }

    /**
     * Gets the value of the cantidad3 property.
     * 
     */
    public int getCantidad3() {
        return cantidad3;
    }

    /**
     * Sets the value of the cantidad3 property.
     * 
     */
    public void setCantidad3(int value) {
        this.cantidad3 = value;
    }

    /**
     * Gets the value of the descripcion3 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescripcion3() {
        return descripcion3;
    }

    /**
     * Sets the value of the descripcion3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescripcion3(String value) {
        this.descripcion3 = value;
    }

    /**
     * Gets the value of the tipoServicio4 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTipoServicio4() {
        return tipoServicio4;
    }

    /**
     * Sets the value of the tipoServicio4 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTipoServicio4(String value) {
        this.tipoServicio4 = value;
    }

    /**
     * Gets the value of the codigoCUPS4 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodigoCUPS4() {
        return codigoCUPS4;
    }

    /**
     * Sets the value of the codigoCUPS4 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodigoCUPS4(String value) {
        this.codigoCUPS4 = value;
    }

    /**
     * Gets the value of the cantidad4 property.
     * 
     */
    public int getCantidad4() {
        return cantidad4;
    }

    /**
     * Sets the value of the cantidad4 property.
     * 
     */
    public void setCantidad4(int value) {
        this.cantidad4 = value;
    }

    /**
     * Gets the value of the descripcion4 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescripcion4() {
        return descripcion4;
    }

    /**
     * Sets the value of the descripcion4 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescripcion4(String value) {
        this.descripcion4 = value;
    }

    /**
     * Gets the value of the tipoServicio5 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTipoServicio5() {
        return tipoServicio5;
    }

    /**
     * Sets the value of the tipoServicio5 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTipoServicio5(String value) {
        this.tipoServicio5 = value;
    }

    /**
     * Gets the value of the codigoCUPS5 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodigoCUPS5() {
        return codigoCUPS5;
    }

    /**
     * Sets the value of the codigoCUPS5 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodigoCUPS5(String value) {
        this.codigoCUPS5 = value;
    }

    /**
     * Gets the value of the cantidad5 property.
     * 
     */
    public int getCantidad5() {
        return cantidad5;
    }

    /**
     * Sets the value of the cantidad5 property.
     * 
     */
    public void setCantidad5(int value) {
        this.cantidad5 = value;
    }

    /**
     * Gets the value of the descripcion5 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescripcion5() {
        return descripcion5;
    }

    /**
     * Sets the value of the descripcion5 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescripcion5(String value) {
        this.descripcion5 = value;
    }

    /**
     * Gets the value of the tipoServicio6 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTipoServicio6() {
        return tipoServicio6;
    }

    /**
     * Sets the value of the tipoServicio6 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTipoServicio6(String value) {
        this.tipoServicio6 = value;
    }

    /**
     * Gets the value of the codigoCUPS6 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodigoCUPS6() {
        return codigoCUPS6;
    }

    /**
     * Sets the value of the codigoCUPS6 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodigoCUPS6(String value) {
        this.codigoCUPS6 = value;
    }

    /**
     * Gets the value of the cantidad6 property.
     * 
     */
    public int getCantidad6() {
        return cantidad6;
    }

    /**
     * Sets the value of the cantidad6 property.
     * 
     */
    public void setCantidad6(int value) {
        this.cantidad6 = value;
    }

    /**
     * Gets the value of the descripcion6 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescripcion6() {
        return descripcion6;
    }

    /**
     * Sets the value of the descripcion6 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescripcion6(String value) {
        this.descripcion6 = value;
    }

    /**
     * Gets the value of the tipoServicio7 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTipoServicio7() {
        return tipoServicio7;
    }

    /**
     * Sets the value of the tipoServicio7 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTipoServicio7(String value) {
        this.tipoServicio7 = value;
    }

    /**
     * Gets the value of the codigoCUPS7 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodigoCUPS7() {
        return codigoCUPS7;
    }

    /**
     * Sets the value of the codigoCUPS7 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodigoCUPS7(String value) {
        this.codigoCUPS7 = value;
    }

    /**
     * Gets the value of the cantidad7 property.
     * 
     */
    public int getCantidad7() {
        return cantidad7;
    }

    /**
     * Sets the value of the cantidad7 property.
     * 
     */
    public void setCantidad7(int value) {
        this.cantidad7 = value;
    }

    /**
     * Gets the value of the descripcion7 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescripcion7() {
        return descripcion7;
    }

    /**
     * Sets the value of the descripcion7 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescripcion7(String value) {
        this.descripcion7 = value;
    }

    /**
     * Gets the value of the tipoServicio8 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTipoServicio8() {
        return tipoServicio8;
    }

    /**
     * Sets the value of the tipoServicio8 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTipoServicio8(String value) {
        this.tipoServicio8 = value;
    }

    /**
     * Gets the value of the codigoCUPS8 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodigoCUPS8() {
        return codigoCUPS8;
    }

    /**
     * Sets the value of the codigoCUPS8 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodigoCUPS8(String value) {
        this.codigoCUPS8 = value;
    }

    /**
     * Gets the value of the cantidad8 property.
     * 
     */
    public int getCantidad8() {
        return cantidad8;
    }

    /**
     * Sets the value of the cantidad8 property.
     * 
     */
    public void setCantidad8(int value) {
        this.cantidad8 = value;
    }

    /**
     * Gets the value of the descripcion8 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescripcion8() {
        return descripcion8;
    }

    /**
     * Sets the value of the descripcion8 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescripcion8(String value) {
        this.descripcion8 = value;
    }

    /**
     * Gets the value of the tipoServicio9 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTipoServicio9() {
        return tipoServicio9;
    }

    /**
     * Sets the value of the tipoServicio9 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTipoServicio9(String value) {
        this.tipoServicio9 = value;
    }

    /**
     * Gets the value of the codigoCUPS9 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodigoCUPS9() {
        return codigoCUPS9;
    }

    /**
     * Sets the value of the codigoCUPS9 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodigoCUPS9(String value) {
        this.codigoCUPS9 = value;
    }

    /**
     * Gets the value of the cantidad9 property.
     * 
     */
    public int getCantidad9() {
        return cantidad9;
    }

    /**
     * Sets the value of the cantidad9 property.
     * 
     */
    public void setCantidad9(int value) {
        this.cantidad9 = value;
    }

    /**
     * Gets the value of the descripcion9 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescripcion9() {
        return descripcion9;
    }

    /**
     * Sets the value of the descripcion9 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescripcion9(String value) {
        this.descripcion9 = value;
    }

    /**
     * Gets the value of the tipoServicio10 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTipoServicio10() {
        return tipoServicio10;
    }

    /**
     * Sets the value of the tipoServicio10 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTipoServicio10(String value) {
        this.tipoServicio10 = value;
    }

    /**
     * Gets the value of the codigoCUPS10 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodigoCUPS10() {
        return codigoCUPS10;
    }

    /**
     * Sets the value of the codigoCUPS10 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodigoCUPS10(String value) {
        this.codigoCUPS10 = value;
    }

    /**
     * Gets the value of the cantidad10 property.
     * 
     */
    public int getCantidad10() {
        return cantidad10;
    }

    /**
     * Sets the value of the cantidad10 property.
     * 
     */
    public void setCantidad10(int value) {
        this.cantidad10 = value;
    }

    /**
     * Gets the value of the descripcion10 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescripcion10() {
        return descripcion10;
    }

    /**
     * Sets the value of the descripcion10 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescripcion10(String value) {
        this.descripcion10 = value;
    }

    /**
     * Gets the value of the tipoServicio11 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTipoServicio11() {
        return tipoServicio11;
    }

    /**
     * Sets the value of the tipoServicio11 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTipoServicio11(String value) {
        this.tipoServicio11 = value;
    }

    /**
     * Gets the value of the codigoCUPS11 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodigoCUPS11() {
        return codigoCUPS11;
    }

    /**
     * Sets the value of the codigoCUPS11 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodigoCUPS11(String value) {
        this.codigoCUPS11 = value;
    }

    /**
     * Gets the value of the cantidad11 property.
     * 
     */
    public int getCantidad11() {
        return cantidad11;
    }

    /**
     * Sets the value of the cantidad11 property.
     * 
     */
    public void setCantidad11(int value) {
        this.cantidad11 = value;
    }

    /**
     * Gets the value of the descripcion11 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescripcion11() {
        return descripcion11;
    }

    /**
     * Sets the value of the descripcion11 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescripcion11(String value) {
        this.descripcion11 = value;
    }

    /**
     * Gets the value of the tipoServicio12 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTipoServicio12() {
        return tipoServicio12;
    }

    /**
     * Sets the value of the tipoServicio12 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTipoServicio12(String value) {
        this.tipoServicio12 = value;
    }

    /**
     * Gets the value of the codigoCUPS12 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodigoCUPS12() {
        return codigoCUPS12;
    }

    /**
     * Sets the value of the codigoCUPS12 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodigoCUPS12(String value) {
        this.codigoCUPS12 = value;
    }

    /**
     * Gets the value of the cantidad12 property.
     * 
     */
    public int getCantidad12() {
        return cantidad12;
    }

    /**
     * Sets the value of the cantidad12 property.
     * 
     */
    public void setCantidad12(int value) {
        this.cantidad12 = value;
    }

    /**
     * Gets the value of the descripcion12 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescripcion12() {
        return descripcion12;
    }

    /**
     * Sets the value of the descripcion12 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescripcion12(String value) {
        this.descripcion12 = value;
    }

}
