package com.servinte.axioma.orm;

// Generated Apr 7, 2010 3:58:52 PM by Hibernate Tools 3.2.5.Beta

import java.util.Date;

/**
 * AdmisionesUrgencias generated by hbm2java
 */
public class AdmisionesUrgencias implements java.io.Serializable {

	private AdmisionesUrgenciasId id;
	private Medicos medicos;
	private Cuentas cuentas;
	private Camas1 camas1;
	private OriAdmisionHospi oriAdmisionHospi;
	private Usuarios usuarios;
	private Date fechaAdmision;
	private Date horaAdmision;
	private String numeroAutorizacion;
	private int causaExterna;
	private Date fechaIngresoObservacion;
	private Date horaIngresoObservacion;
	private Date fechaEgresoObservacion;
	private Date horaEgresoObservacion;
	private Long consecutivoTriage;
	private String consecutivoTriageFecha;

	public AdmisionesUrgencias() {
	}

	public AdmisionesUrgencias(AdmisionesUrgenciasId id, Cuentas cuentas,
			OriAdmisionHospi oriAdmisionHospi, Usuarios usuarios,
			Date fechaAdmision, Date horaAdmision, int causaExterna) {
		this.id = id;
		this.cuentas = cuentas;
		this.oriAdmisionHospi = oriAdmisionHospi;
		this.usuarios = usuarios;
		this.fechaAdmision = fechaAdmision;
		this.horaAdmision = horaAdmision;
		this.causaExterna = causaExterna;
	}

	public AdmisionesUrgencias(AdmisionesUrgenciasId id, Medicos medicos,
			Cuentas cuentas, Camas1 camas1, OriAdmisionHospi oriAdmisionHospi,
			Usuarios usuarios, Date fechaAdmision, Date horaAdmision,
			String numeroAutorizacion, int causaExterna,
			Date fechaIngresoObservacion, Date horaIngresoObservacion,
			Date fechaEgresoObservacion, Date horaEgresoObservacion,
			Long consecutivoTriage, String consecutivoTriageFecha) {
		this.id = id;
		this.medicos = medicos;
		this.cuentas = cuentas;
		this.camas1 = camas1;
		this.oriAdmisionHospi = oriAdmisionHospi;
		this.usuarios = usuarios;
		this.fechaAdmision = fechaAdmision;
		this.horaAdmision = horaAdmision;
		this.numeroAutorizacion = numeroAutorizacion;
		this.causaExterna = causaExterna;
		this.fechaIngresoObservacion = fechaIngresoObservacion;
		this.horaIngresoObservacion = horaIngresoObservacion;
		this.fechaEgresoObservacion = fechaEgresoObservacion;
		this.horaEgresoObservacion = horaEgresoObservacion;
		this.consecutivoTriage = consecutivoTriage;
		this.consecutivoTriageFecha = consecutivoTriageFecha;
	}

	public AdmisionesUrgenciasId getId() {
		return this.id;
	}

	public void setId(AdmisionesUrgenciasId id) {
		this.id = id;
	}

	public Medicos getMedicos() {
		return this.medicos;
	}

	public void setMedicos(Medicos medicos) {
		this.medicos = medicos;
	}

	public Cuentas getCuentas() {
		return this.cuentas;
	}

	public void setCuentas(Cuentas cuentas) {
		this.cuentas = cuentas;
	}

	public Camas1 getCamas1() {
		return this.camas1;
	}

	public void setCamas1(Camas1 camas1) {
		this.camas1 = camas1;
	}

	public OriAdmisionHospi getOriAdmisionHospi() {
		return this.oriAdmisionHospi;
	}

	public void setOriAdmisionHospi(OriAdmisionHospi oriAdmisionHospi) {
		this.oriAdmisionHospi = oriAdmisionHospi;
	}

	public Usuarios getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(Usuarios usuarios) {
		this.usuarios = usuarios;
	}

	public Date getFechaAdmision() {
		return this.fechaAdmision;
	}

	public void setFechaAdmision(Date fechaAdmision) {
		this.fechaAdmision = fechaAdmision;
	}

	public Date getHoraAdmision() {
		return this.horaAdmision;
	}

	public void setHoraAdmision(Date horaAdmision) {
		this.horaAdmision = horaAdmision;
	}

	public String getNumeroAutorizacion() {
		return this.numeroAutorizacion;
	}

	public void setNumeroAutorizacion(String numeroAutorizacion) {
		this.numeroAutorizacion = numeroAutorizacion;
	}

	public int getCausaExterna() {
		return this.causaExterna;
	}

	public void setCausaExterna(int causaExterna) {
		this.causaExterna = causaExterna;
	}

	public Date getFechaIngresoObservacion() {
		return this.fechaIngresoObservacion;
	}

	public void setFechaIngresoObservacion(Date fechaIngresoObservacion) {
		this.fechaIngresoObservacion = fechaIngresoObservacion;
	}

	public Date getHoraIngresoObservacion() {
		return this.horaIngresoObservacion;
	}

	public void setHoraIngresoObservacion(Date horaIngresoObservacion) {
		this.horaIngresoObservacion = horaIngresoObservacion;
	}

	public Date getFechaEgresoObservacion() {
		return this.fechaEgresoObservacion;
	}

	public void setFechaEgresoObservacion(Date fechaEgresoObservacion) {
		this.fechaEgresoObservacion = fechaEgresoObservacion;
	}

	public Date getHoraEgresoObservacion() {
		return this.horaEgresoObservacion;
	}

	public void setHoraEgresoObservacion(Date horaEgresoObservacion) {
		this.horaEgresoObservacion = horaEgresoObservacion;
	}

	public Long getConsecutivoTriage() {
		return this.consecutivoTriage;
	}

	public void setConsecutivoTriage(Long consecutivoTriage) {
		this.consecutivoTriage = consecutivoTriage;
	}

	public String getConsecutivoTriageFecha() {
		return this.consecutivoTriageFecha;
	}

	public void setConsecutivoTriageFecha(String consecutivoTriageFecha) {
		this.consecutivoTriageFecha = consecutivoTriageFecha;
	}

}
