package com.servinte.axioma.orm;

// Generated 21/03/2013 02:55:56 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * AnulacionSolCx generated by hbm2java
 */
public class AnulacionSolCx implements java.io.Serializable {

	private int numeroSolicitud;
	private Usuarios usuarios;
	private SolicitudesCirugia solicitudesCirugia;
	private MotivosAnulQxInst motivosAnulQxInst;
	private String comentarios;
	private Date fecha;
	private Date hora;

	public AnulacionSolCx() {
	}

	public AnulacionSolCx(Usuarios usuarios,
			SolicitudesCirugia solicitudesCirugia,
			MotivosAnulQxInst motivosAnulQxInst, Date fecha, Date hora) {
		this.usuarios = usuarios;
		this.solicitudesCirugia = solicitudesCirugia;
		this.motivosAnulQxInst = motivosAnulQxInst;
		this.fecha = fecha;
		this.hora = hora;
	}

	public AnulacionSolCx(Usuarios usuarios,
			SolicitudesCirugia solicitudesCirugia,
			MotivosAnulQxInst motivosAnulQxInst, String comentarios,
			Date fecha, Date hora) {
		this.usuarios = usuarios;
		this.solicitudesCirugia = solicitudesCirugia;
		this.motivosAnulQxInst = motivosAnulQxInst;
		this.comentarios = comentarios;
		this.fecha = fecha;
		this.hora = hora;
	}

	public int getNumeroSolicitud() {
		return this.numeroSolicitud;
	}

	public void setNumeroSolicitud(int numeroSolicitud) {
		this.numeroSolicitud = numeroSolicitud;
	}

	public Usuarios getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(Usuarios usuarios) {
		this.usuarios = usuarios;
	}

	public SolicitudesCirugia getSolicitudesCirugia() {
		return this.solicitudesCirugia;
	}

	public void setSolicitudesCirugia(SolicitudesCirugia solicitudesCirugia) {
		this.solicitudesCirugia = solicitudesCirugia;
	}

	public MotivosAnulQxInst getMotivosAnulQxInst() {
		return this.motivosAnulQxInst;
	}

	public void setMotivosAnulQxInst(MotivosAnulQxInst motivosAnulQxInst) {
		this.motivosAnulQxInst = motivosAnulQxInst;
	}

	public String getComentarios() {
		return this.comentarios;
	}

	public void setComentarios(String comentarios) {
		this.comentarios = comentarios;
	}

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	public Date getHora() {
		return this.hora;
	}

	public void setHora(Date hora) {
		this.hora = hora;
	}

}
