package com.servinte.axioma.orm;

// Generated 1/06/2011 10:54:41 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * AnulacionesSolicitud generated by hbm2java
 */
@SuppressWarnings("serial")
public class AnulacionesSolicitud implements java.io.Serializable {

	private int solicitud;
	private Medicos medicos;
	private Solicitudes solicitudes;
	private String motivo;
	private Date fecha;
	private String hora;

	public AnulacionesSolicitud() {
	}

	public AnulacionesSolicitud(Medicos medicos, Solicitudes solicitudes,
			String motivo, Date fecha, String hora) {
		this.medicos = medicos;
		this.solicitudes = solicitudes;
		this.motivo = motivo;
		this.fecha = fecha;
		this.hora = hora;
	}

	public int getSolicitud() {
		return this.solicitud;
	}

	public void setSolicitud(int solicitud) {
		this.solicitud = solicitud;
	}

	public Medicos getMedicos() {
		return this.medicos;
	}

	public void setMedicos(Medicos medicos) {
		this.medicos = medicos;
	}

	public Solicitudes getSolicitudes() {
		return this.solicitudes;
	}

	public void setSolicitudes(Solicitudes solicitudes) {
		this.solicitudes = solicitudes;
	}

	public String getMotivo() {
		return this.motivo;
	}

	public void setMotivo(String motivo) {
		this.motivo = motivo;
	}

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	public String getHora() {
		return this.hora;
	}

	public void setHora(String hora) {
		this.hora = hora;
	}

}
