package com.servinte.axioma.orm;

// Generated Apr 7, 2010 3:58:52 PM by Hibernate Tools 3.2.5.Beta

import java.math.BigDecimal;

/**
 * Arreglocomponentes123Id generated by hbm2java
 */
public class Arreglocomponentes123Id implements java.io.Serializable {

	private Integer cuenta;
	private Long plantillaIngreso;
	private BigDecimal plantillaComponente;

	public Arreglocomponentes123Id() {
	}

	public Arreglocomponentes123Id(Integer cuenta, Long plantillaIngreso,
			BigDecimal plantillaComponente) {
		this.cuenta = cuenta;
		this.plantillaIngreso = plantillaIngreso;
		this.plantillaComponente = plantillaComponente;
	}

	public Integer getCuenta() {
		return this.cuenta;
	}

	public void setCuenta(Integer cuenta) {
		this.cuenta = cuenta;
	}

	public Long getPlantillaIngreso() {
		return this.plantillaIngreso;
	}

	public void setPlantillaIngreso(Long plantillaIngreso) {
		this.plantillaIngreso = plantillaIngreso;
	}

	public BigDecimal getPlantillaComponente() {
		return this.plantillaComponente;
	}

	public void setPlantillaComponente(BigDecimal plantillaComponente) {
		this.plantillaComponente = plantillaComponente;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof Arreglocomponentes123Id))
			return false;
		Arreglocomponentes123Id castOther = (Arreglocomponentes123Id) other;

		return ((this.getCuenta() == castOther.getCuenta()) || (this
				.getCuenta() != null
				&& castOther.getCuenta() != null && this.getCuenta().equals(
				castOther.getCuenta())))
				&& ((this.getPlantillaIngreso() == castOther
						.getPlantillaIngreso()) || (this.getPlantillaIngreso() != null
						&& castOther.getPlantillaIngreso() != null && this
						.getPlantillaIngreso().equals(
								castOther.getPlantillaIngreso())))
				&& ((this.getPlantillaComponente() == castOther
						.getPlantillaComponente()) || (this
						.getPlantillaComponente() != null
						&& castOther.getPlantillaComponente() != null && this
						.getPlantillaComponente().equals(
								castOther.getPlantillaComponente())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getCuenta() == null ? 0 : this.getCuenta().hashCode());
		result = 37
				* result
				+ (getPlantillaIngreso() == null ? 0 : this
						.getPlantillaIngreso().hashCode());
		result = 37
				* result
				+ (getPlantillaComponente() == null ? 0 : this
						.getPlantillaComponente().hashCode());
		return result;
	}

}
