package com.servinte.axioma.orm;

// Generated Apr 7, 2010 3:58:52 PM by Hibernate Tools 3.2.5.Beta

/**
 * Arreglocomponentes123 generated by hbm2java
 */
public class Arreglocomponentes123 implements java.io.Serializable {

	private Arreglocomponentes123Id id;

	public Arreglocomponentes123() {
	}

	public Arreglocomponentes123(Arreglocomponentes123Id id) {
		this.id = id;
	}

	public Arreglocomponentes123Id getId() {
		return this.id;
	}

	public void setId(Arreglocomponentes123Id id) {
		this.id = id;
	}

}
