package com.servinte.axioma.orm;

// Generated 15/06/2011 05:09:59 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * CapitadoInconsistencia generated by hbm2java
 */
public class CapitadoInconsistencia implements java.io.Serializable {

	private long codigoPk;
	private InconsistenSubirPaciente inconsistenSubirPaciente;
	private String tipoIdentificacion;
	private String numeroIdentificacion;
	private String primerNombre;
	private String segundoNombre;
	private String primerApellido;
	private String segundoApellido;
	private String fechaNacimiento;
	private Integer linea;
	private String tipoInconsistencia;
	private Set inconsistenciaPersonas = new HashSet(0);

	public CapitadoInconsistencia() {
	}

	public CapitadoInconsistencia(long codigoPk) {
		this.codigoPk = codigoPk;
	}

	public CapitadoInconsistencia(long codigoPk,
			InconsistenSubirPaciente inconsistenSubirPaciente,
			String tipoIdentificacion, String numeroIdentificacion,
			String primerNombre, String segundoNombre, String primerApellido,
			String segundoApellido, String fechaNacimiento, Integer linea,
			String tipoInconsistencia, Set inconsistenciaPersonas) {
		this.codigoPk = codigoPk;
		this.inconsistenSubirPaciente = inconsistenSubirPaciente;
		this.tipoIdentificacion = tipoIdentificacion;
		this.numeroIdentificacion = numeroIdentificacion;
		this.primerNombre = primerNombre;
		this.segundoNombre = segundoNombre;
		this.primerApellido = primerApellido;
		this.segundoApellido = segundoApellido;
		this.fechaNacimiento = fechaNacimiento;
		this.linea = linea;
		this.tipoInconsistencia = tipoInconsistencia;
		this.inconsistenciaPersonas = inconsistenciaPersonas;
	}

	public long getCodigoPk() {
		return this.codigoPk;
	}

	public void setCodigoPk(long codigoPk) {
		this.codigoPk = codigoPk;
	}

	public InconsistenSubirPaciente getInconsistenSubirPaciente() {
		return this.inconsistenSubirPaciente;
	}

	public void setInconsistenSubirPaciente(
			InconsistenSubirPaciente inconsistenSubirPaciente) {
		this.inconsistenSubirPaciente = inconsistenSubirPaciente;
	}

	public String getTipoIdentificacion() {
		return this.tipoIdentificacion;
	}

	public void setTipoIdentificacion(String tipoIdentificacion) {
		this.tipoIdentificacion = tipoIdentificacion;
	}

	public String getNumeroIdentificacion() {
		return this.numeroIdentificacion;
	}

	public void setNumeroIdentificacion(String numeroIdentificacion) {
		this.numeroIdentificacion = numeroIdentificacion;
	}

	public String getPrimerNombre() {
		return this.primerNombre;
	}

	public void setPrimerNombre(String primerNombre) {
		this.primerNombre = primerNombre;
	}

	public String getSegundoNombre() {
		return this.segundoNombre;
	}

	public void setSegundoNombre(String segundoNombre) {
		this.segundoNombre = segundoNombre;
	}

	public String getPrimerApellido() {
		return this.primerApellido;
	}

	public void setPrimerApellido(String primerApellido) {
		this.primerApellido = primerApellido;
	}

	public String getSegundoApellido() {
		return this.segundoApellido;
	}

	public void setSegundoApellido(String segundoApellido) {
		this.segundoApellido = segundoApellido;
	}

	public String getFechaNacimiento() {
		return this.fechaNacimiento;
	}

	public void setFechaNacimiento(String fechaNacimiento) {
		this.fechaNacimiento = fechaNacimiento;
	}

	public Integer getLinea() {
		return this.linea;
	}

	public void setLinea(Integer linea) {
		this.linea = linea;
	}

	public String getTipoInconsistencia() {
		return this.tipoInconsistencia;
	}

	public void setTipoInconsistencia(String tipoInconsistencia) {
		this.tipoInconsistencia = tipoInconsistencia;
	}

	public Set getInconsistenciaPersonas() {
		return this.inconsistenciaPersonas;
	}

	public void setInconsistenciaPersonas(Set inconsistenciaPersonas) {
		this.inconsistenciaPersonas = inconsistenciaPersonas;
	}

}
