package com.servinte.axioma.orm;

// Generated Apr 9, 2010 9:43:36 AM by Hibernate Tools 3.2.5.Beta

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ConceptosDeEgreso generated by hbm2java
 */
public class ConceptosDeEgreso implements java.io.Serializable {

	private long codigoPk;
	private CuentasContables cuentasContables;
	private Usuarios usuarios;
	private Instituciones instituciones;
	private String codigo;
	private String descripcion;
	private char activo;
	private Date fechaModifica;
	private String horaModifica;
	private Set concEgrXusuXcatencions = new HashSet(0);

	public ConceptosDeEgreso() {
	}

	public ConceptosDeEgreso(long codigoPk, Usuarios usuarios,
			Instituciones instituciones, String codigo, String descripcion,
			char activo, Date fechaModifica, String horaModifica) {
		this.codigoPk = codigoPk;
		this.usuarios = usuarios;
		this.instituciones = instituciones;
		this.codigo = codigo;
		this.descripcion = descripcion;
		this.activo = activo;
		this.fechaModifica = fechaModifica;
		this.horaModifica = horaModifica;
	}

	public ConceptosDeEgreso(long codigoPk, CuentasContables cuentasContables,
			Usuarios usuarios, Instituciones instituciones, String codigo,
			String descripcion, char activo, Date fechaModifica,
			String horaModifica, Set concEgrXusuXcatencions) {
		this.codigoPk = codigoPk;
		this.cuentasContables = cuentasContables;
		this.usuarios = usuarios;
		this.instituciones = instituciones;
		this.codigo = codigo;
		this.descripcion = descripcion;
		this.activo = activo;
		this.fechaModifica = fechaModifica;
		this.horaModifica = horaModifica;
		this.concEgrXusuXcatencions = concEgrXusuXcatencions;
	}

	public long getCodigoPk() {
		return this.codigoPk;
	}

	public void setCodigoPk(long codigoPk) {
		this.codigoPk = codigoPk;
	}

	public CuentasContables getCuentasContables() {
		return this.cuentasContables;
	}

	public void setCuentasContables(CuentasContables cuentasContables) {
		this.cuentasContables = cuentasContables;
	}

	public Usuarios getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(Usuarios usuarios) {
		this.usuarios = usuarios;
	}

	public Instituciones getInstituciones() {
		return this.instituciones;
	}

	public void setInstituciones(Instituciones instituciones) {
		this.instituciones = instituciones;
	}

	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public char getActivo() {
		return this.activo;
	}

	public void setActivo(char activo) {
		this.activo = activo;
	}

	public Date getFechaModifica() {
		return this.fechaModifica;
	}

	public void setFechaModifica(Date fechaModifica) {
		this.fechaModifica = fechaModifica;
	}

	public String getHoraModifica() {
		return this.horaModifica;
	}

	public void setHoraModifica(String horaModifica) {
		this.horaModifica = horaModifica;
	}

	public Set getConcEgrXusuXcatencions() {
		return this.concEgrXusuXcatencions;
	}

	public void setConcEgrXusuXcatencions(Set concEgrXusuXcatencions) {
		this.concEgrXusuXcatencions = concEgrXusuXcatencions;
	}

}
