package com.servinte.axioma.orm;

// Generated Apr 7, 2010 3:58:52 PM by Hibernate Tools 3.2.5.Beta

import java.util.HashSet;
import java.util.Set;

/**
 * CondicionesServicios generated by hbm2java
 */
public class CondicionesServicios implements java.io.Serializable {

	private long consecutivo;
	private Instituciones instituciones;
	private Set servicioses = new HashSet(0);
	private Set examenConditomas = new HashSet(0);

	public CondicionesServicios() {
	}

	public CondicionesServicios(long consecutivo, Instituciones instituciones) {
		this.consecutivo = consecutivo;
		this.instituciones = instituciones;
	}

	public CondicionesServicios(long consecutivo, Instituciones instituciones,
			Set servicioses, Set examenConditomas) {
		this.consecutivo = consecutivo;
		this.instituciones = instituciones;
		this.servicioses = servicioses;
		this.examenConditomas = examenConditomas;
	}

	public long getConsecutivo() {
		return this.consecutivo;
	}

	public void setConsecutivo(long consecutivo) {
		this.consecutivo = consecutivo;
	}

	public Instituciones getInstituciones() {
		return this.instituciones;
	}

	public void setInstituciones(Instituciones instituciones) {
		this.instituciones = instituciones;
	}

	public Set getServicioses() {
		return this.servicioses;
	}

	public void setServicioses(Set servicioses) {
		this.servicioses = servicioses;
	}

	public Set getExamenConditomas() {
		return this.examenConditomas;
	}

	public void setExamenConditomas(Set examenConditomas) {
		this.examenConditomas = examenConditomas;
	}

}
