package com.servinte.axioma.orm;

// Generated Jun 21, 2010 11:07:48 AM by Hibernate Tools 3.2.4.GA

import java.math.BigDecimal;

/**
 * CuadreCaja generated by hbm2java
 */
public class CuadreCaja implements java.io.Serializable {

	private long codigoPk;
	private FormasPago formasPago;
	private MovimientosCaja movimientosCaja;
	private BigDecimal valorcaja;
	private BigDecimal valorsistema;
	private BigDecimal valordiferencia;

	public CuadreCaja() {
	}

	public CuadreCaja(long codigoPk, FormasPago formasPago,
			MovimientosCaja movimientosCaja, BigDecimal valorcaja,
			BigDecimal valorsistema, BigDecimal valordiferencia) {
		this.codigoPk = codigoPk;
		this.formasPago = formasPago;
		this.movimientosCaja = movimientosCaja;
		this.valorcaja = valorcaja;
		this.valorsistema = valorsistema;
		this.valordiferencia = valordiferencia;
	}

	public long getCodigoPk() {
		return this.codigoPk;
	}

	public void setCodigoPk(long codigoPk) {
		this.codigoPk = codigoPk;
	}

	public FormasPago getFormasPago() {
		return this.formasPago;
	}

	public void setFormasPago(FormasPago formasPago) {
		this.formasPago = formasPago;
	}

	public MovimientosCaja getMovimientosCaja() {
		return this.movimientosCaja;
	}

	public void setMovimientosCaja(MovimientosCaja movimientosCaja) {
		this.movimientosCaja = movimientosCaja;
	}

	public BigDecimal getValorcaja() {
		return this.valorcaja;
	}

	public void setValorcaja(BigDecimal valorcaja) {
		this.valorcaja = valorcaja;
	}

	public BigDecimal getValorsistema() {
		return this.valorsistema;
	}

	public void setValorsistema(BigDecimal valorsistema) {
		this.valorsistema = valorsistema;
	}

	public BigDecimal getValordiferencia() {
		return this.valordiferencia;
	}

	public void setValordiferencia(BigDecimal valordiferencia) {
		this.valordiferencia = valordiferencia;
	}

}
