package com.servinte.axioma.orm;

// Generated Apr 7, 2010 3:58:52 PM by Hibernate Tools 3.2.5.Beta

import java.util.Date;

/**
 * CuentasProcesoPresupuesto generated by hbm2java
 */
public class CuentasProcesoPresupuesto implements java.io.Serializable {

	private int cuenta;
	private Cuentas cuentas;
	private Usuarios usuarios;
	private Date fecha;
	private String hora;
	private String idSesion;
	private char esFlujoInclusiones;

	public CuentasProcesoPresupuesto() {
	}

	public CuentasProcesoPresupuesto(Cuentas cuentas, Usuarios usuarios,
			Date fecha, String hora, String idSesion, char esFlujoInclusiones) {
		this.cuentas = cuentas;
		this.usuarios = usuarios;
		this.fecha = fecha;
		this.hora = hora;
		this.idSesion = idSesion;
		this.esFlujoInclusiones = esFlujoInclusiones;
	}

	public int getCuenta() {
		return this.cuenta;
	}

	public void setCuenta(int cuenta) {
		this.cuenta = cuenta;
	}

	public Cuentas getCuentas() {
		return this.cuentas;
	}

	public void setCuentas(Cuentas cuentas) {
		this.cuentas = cuentas;
	}

	public Usuarios getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(Usuarios usuarios) {
		this.usuarios = usuarios;
	}

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	public String getHora() {
		return this.hora;
	}

	public void setHora(String hora) {
		this.hora = hora;
	}

	public String getIdSesion() {
		return this.idSesion;
	}

	public void setIdSesion(String idSesion) {
		this.idSesion = idSesion;
	}

	public char getEsFlujoInclusiones() {
		return this.esFlujoInclusiones;
	}

	public void setEsFlujoInclusiones(char esFlujoInclusiones) {
		this.esFlujoInclusiones = esFlujoInclusiones;
	}

}
