package com.servinte.axioma.orm;

// Generated Sep 9, 2010 11:32:10 AM by Hibernate Tools 3.2.4.GA

/**
 * DetAutorizacionConvIngPac generated by hbm2java
 */
public class DetAutorizacionConvIngPac implements java.io.Serializable {

	private long codigoPk;
	private AutorizacionConvIngPac autorizacionConvIngPac;
	private String tipoMedioAuto;
	private String observacionesCambio;

	public DetAutorizacionConvIngPac() {
	}

	public DetAutorizacionConvIngPac(long codigoPk,
			AutorizacionConvIngPac autorizacionConvIngPac, String tipoMedioAuto) {
		this.codigoPk = codigoPk;
		this.autorizacionConvIngPac = autorizacionConvIngPac;
		this.tipoMedioAuto = tipoMedioAuto;
	}

	public DetAutorizacionConvIngPac(long codigoPk,
			AutorizacionConvIngPac autorizacionConvIngPac,
			String tipoMedioAuto, String observacionesCambio) {
		this.codigoPk = codigoPk;
		this.autorizacionConvIngPac = autorizacionConvIngPac;
		this.tipoMedioAuto = tipoMedioAuto;
		this.observacionesCambio = observacionesCambio;
	}

	public long getCodigoPk() {
		return this.codigoPk;
	}

	public void setCodigoPk(long codigoPk) {
		this.codigoPk = codigoPk;
	}

	public AutorizacionConvIngPac getAutorizacionConvIngPac() {
		return this.autorizacionConvIngPac;
	}

	public void setAutorizacionConvIngPac(
			AutorizacionConvIngPac autorizacionConvIngPac) {
		this.autorizacionConvIngPac = autorizacionConvIngPac;
	}

	public String getTipoMedioAuto() {
		return this.tipoMedioAuto;
	}

	public void setTipoMedioAuto(String tipoMedioAuto) {
		this.tipoMedioAuto = tipoMedioAuto;
	}

	public String getObservacionesCambio() {
		return this.observacionesCambio;
	}

	public void setObservacionesCambio(String observacionesCambio) {
		this.observacionesCambio = observacionesCambio;
	}

}
