package com.servinte.axioma.orm;

// Generated Apr 7, 2010 3:58:52 PM by Hibernate Tools 3.2.5.Beta

/**
 * DetArtFormatoImpId generated by hbm2java
 */
public class DetArtFormatoImpId implements java.io.Serializable {

	private int codigoFormato;
	private String descSeccionArt;
	private Boolean detalleArticulos;
	private Integer nivel;
	private Boolean detalleNivel;
	private Boolean valoresDetalle;
	private Boolean subtotalNivel;
	private int prioridad;
	private String medicamentosArticulos;

	public DetArtFormatoImpId() {
	}

	public DetArtFormatoImpId(int codigoFormato, String descSeccionArt,
			int prioridad, String medicamentosArticulos) {
		this.codigoFormato = codigoFormato;
		this.descSeccionArt = descSeccionArt;
		this.prioridad = prioridad;
		this.medicamentosArticulos = medicamentosArticulos;
	}

	public DetArtFormatoImpId(int codigoFormato, String descSeccionArt,
			Boolean detalleArticulos, Integer nivel, Boolean detalleNivel,
			Boolean valoresDetalle, Boolean subtotalNivel, int prioridad,
			String medicamentosArticulos) {
		this.codigoFormato = codigoFormato;
		this.descSeccionArt = descSeccionArt;
		this.detalleArticulos = detalleArticulos;
		this.nivel = nivel;
		this.detalleNivel = detalleNivel;
		this.valoresDetalle = valoresDetalle;
		this.subtotalNivel = subtotalNivel;
		this.prioridad = prioridad;
		this.medicamentosArticulos = medicamentosArticulos;
	}

	public int getCodigoFormato() {
		return this.codigoFormato;
	}

	public void setCodigoFormato(int codigoFormato) {
		this.codigoFormato = codigoFormato;
	}

	public String getDescSeccionArt() {
		return this.descSeccionArt;
	}

	public void setDescSeccionArt(String descSeccionArt) {
		this.descSeccionArt = descSeccionArt;
	}

	public Boolean getDetalleArticulos() {
		return this.detalleArticulos;
	}

	public void setDetalleArticulos(Boolean detalleArticulos) {
		this.detalleArticulos = detalleArticulos;
	}

	public Integer getNivel() {
		return this.nivel;
	}

	public void setNivel(Integer nivel) {
		this.nivel = nivel;
	}

	public Boolean getDetalleNivel() {
		return this.detalleNivel;
	}

	public void setDetalleNivel(Boolean detalleNivel) {
		this.detalleNivel = detalleNivel;
	}

	public Boolean getValoresDetalle() {
		return this.valoresDetalle;
	}

	public void setValoresDetalle(Boolean valoresDetalle) {
		this.valoresDetalle = valoresDetalle;
	}

	public Boolean getSubtotalNivel() {
		return this.subtotalNivel;
	}

	public void setSubtotalNivel(Boolean subtotalNivel) {
		this.subtotalNivel = subtotalNivel;
	}

	public int getPrioridad() {
		return this.prioridad;
	}

	public void setPrioridad(int prioridad) {
		this.prioridad = prioridad;
	}

	public String getMedicamentosArticulos() {
		return this.medicamentosArticulos;
	}

	public void setMedicamentosArticulos(String medicamentosArticulos) {
		this.medicamentosArticulos = medicamentosArticulos;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DetArtFormatoImpId))
			return false;
		DetArtFormatoImpId castOther = (DetArtFormatoImpId) other;

		return (this.getCodigoFormato() == castOther.getCodigoFormato())
				&& ((this.getDescSeccionArt() == castOther.getDescSeccionArt()) || (this
						.getDescSeccionArt() != null
						&& castOther.getDescSeccionArt() != null && this
						.getDescSeccionArt().equals(
								castOther.getDescSeccionArt())))
				&& ((this.getDetalleArticulos() == castOther
						.getDetalleArticulos()) || (this.getDetalleArticulos() != null
						&& castOther.getDetalleArticulos() != null && this
						.getDetalleArticulos().equals(
								castOther.getDetalleArticulos())))
				&& ((this.getNivel() == castOther.getNivel()) || (this
						.getNivel() != null
						&& castOther.getNivel() != null && this.getNivel()
						.equals(castOther.getNivel())))
				&& ((this.getDetalleNivel() == castOther.getDetalleNivel()) || (this
						.getDetalleNivel() != null
						&& castOther.getDetalleNivel() != null && this
						.getDetalleNivel().equals(castOther.getDetalleNivel())))
				&& ((this.getValoresDetalle() == castOther.getValoresDetalle()) || (this
						.getValoresDetalle() != null
						&& castOther.getValoresDetalle() != null && this
						.getValoresDetalle().equals(
								castOther.getValoresDetalle())))
				&& ((this.getSubtotalNivel() == castOther.getSubtotalNivel()) || (this
						.getSubtotalNivel() != null
						&& castOther.getSubtotalNivel() != null && this
						.getSubtotalNivel()
						.equals(castOther.getSubtotalNivel())))
				&& (this.getPrioridad() == castOther.getPrioridad())
				&& ((this.getMedicamentosArticulos() == castOther
						.getMedicamentosArticulos()) || (this
						.getMedicamentosArticulos() != null
						&& castOther.getMedicamentosArticulos() != null && this
						.getMedicamentosArticulos().equals(
								castOther.getMedicamentosArticulos())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCodigoFormato();
		result = 37
				* result
				+ (getDescSeccionArt() == null ? 0 : this.getDescSeccionArt()
						.hashCode());
		result = 37
				* result
				+ (getDetalleArticulos() == null ? 0 : this
						.getDetalleArticulos().hashCode());
		result = 37 * result
				+ (getNivel() == null ? 0 : this.getNivel().hashCode());
		result = 37
				* result
				+ (getDetalleNivel() == null ? 0 : this.getDetalleNivel()
						.hashCode());
		result = 37
				* result
				+ (getValoresDetalle() == null ? 0 : this.getValoresDetalle()
						.hashCode());
		result = 37
				* result
				+ (getSubtotalNivel() == null ? 0 : this.getSubtotalNivel()
						.hashCode());
		result = 37 * result + this.getPrioridad();
		result = 37
				* result
				+ (getMedicamentosArticulos() == null ? 0 : this
						.getMedicamentosArticulos().hashCode());
		return result;
	}

}
