package com.servinte.axioma.orm;

// Generated Jun 21, 2010 11:07:48 AM by Hibernate Tools 3.2.4.GA

/**
 * DetExclusionesSuperficies generated by hbm2java
 */
public class DetExclusionesSuperficies implements java.io.Serializable {

	private long codigoPk;
	private DetPlanTratamiento detPlanTratamiento;
	private ExclusionesPresupuesto exclusionesPresupuesto;

	public DetExclusionesSuperficies() {
	}

	public DetExclusionesSuperficies(long codigoPk,
			DetPlanTratamiento detPlanTratamiento,
			ExclusionesPresupuesto exclusionesPresupuesto) {
		this.codigoPk = codigoPk;
		this.detPlanTratamiento = detPlanTratamiento;
		this.exclusionesPresupuesto = exclusionesPresupuesto;
	}

	public long getCodigoPk() {
		return this.codigoPk;
	}

	public void setCodigoPk(long codigoPk) {
		this.codigoPk = codigoPk;
	}

	public DetPlanTratamiento getDetPlanTratamiento() {
		return this.detPlanTratamiento;
	}

	public void setDetPlanTratamiento(DetPlanTratamiento detPlanTratamiento) {
		this.detPlanTratamiento = detPlanTratamiento;
	}

	public ExclusionesPresupuesto getExclusionesPresupuesto() {
		return this.exclusionesPresupuesto;
	}

	public void setExclusionesPresupuesto(
			ExclusionesPresupuesto exclusionesPresupuesto) {
		this.exclusionesPresupuesto = exclusionesPresupuesto;
	}

}
