package com.servinte.axioma.orm;

// Generated Apr 7, 2010 3:58:52 PM by Hibernate Tools 3.2.5.Beta

/**
 * DetServFormatoImpId generated by hbm2java
 */
public class DetServFormatoImpId implements java.io.Serializable {

	private int codigoFormato;
	private Boolean detalle;
	private Boolean valoresDetalle;
	private Boolean subtotalGrupo;
	private int prioridad;
	private int grupo;

	public DetServFormatoImpId() {
	}

	public DetServFormatoImpId(int codigoFormato, int prioridad, int grupo) {
		this.codigoFormato = codigoFormato;
		this.prioridad = prioridad;
		this.grupo = grupo;
	}

	public DetServFormatoImpId(int codigoFormato, Boolean detalle,
			Boolean valoresDetalle, Boolean subtotalGrupo, int prioridad,
			int grupo) {
		this.codigoFormato = codigoFormato;
		this.detalle = detalle;
		this.valoresDetalle = valoresDetalle;
		this.subtotalGrupo = subtotalGrupo;
		this.prioridad = prioridad;
		this.grupo = grupo;
	}

	public int getCodigoFormato() {
		return this.codigoFormato;
	}

	public void setCodigoFormato(int codigoFormato) {
		this.codigoFormato = codigoFormato;
	}

	public Boolean getDetalle() {
		return this.detalle;
	}

	public void setDetalle(Boolean detalle) {
		this.detalle = detalle;
	}

	public Boolean getValoresDetalle() {
		return this.valoresDetalle;
	}

	public void setValoresDetalle(Boolean valoresDetalle) {
		this.valoresDetalle = valoresDetalle;
	}

	public Boolean getSubtotalGrupo() {
		return this.subtotalGrupo;
	}

	public void setSubtotalGrupo(Boolean subtotalGrupo) {
		this.subtotalGrupo = subtotalGrupo;
	}

	public int getPrioridad() {
		return this.prioridad;
	}

	public void setPrioridad(int prioridad) {
		this.prioridad = prioridad;
	}

	public int getGrupo() {
		return this.grupo;
	}

	public void setGrupo(int grupo) {
		this.grupo = grupo;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DetServFormatoImpId))
			return false;
		DetServFormatoImpId castOther = (DetServFormatoImpId) other;

		return (this.getCodigoFormato() == castOther.getCodigoFormato())
				&& ((this.getDetalle() == castOther.getDetalle()) || (this
						.getDetalle() != null
						&& castOther.getDetalle() != null && this.getDetalle()
						.equals(castOther.getDetalle())))
				&& ((this.getValoresDetalle() == castOther.getValoresDetalle()) || (this
						.getValoresDetalle() != null
						&& castOther.getValoresDetalle() != null && this
						.getValoresDetalle().equals(
								castOther.getValoresDetalle())))
				&& ((this.getSubtotalGrupo() == castOther.getSubtotalGrupo()) || (this
						.getSubtotalGrupo() != null
						&& castOther.getSubtotalGrupo() != null && this
						.getSubtotalGrupo()
						.equals(castOther.getSubtotalGrupo())))
				&& (this.getPrioridad() == castOther.getPrioridad())
				&& (this.getGrupo() == castOther.getGrupo());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCodigoFormato();
		result = 37 * result
				+ (getDetalle() == null ? 0 : this.getDetalle().hashCode());
		result = 37
				* result
				+ (getValoresDetalle() == null ? 0 : this.getValoresDetalle()
						.hashCode());
		result = 37
				* result
				+ (getSubtotalGrupo() == null ? 0 : this.getSubtotalGrupo()
						.hashCode());
		result = 37 * result + this.getPrioridad();
		result = 37 * result + this.getGrupo();
		return result;
	}

}
