package com.servinte.axioma.orm;

// Generated Apr 7, 2010 3:58:52 PM by Hibernate Tools 3.2.5.Beta

/**
 * DetServFormatoImp generated by hbm2java
 */
public class DetServFormatoImp implements java.io.Serializable {

	private DetServFormatoImpId id;
	private FormatoImpPresupuesto formatoImpPresupuesto;
	private GruposServicios gruposServicios;

	public DetServFormatoImp() {
	}

	public DetServFormatoImp(DetServFormatoImpId id,
			FormatoImpPresupuesto formatoImpPresupuesto,
			GruposServicios gruposServicios) {
		this.id = id;
		this.formatoImpPresupuesto = formatoImpPresupuesto;
		this.gruposServicios = gruposServicios;
	}

	public DetServFormatoImpId getId() {
		return this.id;
	}

	public void setId(DetServFormatoImpId id) {
		this.id = id;
	}

	public FormatoImpPresupuesto getFormatoImpPresupuesto() {
		return this.formatoImpPresupuesto;
	}

	public void setFormatoImpPresupuesto(
			FormatoImpPresupuesto formatoImpPresupuesto) {
		this.formatoImpPresupuesto = formatoImpPresupuesto;
	}

	public GruposServicios getGruposServicios() {
		return this.gruposServicios;
	}

	public void setGruposServicios(GruposServicios gruposServicios) {
		this.gruposServicios = gruposServicios;
	}

}
