package com.servinte.axioma.orm;

// Generated Sep 8, 2010 1:46:00 PM by Hibernate Tools 3.2.4.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * EncaEmiTarjetaCliente generated by hbm2java
 */
public class EncaEmiTarjetaCliente implements java.io.Serializable {

	private long codigo;
	private Usuarios usuarios;
	private TiposTarjCliente tiposTarjCliente;
	private Instituciones instituciones;
	private long serialInicial;
	private long serialFinal;
	private Date fechaModifica;
	private String horaModifica;
	private Long cantidad;
	private Set detEmiTarjetaClientes = new HashSet(0);

	public EncaEmiTarjetaCliente() {
	}

	public EncaEmiTarjetaCliente(long codigo, Usuarios usuarios,
			TiposTarjCliente tiposTarjCliente, Instituciones instituciones,
			long serialInicial, long serialFinal, Date fechaModifica,
			String horaModifica) {
		this.codigo = codigo;
		this.usuarios = usuarios;
		this.tiposTarjCliente = tiposTarjCliente;
		this.instituciones = instituciones;
		this.serialInicial = serialInicial;
		this.serialFinal = serialFinal;
		this.fechaModifica = fechaModifica;
		this.horaModifica = horaModifica;
	}

	public EncaEmiTarjetaCliente(long codigo, Usuarios usuarios,
			TiposTarjCliente tiposTarjCliente, Instituciones instituciones,
			long serialInicial, long serialFinal, Date fechaModifica,
			String horaModifica, Long cantidad, Set detEmiTarjetaClientes) {
		this.codigo = codigo;
		this.usuarios = usuarios;
		this.tiposTarjCliente = tiposTarjCliente;
		this.instituciones = instituciones;
		this.serialInicial = serialInicial;
		this.serialFinal = serialFinal;
		this.fechaModifica = fechaModifica;
		this.horaModifica = horaModifica;
		this.cantidad = cantidad;
		this.detEmiTarjetaClientes = detEmiTarjetaClientes;
	}

	public long getCodigo() {
		return this.codigo;
	}

	public void setCodigo(long codigo) {
		this.codigo = codigo;
	}

	public Usuarios getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(Usuarios usuarios) {
		this.usuarios = usuarios;
	}

	public TiposTarjCliente getTiposTarjCliente() {
		return this.tiposTarjCliente;
	}

	public void setTiposTarjCliente(TiposTarjCliente tiposTarjCliente) {
		this.tiposTarjCliente = tiposTarjCliente;
	}

	public Instituciones getInstituciones() {
		return this.instituciones;
	}

	public void setInstituciones(Instituciones instituciones) {
		this.instituciones = instituciones;
	}

	public long getSerialInicial() {
		return this.serialInicial;
	}

	public void setSerialInicial(long serialInicial) {
		this.serialInicial = serialInicial;
	}

	public long getSerialFinal() {
		return this.serialFinal;
	}

	public void setSerialFinal(long serialFinal) {
		this.serialFinal = serialFinal;
	}

	public Date getFechaModifica() {
		return this.fechaModifica;
	}

	public void setFechaModifica(Date fechaModifica) {
		this.fechaModifica = fechaModifica;
	}

	public String getHoraModifica() {
		return this.horaModifica;
	}

	public void setHoraModifica(String horaModifica) {
		this.horaModifica = horaModifica;
	}

	public Long getCantidad() {
		return this.cantidad;
	}

	public void setCantidad(Long cantidad) {
		this.cantidad = cantidad;
	}

	public Set getDetEmiTarjetaClientes() {
		return this.detEmiTarjetaClientes;
	}

	public void setDetEmiTarjetaClientes(Set detEmiTarjetaClientes) {
		this.detEmiTarjetaClientes = detEmiTarjetaClientes;
	}

}
