package com.servinte.axioma.orm;

// Generated 26/08/2011 02:58:10 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * EntregaCajaMayor generated by hbm2java
 */
public class EntregaCajaMayor implements java.io.Serializable {

	private long movimientoCaja;
	private Cajas cajas;
	private MovimientosCaja movimientosCajaByMovimientoCajaArqueo;
	private MovimientosCaja movimientosCajaByCodigoPk;
	private String estado;
	private TrasladoCajaPrincipalMayor trasladoCajaPrincipalMayor;
	private Set cierreCajaXEntregaCajas = new HashSet(0);

	public EntregaCajaMayor() {
	}

	public EntregaCajaMayor(Cajas cajas,
			MovimientosCaja movimientosCajaByMovimientoCajaArqueo,
			MovimientosCaja movimientosCajaByCodigoPk, String estado) {
		this.cajas = cajas;
		this.movimientosCajaByMovimientoCajaArqueo = movimientosCajaByMovimientoCajaArqueo;
		this.movimientosCajaByCodigoPk = movimientosCajaByCodigoPk;
		this.estado = estado;
	}

	public EntregaCajaMayor(Cajas cajas,
			MovimientosCaja movimientosCajaByMovimientoCajaArqueo,
			MovimientosCaja movimientosCajaByCodigoPk, String estado,
			TrasladoCajaPrincipalMayor trasladoCajaPrincipalMayor,
			Set cierreCajaXEntregaCajas) {
		this.cajas = cajas;
		this.movimientosCajaByMovimientoCajaArqueo = movimientosCajaByMovimientoCajaArqueo;
		this.movimientosCajaByCodigoPk = movimientosCajaByCodigoPk;
		this.estado = estado;
		this.trasladoCajaPrincipalMayor = trasladoCajaPrincipalMayor;
		this.cierreCajaXEntregaCajas = cierreCajaXEntregaCajas;
	}

	public long getMovimientoCaja() {
		return this.movimientoCaja;
	}

	public void setMovimientoCaja(long movimientoCaja) {
		this.movimientoCaja = movimientoCaja;
	}

	public Cajas getCajas() {
		return this.cajas;
	}

	public void setCajas(Cajas cajas) {
		this.cajas = cajas;
	}

	public MovimientosCaja getMovimientosCajaByMovimientoCajaArqueo() {
		return this.movimientosCajaByMovimientoCajaArqueo;
	}

	public void setMovimientosCajaByMovimientoCajaArqueo(
			MovimientosCaja movimientosCajaByMovimientoCajaArqueo) {
		this.movimientosCajaByMovimientoCajaArqueo = movimientosCajaByMovimientoCajaArqueo;
	}

	public MovimientosCaja getMovimientosCajaByCodigoPk() {
		return this.movimientosCajaByCodigoPk;
	}

	public void setMovimientosCajaByCodigoPk(
			MovimientosCaja movimientosCajaByCodigoPk) {
		this.movimientosCajaByCodigoPk = movimientosCajaByCodigoPk;
	}

	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	public TrasladoCajaPrincipalMayor getTrasladoCajaPrincipalMayor() {
		return this.trasladoCajaPrincipalMayor;
	}

	public void setTrasladoCajaPrincipalMayor(
			TrasladoCajaPrincipalMayor trasladoCajaPrincipalMayor) {
		this.trasladoCajaPrincipalMayor = trasladoCajaPrincipalMayor;
	}

	public Set getCierreCajaXEntregaCajas() {
		return this.cierreCajaXEntregaCajas;
	}

	public void setCierreCajaXEntregaCajas(Set cierreCajaXEntregaCajas) {
		this.cierreCajaXEntregaCajas = cierreCajaXEntregaCajas;
	}

}
