package com.servinte.axioma.orm;

// Generated 21/07/2011 03:06:42 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Especialidades generated by hbm2java
 */
public class Especialidades implements java.io.Serializable {

	private int codigo;
	private Usuarios usuarios;
	private CentrosCosto centrosCosto;
	private Instituciones instituciones;
	private String nombre;
	private String consecutivo;
	private Date fechaGrabacion;
	private String horaGrabacion;
	private String tipoEspecialidad;
	private Set especiServCueIngs = new HashSet(0);
	private Set presupuestoOdontologicos = new HashSet(0);
	private Set unidadesConsultas = new HashSet(0);
	private Set especialidadesMedicoses = new HashSet(0);
	private Set paquetizacionDetFacturas = new HashSet(0);
	private Set histoMontoAgrupServs = new HashSet(0);
	private Set planTratamientos = new HashSet(0);
	private Set logDetPlanTratamientos = new HashSet(0);
	private Set paqAgrupacionServicioses = new HashSet(0);
	private Set hisConfPlanTratamientos = new HashSet(0);
	private Set logPlanTratamientos = new HashSet(0);
	private Set agruSerExceTariConts = new HashSet(0);
	private Set excepcionesTarifases = new HashSet(0);
	private Set hisConfDetPlanTs = new HashSet(0);
	private Set funSecParametrizadases = new HashSet(0);
	private Set solCirugiaPorServicios = new HashSet(0);
	private Set detServHonoraEspServs = new HashSet(0);
	private Set detPlanTratamientos = new HashSet(0);
	private Set agruSerIncluexcluEconts = new HashSet(0);
	private Set cuentases = new HashSet(0);
	private Set logPresupuestoOdontos = new HashSet(0);
	private Set cobAgrupServicioses = new HashSet(0);
	private Set solicitudesesForEspecialidadSolicitante = new HashSet(0);
	private Set logProgramases = new HashSet(0);
	private Set cuentasXEspOdontos = new HashSet(0);
	private Set solicitudesesForEspecialidadSolicitada = new HashSet(0);
	private Set programasServiciosPlanTs = new HashSet(0);
	private Set exCoberAgruSerEntSubs = new HashSet(0);
	private Set recargosTarifases = new HashSet(0);
	private Set evolucioneses = new HashSet(0);
	private Set hisConfProgServPlanTs = new HashSet(0);
	private Set agruSerIncluexcluCcs = new HashSet(0);
	private Set ordenesAmbulatoriases = new HashSet(0);
	private Set servicioses = new HashSet(0);
	private Set detAgruHonoraEspServs = new HashSet(0);
	private Set cuotasOdontEspecialidads = new HashSet(0);
	private Set logPresupuestoOdos = new HashSet(0);
	private Set logProgramasServiciosPlanTs = new HashSet(0);
	private Set presupuestoCuotasEsps = new HashSet(0);
	private Set montoAgrupacionServicioses = new HashSet(0);
	private Set clasOdoSecEspes = new HashSet(0);
	private Set nivelAutorAgrServs = new HashSet(0);
	private Set indCalidadEspecialidads = new HashSet(0);
	private Set asociosDetFacturas = new HashSet(0);
	private Set paquetesOdontologicoses = new HashSet(0);
	private Set programases = new HashSet(0);
	private Set agruSerDescComConvxconts = new HashSet(0);
	private Set agruSerExepCobConvxconts = new HashSet(0);

	public Especialidades() {
	}

	public Especialidades(int codigo, Usuarios usuarios,
			Instituciones instituciones, String nombre, String consecutivo,
			Date fechaGrabacion, String horaGrabacion, String tipoEspecialidad) {
		this.codigo = codigo;
		this.usuarios = usuarios;
		this.instituciones = instituciones;
		this.nombre = nombre;
		this.consecutivo = consecutivo;
		this.fechaGrabacion = fechaGrabacion;
		this.horaGrabacion = horaGrabacion;
		this.tipoEspecialidad = tipoEspecialidad;
	}

	public Especialidades(int codigo, Usuarios usuarios,
			CentrosCosto centrosCosto, Instituciones instituciones,
			String nombre, String consecutivo, Date fechaGrabacion,
			String horaGrabacion, String tipoEspecialidad,
			Set especiServCueIngs, Set presupuestoOdontologicos,
			Set unidadesConsultas, Set especialidadesMedicoses,
			Set paquetizacionDetFacturas, Set histoMontoAgrupServs,
			Set planTratamientos, Set logDetPlanTratamientos,
			Set paqAgrupacionServicioses, Set hisConfPlanTratamientos,
			Set logPlanTratamientos, Set agruSerExceTariConts,
			Set excepcionesTarifases, Set hisConfDetPlanTs,
			Set funSecParametrizadases, Set solCirugiaPorServicios,
			Set detServHonoraEspServs, Set detPlanTratamientos,
			Set agruSerIncluexcluEconts, Set cuentases,
			Set logPresupuestoOdontos, Set cobAgrupServicioses,
			Set solicitudesesForEspecialidadSolicitante, Set logProgramases,
			Set cuentasXEspOdontos, Set solicitudesesForEspecialidadSolicitada,
			Set programasServiciosPlanTs, Set exCoberAgruSerEntSubs,
			Set recargosTarifases, Set evolucioneses,
			Set hisConfProgServPlanTs, Set agruSerIncluexcluCcs,
			Set ordenesAmbulatoriases, Set servicioses,
			Set detAgruHonoraEspServs, Set cuotasOdontEspecialidads,
			Set logPresupuestoOdos, Set logProgramasServiciosPlanTs,
			Set presupuestoCuotasEsps, Set montoAgrupacionServicioses,
			Set clasOdoSecEspes, Set nivelAutorAgrServs,
			Set indCalidadEspecialidads, Set asociosDetFacturas,
			Set paquetesOdontologicoses, Set programases,
			Set agruSerDescComConvxconts, Set agruSerExepCobConvxconts) {
		this.codigo = codigo;
		this.usuarios = usuarios;
		this.centrosCosto = centrosCosto;
		this.instituciones = instituciones;
		this.nombre = nombre;
		this.consecutivo = consecutivo;
		this.fechaGrabacion = fechaGrabacion;
		this.horaGrabacion = horaGrabacion;
		this.tipoEspecialidad = tipoEspecialidad;
		this.especiServCueIngs = especiServCueIngs;
		this.presupuestoOdontologicos = presupuestoOdontologicos;
		this.unidadesConsultas = unidadesConsultas;
		this.especialidadesMedicoses = especialidadesMedicoses;
		this.paquetizacionDetFacturas = paquetizacionDetFacturas;
		this.histoMontoAgrupServs = histoMontoAgrupServs;
		this.planTratamientos = planTratamientos;
		this.logDetPlanTratamientos = logDetPlanTratamientos;
		this.paqAgrupacionServicioses = paqAgrupacionServicioses;
		this.hisConfPlanTratamientos = hisConfPlanTratamientos;
		this.logPlanTratamientos = logPlanTratamientos;
		this.agruSerExceTariConts = agruSerExceTariConts;
		this.excepcionesTarifases = excepcionesTarifases;
		this.hisConfDetPlanTs = hisConfDetPlanTs;
		this.funSecParametrizadases = funSecParametrizadases;
		this.solCirugiaPorServicios = solCirugiaPorServicios;
		this.detServHonoraEspServs = detServHonoraEspServs;
		this.detPlanTratamientos = detPlanTratamientos;
		this.agruSerIncluexcluEconts = agruSerIncluexcluEconts;
		this.cuentases = cuentases;
		this.logPresupuestoOdontos = logPresupuestoOdontos;
		this.cobAgrupServicioses = cobAgrupServicioses;
		this.solicitudesesForEspecialidadSolicitante = solicitudesesForEspecialidadSolicitante;
		this.logProgramases = logProgramases;
		this.cuentasXEspOdontos = cuentasXEspOdontos;
		this.solicitudesesForEspecialidadSolicitada = solicitudesesForEspecialidadSolicitada;
		this.programasServiciosPlanTs = programasServiciosPlanTs;
		this.exCoberAgruSerEntSubs = exCoberAgruSerEntSubs;
		this.recargosTarifases = recargosTarifases;
		this.evolucioneses = evolucioneses;
		this.hisConfProgServPlanTs = hisConfProgServPlanTs;
		this.agruSerIncluexcluCcs = agruSerIncluexcluCcs;
		this.ordenesAmbulatoriases = ordenesAmbulatoriases;
		this.servicioses = servicioses;
		this.detAgruHonoraEspServs = detAgruHonoraEspServs;
		this.cuotasOdontEspecialidads = cuotasOdontEspecialidads;
		this.logPresupuestoOdos = logPresupuestoOdos;
		this.logProgramasServiciosPlanTs = logProgramasServiciosPlanTs;
		this.presupuestoCuotasEsps = presupuestoCuotasEsps;
		this.montoAgrupacionServicioses = montoAgrupacionServicioses;
		this.clasOdoSecEspes = clasOdoSecEspes;
		this.nivelAutorAgrServs = nivelAutorAgrServs;
		this.indCalidadEspecialidads = indCalidadEspecialidads;
		this.asociosDetFacturas = asociosDetFacturas;
		this.paquetesOdontologicoses = paquetesOdontologicoses;
		this.programases = programases;
		this.agruSerDescComConvxconts = agruSerDescComConvxconts;
		this.agruSerExepCobConvxconts = agruSerExepCobConvxconts;
	}

	public int getCodigo() {
		return this.codigo;
	}

	public void setCodigo(int codigo) {
		this.codigo = codigo;
	}

	public Usuarios getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(Usuarios usuarios) {
		this.usuarios = usuarios;
	}

	public CentrosCosto getCentrosCosto() {
		return this.centrosCosto;
	}

	public void setCentrosCosto(CentrosCosto centrosCosto) {
		this.centrosCosto = centrosCosto;
	}

	public Instituciones getInstituciones() {
		return this.instituciones;
	}

	public void setInstituciones(Instituciones instituciones) {
		this.instituciones = instituciones;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getConsecutivo() {
		return this.consecutivo;
	}

	public void setConsecutivo(String consecutivo) {
		this.consecutivo = consecutivo;
	}

	public Date getFechaGrabacion() {
		return this.fechaGrabacion;
	}

	public void setFechaGrabacion(Date fechaGrabacion) {
		this.fechaGrabacion = fechaGrabacion;
	}

	public String getHoraGrabacion() {
		return this.horaGrabacion;
	}

	public void setHoraGrabacion(String horaGrabacion) {
		this.horaGrabacion = horaGrabacion;
	}

	public String getTipoEspecialidad() {
		return this.tipoEspecialidad;
	}

	public void setTipoEspecialidad(String tipoEspecialidad) {
		this.tipoEspecialidad = tipoEspecialidad;
	}

	public Set getEspeciServCueIngs() {
		return this.especiServCueIngs;
	}

	public void setEspeciServCueIngs(Set especiServCueIngs) {
		this.especiServCueIngs = especiServCueIngs;
	}

	public Set getPresupuestoOdontologicos() {
		return this.presupuestoOdontologicos;
	}

	public void setPresupuestoOdontologicos(Set presupuestoOdontologicos) {
		this.presupuestoOdontologicos = presupuestoOdontologicos;
	}

	public Set getUnidadesConsultas() {
		return this.unidadesConsultas;
	}

	public void setUnidadesConsultas(Set unidadesConsultas) {
		this.unidadesConsultas = unidadesConsultas;
	}

	public Set getEspecialidadesMedicoses() {
		return this.especialidadesMedicoses;
	}

	public void setEspecialidadesMedicoses(Set especialidadesMedicoses) {
		this.especialidadesMedicoses = especialidadesMedicoses;
	}

	public Set getPaquetizacionDetFacturas() {
		return this.paquetizacionDetFacturas;
	}

	public void setPaquetizacionDetFacturas(Set paquetizacionDetFacturas) {
		this.paquetizacionDetFacturas = paquetizacionDetFacturas;
	}

	public Set getHistoMontoAgrupServs() {
		return this.histoMontoAgrupServs;
	}

	public void setHistoMontoAgrupServs(Set histoMontoAgrupServs) {
		this.histoMontoAgrupServs = histoMontoAgrupServs;
	}

	public Set getPlanTratamientos() {
		return this.planTratamientos;
	}

	public void setPlanTratamientos(Set planTratamientos) {
		this.planTratamientos = planTratamientos;
	}

	public Set getLogDetPlanTratamientos() {
		return this.logDetPlanTratamientos;
	}

	public void setLogDetPlanTratamientos(Set logDetPlanTratamientos) {
		this.logDetPlanTratamientos = logDetPlanTratamientos;
	}

	public Set getPaqAgrupacionServicioses() {
		return this.paqAgrupacionServicioses;
	}

	public void setPaqAgrupacionServicioses(Set paqAgrupacionServicioses) {
		this.paqAgrupacionServicioses = paqAgrupacionServicioses;
	}

	public Set getHisConfPlanTratamientos() {
		return this.hisConfPlanTratamientos;
	}

	public void setHisConfPlanTratamientos(Set hisConfPlanTratamientos) {
		this.hisConfPlanTratamientos = hisConfPlanTratamientos;
	}

	public Set getLogPlanTratamientos() {
		return this.logPlanTratamientos;
	}

	public void setLogPlanTratamientos(Set logPlanTratamientos) {
		this.logPlanTratamientos = logPlanTratamientos;
	}

	public Set getAgruSerExceTariConts() {
		return this.agruSerExceTariConts;
	}

	public void setAgruSerExceTariConts(Set agruSerExceTariConts) {
		this.agruSerExceTariConts = agruSerExceTariConts;
	}

	public Set getExcepcionesTarifases() {
		return this.excepcionesTarifases;
	}

	public void setExcepcionesTarifases(Set excepcionesTarifases) {
		this.excepcionesTarifases = excepcionesTarifases;
	}

	public Set getHisConfDetPlanTs() {
		return this.hisConfDetPlanTs;
	}

	public void setHisConfDetPlanTs(Set hisConfDetPlanTs) {
		this.hisConfDetPlanTs = hisConfDetPlanTs;
	}

	public Set getFunSecParametrizadases() {
		return this.funSecParametrizadases;
	}

	public void setFunSecParametrizadases(Set funSecParametrizadases) {
		this.funSecParametrizadases = funSecParametrizadases;
	}

	public Set getSolCirugiaPorServicios() {
		return this.solCirugiaPorServicios;
	}

	public void setSolCirugiaPorServicios(Set solCirugiaPorServicios) {
		this.solCirugiaPorServicios = solCirugiaPorServicios;
	}

	public Set getDetServHonoraEspServs() {
		return this.detServHonoraEspServs;
	}

	public void setDetServHonoraEspServs(Set detServHonoraEspServs) {
		this.detServHonoraEspServs = detServHonoraEspServs;
	}

	public Set getDetPlanTratamientos() {
		return this.detPlanTratamientos;
	}

	public void setDetPlanTratamientos(Set detPlanTratamientos) {
		this.detPlanTratamientos = detPlanTratamientos;
	}

	public Set getAgruSerIncluexcluEconts() {
		return this.agruSerIncluexcluEconts;
	}

	public void setAgruSerIncluexcluEconts(Set agruSerIncluexcluEconts) {
		this.agruSerIncluexcluEconts = agruSerIncluexcluEconts;
	}

	public Set getCuentases() {
		return this.cuentases;
	}

	public void setCuentases(Set cuentases) {
		this.cuentases = cuentases;
	}

	public Set getLogPresupuestoOdontos() {
		return this.logPresupuestoOdontos;
	}

	public void setLogPresupuestoOdontos(Set logPresupuestoOdontos) {
		this.logPresupuestoOdontos = logPresupuestoOdontos;
	}

	public Set getCobAgrupServicioses() {
		return this.cobAgrupServicioses;
	}

	public void setCobAgrupServicioses(Set cobAgrupServicioses) {
		this.cobAgrupServicioses = cobAgrupServicioses;
	}

	public Set getSolicitudesesForEspecialidadSolicitante() {
		return this.solicitudesesForEspecialidadSolicitante;
	}

	public void setSolicitudesesForEspecialidadSolicitante(
			Set solicitudesesForEspecialidadSolicitante) {
		this.solicitudesesForEspecialidadSolicitante = solicitudesesForEspecialidadSolicitante;
	}

	public Set getLogProgramases() {
		return this.logProgramases;
	}

	public void setLogProgramases(Set logProgramases) {
		this.logProgramases = logProgramases;
	}

	public Set getCuentasXEspOdontos() {
		return this.cuentasXEspOdontos;
	}

	public void setCuentasXEspOdontos(Set cuentasXEspOdontos) {
		this.cuentasXEspOdontos = cuentasXEspOdontos;
	}

	public Set getSolicitudesesForEspecialidadSolicitada() {
		return this.solicitudesesForEspecialidadSolicitada;
	}

	public void setSolicitudesesForEspecialidadSolicitada(
			Set solicitudesesForEspecialidadSolicitada) {
		this.solicitudesesForEspecialidadSolicitada = solicitudesesForEspecialidadSolicitada;
	}

	public Set getProgramasServiciosPlanTs() {
		return this.programasServiciosPlanTs;
	}

	public void setProgramasServiciosPlanTs(Set programasServiciosPlanTs) {
		this.programasServiciosPlanTs = programasServiciosPlanTs;
	}

	public Set getExCoberAgruSerEntSubs() {
		return this.exCoberAgruSerEntSubs;
	}

	public void setExCoberAgruSerEntSubs(Set exCoberAgruSerEntSubs) {
		this.exCoberAgruSerEntSubs = exCoberAgruSerEntSubs;
	}

	public Set getRecargosTarifases() {
		return this.recargosTarifases;
	}

	public void setRecargosTarifases(Set recargosTarifases) {
		this.recargosTarifases = recargosTarifases;
	}

	public Set getEvolucioneses() {
		return this.evolucioneses;
	}

	public void setEvolucioneses(Set evolucioneses) {
		this.evolucioneses = evolucioneses;
	}

	public Set getHisConfProgServPlanTs() {
		return this.hisConfProgServPlanTs;
	}

	public void setHisConfProgServPlanTs(Set hisConfProgServPlanTs) {
		this.hisConfProgServPlanTs = hisConfProgServPlanTs;
	}

	public Set getAgruSerIncluexcluCcs() {
		return this.agruSerIncluexcluCcs;
	}

	public void setAgruSerIncluexcluCcs(Set agruSerIncluexcluCcs) {
		this.agruSerIncluexcluCcs = agruSerIncluexcluCcs;
	}

	public Set getOrdenesAmbulatoriases() {
		return this.ordenesAmbulatoriases;
	}

	public void setOrdenesAmbulatoriases(Set ordenesAmbulatoriases) {
		this.ordenesAmbulatoriases = ordenesAmbulatoriases;
	}

	public Set getServicioses() {
		return this.servicioses;
	}

	public void setServicioses(Set servicioses) {
		this.servicioses = servicioses;
	}

	public Set getDetAgruHonoraEspServs() {
		return this.detAgruHonoraEspServs;
	}

	public void setDetAgruHonoraEspServs(Set detAgruHonoraEspServs) {
		this.detAgruHonoraEspServs = detAgruHonoraEspServs;
	}

	public Set getCuotasOdontEspecialidads() {
		return this.cuotasOdontEspecialidads;
	}

	public void setCuotasOdontEspecialidads(Set cuotasOdontEspecialidads) {
		this.cuotasOdontEspecialidads = cuotasOdontEspecialidads;
	}

	public Set getLogPresupuestoOdos() {
		return this.logPresupuestoOdos;
	}

	public void setLogPresupuestoOdos(Set logPresupuestoOdos) {
		this.logPresupuestoOdos = logPresupuestoOdos;
	}

	public Set getLogProgramasServiciosPlanTs() {
		return this.logProgramasServiciosPlanTs;
	}

	public void setLogProgramasServiciosPlanTs(Set logProgramasServiciosPlanTs) {
		this.logProgramasServiciosPlanTs = logProgramasServiciosPlanTs;
	}

	public Set getPresupuestoCuotasEsps() {
		return this.presupuestoCuotasEsps;
	}

	public void setPresupuestoCuotasEsps(Set presupuestoCuotasEsps) {
		this.presupuestoCuotasEsps = presupuestoCuotasEsps;
	}

	public Set getMontoAgrupacionServicioses() {
		return this.montoAgrupacionServicioses;
	}

	public void setMontoAgrupacionServicioses(Set montoAgrupacionServicioses) {
		this.montoAgrupacionServicioses = montoAgrupacionServicioses;
	}

	public Set getClasOdoSecEspes() {
		return this.clasOdoSecEspes;
	}

	public void setClasOdoSecEspes(Set clasOdoSecEspes) {
		this.clasOdoSecEspes = clasOdoSecEspes;
	}

	public Set getNivelAutorAgrServs() {
		return this.nivelAutorAgrServs;
	}

	public void setNivelAutorAgrServs(Set nivelAutorAgrServs) {
		this.nivelAutorAgrServs = nivelAutorAgrServs;
	}

	public Set getIndCalidadEspecialidads() {
		return this.indCalidadEspecialidads;
	}

	public void setIndCalidadEspecialidads(Set indCalidadEspecialidads) {
		this.indCalidadEspecialidads = indCalidadEspecialidads;
	}

	public Set getAsociosDetFacturas() {
		return this.asociosDetFacturas;
	}

	public void setAsociosDetFacturas(Set asociosDetFacturas) {
		this.asociosDetFacturas = asociosDetFacturas;
	}

	public Set getPaquetesOdontologicoses() {
		return this.paquetesOdontologicoses;
	}

	public void setPaquetesOdontologicoses(Set paquetesOdontologicoses) {
		this.paquetesOdontologicoses = paquetesOdontologicoses;
	}

	public Set getProgramases() {
		return this.programases;
	}

	public void setProgramases(Set programases) {
		this.programases = programases;
	}

	public Set getAgruSerDescComConvxconts() {
		return this.agruSerDescComConvxconts;
	}

	public void setAgruSerDescComConvxconts(Set agruSerDescComConvxconts) {
		this.agruSerDescComConvxconts = agruSerDescComConvxconts;
	}

	public Set getAgruSerExepCobConvxconts() {
		return this.agruSerExepCobConvxconts;
	}

	public void setAgruSerExepCobConvxconts(Set agruSerExepCobConvxconts) {
		this.agruSerExepCobConvxconts = agruSerExepCobConvxconts;
	}

}
