package com.servinte.axioma.orm;

// Generated Apr 7, 2010 3:58:52 PM by Hibernate Tools 3.2.5.Beta

import java.util.HashSet;
import java.util.Set;

/**
 * EstadosRecibosCaja generated by hbm2java
 */
public class EstadosRecibosCaja implements java.io.Serializable {

	private int codigo;
	private String descripcion;
	private Set recibosCajas = new HashSet(0);

	public EstadosRecibosCaja() {
	}

	public EstadosRecibosCaja(int codigo, String descripcion) {
		this.codigo = codigo;
		this.descripcion = descripcion;
	}

	public EstadosRecibosCaja(int codigo, String descripcion, Set recibosCajas) {
		this.codigo = codigo;
		this.descripcion = descripcion;
		this.recibosCajas = recibosCajas;
	}

	public int getCodigo() {
		return this.codigo;
	}

	public void setCodigo(int codigo) {
		this.codigo = codigo;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Set getRecibosCajas() {
		return this.recibosCajas;
	}

	public void setRecibosCajas(Set recibosCajas) {
		this.recibosCajas = recibosCajas;
	}

}
