package com.servinte.axioma.orm;

// Generated Apr 7, 2010 3:58:52 PM by Hibernate Tools 3.2.5.Beta

import java.util.HashSet;
import java.util.Set;

/**
 * EstadosCama generated by hbm2java
 */
public class EstadosCama implements java.io.Serializable {

	private int codigo;
	private String nombre;
	private String color;
	private Set logEstadosCamasForEstadoNuevo = new HashSet(0);
	private Set procesoAutomaticoCensos = new HashSet(0);
	private Set camas1s = new HashSet(0);
	private Set logEstadosCamasForEstadoOriginal = new HashSet(0);

	public EstadosCama() {
	}

	public EstadosCama(int codigo, String nombre) {
		this.codigo = codigo;
		this.nombre = nombre;
	}

	public EstadosCama(int codigo, String nombre, String color,
			Set logEstadosCamasForEstadoNuevo, Set procesoAutomaticoCensos,
			Set camas1s, Set logEstadosCamasForEstadoOriginal) {
		this.codigo = codigo;
		this.nombre = nombre;
		this.color = color;
		this.logEstadosCamasForEstadoNuevo = logEstadosCamasForEstadoNuevo;
		this.procesoAutomaticoCensos = procesoAutomaticoCensos;
		this.camas1s = camas1s;
		this.logEstadosCamasForEstadoOriginal = logEstadosCamasForEstadoOriginal;
	}

	public int getCodigo() {
		return this.codigo;
	}

	public void setCodigo(int codigo) {
		this.codigo = codigo;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getColor() {
		return this.color;
	}

	public void setColor(String color) {
		this.color = color;
	}

	public Set getLogEstadosCamasForEstadoNuevo() {
		return this.logEstadosCamasForEstadoNuevo;
	}

	public void setLogEstadosCamasForEstadoNuevo(
			Set logEstadosCamasForEstadoNuevo) {
		this.logEstadosCamasForEstadoNuevo = logEstadosCamasForEstadoNuevo;
	}

	public Set getProcesoAutomaticoCensos() {
		return this.procesoAutomaticoCensos;
	}

	public void setProcesoAutomaticoCensos(Set procesoAutomaticoCensos) {
		this.procesoAutomaticoCensos = procesoAutomaticoCensos;
	}

	public Set getCamas1s() {
		return this.camas1s;
	}

	public void setCamas1s(Set camas1s) {
		this.camas1s = camas1s;
	}

	public Set getLogEstadosCamasForEstadoOriginal() {
		return this.logEstadosCamasForEstadoOriginal;
	}

	public void setLogEstadosCamasForEstadoOriginal(
			Set logEstadosCamasForEstadoOriginal) {
		this.logEstadosCamasForEstadoOriginal = logEstadosCamasForEstadoOriginal;
	}

}
