package com.servinte.axioma.orm;

// Generated 17/08/2012 10:54:42 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * EstadosPeticion generated by hbm2java
 */
public class EstadosPeticion implements java.io.Serializable {

	private int codigo;
	private String nombre;
	private Set peticionQxes = new HashSet(0);

	public EstadosPeticion() {
	}

	public EstadosPeticion(int codigo, String nombre) {
		this.codigo = codigo;
		this.nombre = nombre;
	}

	public EstadosPeticion(int codigo, String nombre, Set peticionQxes) {
		this.codigo = codigo;
		this.nombre = nombre;
		this.peticionQxes = peticionQxes;
	}

	public int getCodigo() {
		return this.codigo;
	}

	public void setCodigo(int codigo) {
		this.codigo = codigo;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Set getPeticionQxes() {
		return this.peticionQxes;
	}

	public void setPeticionQxes(Set peticionQxes) {
		this.peticionQxes = peticionQxes;
	}

}
