package com.servinte.axioma.orm;

// Generated Apr 7, 2010 3:58:52 PM by Hibernate Tools 3.2.5.Beta

/**
 * FinServNaturalezaId generated by hbm2java
 */
public class FinServNaturalezaId implements java.io.Serializable {

	private int finalidad;
	private String naturaleza;
	private int institucion;

	public FinServNaturalezaId() {
	}

	public FinServNaturalezaId(int finalidad, String naturaleza, int institucion) {
		this.finalidad = finalidad;
		this.naturaleza = naturaleza;
		this.institucion = institucion;
	}

	public int getFinalidad() {
		return this.finalidad;
	}

	public void setFinalidad(int finalidad) {
		this.finalidad = finalidad;
	}

	public String getNaturaleza() {
		return this.naturaleza;
	}

	public void setNaturaleza(String naturaleza) {
		this.naturaleza = naturaleza;
	}

	public int getInstitucion() {
		return this.institucion;
	}

	public void setInstitucion(int institucion) {
		this.institucion = institucion;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof FinServNaturalezaId))
			return false;
		FinServNaturalezaId castOther = (FinServNaturalezaId) other;

		return (this.getFinalidad() == castOther.getFinalidad())
				&& ((this.getNaturaleza() == castOther.getNaturaleza()) || (this
						.getNaturaleza() != null
						&& castOther.getNaturaleza() != null && this
						.getNaturaleza().equals(castOther.getNaturaleza())))
				&& (this.getInstitucion() == castOther.getInstitucion());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getFinalidad();
		result = 37
				* result
				+ (getNaturaleza() == null ? 0 : this.getNaturaleza()
						.hashCode());
		result = 37 * result + this.getInstitucion();
		return result;
	}

}
