package com.servinte.axioma.orm;

// Generated Apr 7, 2010 3:58:52 PM by Hibernate Tools 3.2.5.Beta

import java.util.HashSet;
import java.util.Set;

/**
 * FuncionalParametrizables generated by hbm2java
 */
public class FuncionalParametrizables implements java.io.Serializable {

	private int codigo;
	private String descripcion;
	private Set funSecParametrizadases = new HashSet(0);

	public FuncionalParametrizables() {
	}

	public FuncionalParametrizables(int codigo) {
		this.codigo = codigo;
	}

	public FuncionalParametrizables(int codigo, String descripcion,
			Set funSecParametrizadases) {
		this.codigo = codigo;
		this.descripcion = descripcion;
		this.funSecParametrizadases = funSecParametrizadases;
	}

	public int getCodigo() {
		return this.codigo;
	}

	public void setCodigo(int codigo) {
		this.codigo = codigo;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Set getFunSecParametrizadases() {
		return this.funSecParametrizadases;
	}

	public void setFunSecParametrizadases(Set funSecParametrizadases) {
		this.funSecParametrizadases = funSecParametrizadases;
	}

}
