package com.servinte.axioma.orm;

// Generated Apr 7, 2010 3:58:52 PM by Hibernate Tools 3.2.5.Beta

/**
 * FuncionalidadSinPac generated by hbm2java
 */
public class FuncionalidadSinPac implements java.io.Serializable {

	private int codigoFunc;
	private Funcionalidades funcionalidades;

	public FuncionalidadSinPac() {
	}

	public FuncionalidadSinPac(Funcionalidades funcionalidades) {
		this.funcionalidades = funcionalidades;
	}

	public int getCodigoFunc() {
		return this.codigoFunc;
	}

	public void setCodigoFunc(int codigoFunc) {
		this.codigoFunc = codigoFunc;
	}

	public Funcionalidades getFuncionalidades() {
		return this.funcionalidades;
	}

	public void setFuncionalidades(Funcionalidades funcionalidades) {
		this.funcionalidades = funcionalidades;
	}

}
