package com.servinte.axioma.orm;

// Generated Jan 12, 2011 11:27:59 AM by Hibernate Tools 3.2.4.GA

import java.util.Date;

/**
 * HistoAutorizacionIngEstan generated by hbm2java
 */
public class HistoAutorizacionIngEstan implements java.io.Serializable {

	private long codigoPk;
	private AutorizacionesIngreEstancia autorizacionesIngreEstancia;
	private Usuarios usuarios;
	private Date fechaInicioAutorizacion;
	private long consecutivoAdmision;
	private int diasEstanciaAutorizados;
	private String usuarioContacta;
	private String cargoUsuarioContacta;
	private String observaciones;
	private Integer convenioRecobro;
	private String otroConvenioRecobro;
	private char indicativoTemporal;
	private int centroCostoSolicitante;
	private String estado;
	private Date fechaModifica;
	private String horaModifica;
	private String accionRealizada;

	public HistoAutorizacionIngEstan() {
	}

	public HistoAutorizacionIngEstan(long codigoPk, Usuarios usuarios,
			Date fechaInicioAutorizacion, long consecutivoAdmision,
			int diasEstanciaAutorizados, String usuarioContacta,
			String cargoUsuarioContacta, char indicativoTemporal,
			int centroCostoSolicitante, String estado, Date fechaModifica,
			String horaModifica, String accionRealizada) {
		this.codigoPk = codigoPk;
		this.usuarios = usuarios;
		this.fechaInicioAutorizacion = fechaInicioAutorizacion;
		this.consecutivoAdmision = consecutivoAdmision;
		this.diasEstanciaAutorizados = diasEstanciaAutorizados;
		this.usuarioContacta = usuarioContacta;
		this.cargoUsuarioContacta = cargoUsuarioContacta;
		this.indicativoTemporal = indicativoTemporal;
		this.centroCostoSolicitante = centroCostoSolicitante;
		this.estado = estado;
		this.fechaModifica = fechaModifica;
		this.horaModifica = horaModifica;
		this.accionRealizada = accionRealizada;
	}

	public HistoAutorizacionIngEstan(long codigoPk,
			AutorizacionesIngreEstancia autorizacionesIngreEstancia,
			Usuarios usuarios, Date fechaInicioAutorizacion,
			long consecutivoAdmision, int diasEstanciaAutorizados,
			String usuarioContacta, String cargoUsuarioContacta,
			String observaciones, Integer convenioRecobro,
			String otroConvenioRecobro, char indicativoTemporal,
			int centroCostoSolicitante, String estado, Date fechaModifica,
			String horaModifica, String accionRealizada) {
		this.codigoPk = codigoPk;
		this.autorizacionesIngreEstancia = autorizacionesIngreEstancia;
		this.usuarios = usuarios;
		this.fechaInicioAutorizacion = fechaInicioAutorizacion;
		this.consecutivoAdmision = consecutivoAdmision;
		this.diasEstanciaAutorizados = diasEstanciaAutorizados;
		this.usuarioContacta = usuarioContacta;
		this.cargoUsuarioContacta = cargoUsuarioContacta;
		this.observaciones = observaciones;
		this.convenioRecobro = convenioRecobro;
		this.otroConvenioRecobro = otroConvenioRecobro;
		this.indicativoTemporal = indicativoTemporal;
		this.centroCostoSolicitante = centroCostoSolicitante;
		this.estado = estado;
		this.fechaModifica = fechaModifica;
		this.horaModifica = horaModifica;
		this.accionRealizada = accionRealizada;
	}

	public long getCodigoPk() {
		return this.codigoPk;
	}

	public void setCodigoPk(long codigoPk) {
		this.codigoPk = codigoPk;
	}

	public AutorizacionesIngreEstancia getAutorizacionesIngreEstancia() {
		return this.autorizacionesIngreEstancia;
	}

	public void setAutorizacionesIngreEstancia(
			AutorizacionesIngreEstancia autorizacionesIngreEstancia) {
		this.autorizacionesIngreEstancia = autorizacionesIngreEstancia;
	}

	public Usuarios getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(Usuarios usuarios) {
		this.usuarios = usuarios;
	}

	public Date getFechaInicioAutorizacion() {
		return this.fechaInicioAutorizacion;
	}

	public void setFechaInicioAutorizacion(Date fechaInicioAutorizacion) {
		this.fechaInicioAutorizacion = fechaInicioAutorizacion;
	}

	public long getConsecutivoAdmision() {
		return this.consecutivoAdmision;
	}

	public void setConsecutivoAdmision(long consecutivoAdmision) {
		this.consecutivoAdmision = consecutivoAdmision;
	}

	public int getDiasEstanciaAutorizados() {
		return this.diasEstanciaAutorizados;
	}

	public void setDiasEstanciaAutorizados(int diasEstanciaAutorizados) {
		this.diasEstanciaAutorizados = diasEstanciaAutorizados;
	}

	public String getUsuarioContacta() {
		return this.usuarioContacta;
	}

	public void setUsuarioContacta(String usuarioContacta) {
		this.usuarioContacta = usuarioContacta;
	}

	public String getCargoUsuarioContacta() {
		return this.cargoUsuarioContacta;
	}

	public void setCargoUsuarioContacta(String cargoUsuarioContacta) {
		this.cargoUsuarioContacta = cargoUsuarioContacta;
	}

	public String getObservaciones() {
		return this.observaciones;
	}

	public void setObservaciones(String observaciones) {
		this.observaciones = observaciones;
	}

	public Integer getConvenioRecobro() {
		return this.convenioRecobro;
	}

	public void setConvenioRecobro(Integer convenioRecobro) {
		this.convenioRecobro = convenioRecobro;
	}

	public String getOtroConvenioRecobro() {
		return this.otroConvenioRecobro;
	}

	public void setOtroConvenioRecobro(String otroConvenioRecobro) {
		this.otroConvenioRecobro = otroConvenioRecobro;
	}

	public char getIndicativoTemporal() {
		return this.indicativoTemporal;
	}

	public void setIndicativoTemporal(char indicativoTemporal) {
		this.indicativoTemporal = indicativoTemporal;
	}

	public int getCentroCostoSolicitante() {
		return this.centroCostoSolicitante;
	}

	public void setCentroCostoSolicitante(int centroCostoSolicitante) {
		this.centroCostoSolicitante = centroCostoSolicitante;
	}

	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	public Date getFechaModifica() {
		return this.fechaModifica;
	}

	public void setFechaModifica(Date fechaModifica) {
		this.fechaModifica = fechaModifica;
	}

	public String getHoraModifica() {
		return this.horaModifica;
	}

	public void setHoraModifica(String horaModifica) {
		this.horaModifica = horaModifica;
	}

	public String getAccionRealizada() {
		return this.accionRealizada;
	}

	public void setAccionRealizada(String accionRealizada) {
		this.accionRealizada = accionRealizada;
	}

}
