package com.servinte.axioma.orm;

// Generated Apr 7, 2010 3:58:52 PM by Hibernate Tools 3.2.5.Beta

import java.math.BigDecimal;
import java.util.Date;

/**
 * HistoricoSubcuentas generated by hbm2java
 */
public class HistoricoSubcuentas implements java.io.Serializable {

	private HistoricoSubcuentasId id;
	private Facturas facturas;
	private EsquemasTarifarios esquemasTarifariosByEsquemaTarifariosArticulos;
	private EstratosSociales estratosSociales;
	private Pacientes pacientes;
	private Convenios convenios;
	private Ingresos ingresos;
	private NaturalezaPacientes naturalezaPacientes;
	private Contratos contratos;
	private EsquemasTarifarios esquemasTarifariosByEsquemaTarifariosServicios;
	private MontosCobro montosCobro;
	private Usuarios usuarios;
	private TiposAfiliado tiposAfiliado;
	private EsquemasTarifarios esquemasTarifariosByEsquemaTarServOriginal;
	private EsquemasTarifarios esquemasTarifariosByEsquemaTarArtiOriginal;
	private String nroPoliza;
	private String nroCarnet;
	private String nroAutorizacion;
	private Date fechaAfiliacion;
	private Integer semanasCotizacion;
	private BigDecimal valorUtilizadoSoat;
	private int nroPrioridad;
	private BigDecimal porcentajeAutorizado;
	private BigDecimal montoAutorizado;
	private String obsParametrosDistribucion;
	private char facturado;
	private Date fechaModifica;
	private String horaModifica;

	public HistoricoSubcuentas() {
	}

	public HistoricoSubcuentas(HistoricoSubcuentasId id, Facturas facturas,
			EstratosSociales estratosSociales, Pacientes pacientes,
			Convenios convenios, Ingresos ingresos,
			NaturalezaPacientes naturalezaPacientes, Contratos contratos,
			MontosCobro montosCobro, Usuarios usuarios, int nroPrioridad,
			char facturado, Date fechaModifica, String horaModifica) {
		this.id = id;
		this.facturas = facturas;
		this.estratosSociales = estratosSociales;
		this.pacientes = pacientes;
		this.convenios = convenios;
		this.ingresos = ingresos;
		this.naturalezaPacientes = naturalezaPacientes;
		this.contratos = contratos;
		this.montosCobro = montosCobro;
		this.usuarios = usuarios;
		this.nroPrioridad = nroPrioridad;
		this.facturado = facturado;
		this.fechaModifica = fechaModifica;
		this.horaModifica = horaModifica;
	}

	public HistoricoSubcuentas(HistoricoSubcuentasId id, Facturas facturas,
			EsquemasTarifarios esquemasTarifariosByEsquemaTarifariosArticulos,
			EstratosSociales estratosSociales, Pacientes pacientes,
			Convenios convenios, Ingresos ingresos,
			NaturalezaPacientes naturalezaPacientes, Contratos contratos,
			EsquemasTarifarios esquemasTarifariosByEsquemaTarifariosServicios,
			MontosCobro montosCobro, Usuarios usuarios,
			TiposAfiliado tiposAfiliado,
			EsquemasTarifarios esquemasTarifariosByEsquemaTarServOriginal,
			EsquemasTarifarios esquemasTarifariosByEsquemaTarArtiOriginal,
			String nroPoliza, String nroCarnet, String nroAutorizacion,
			Date fechaAfiliacion, Integer semanasCotizacion,
			BigDecimal valorUtilizadoSoat, int nroPrioridad,
			BigDecimal porcentajeAutorizado, BigDecimal montoAutorizado,
			String obsParametrosDistribucion, char facturado,
			Date fechaModifica, String horaModifica) {
		this.id = id;
		this.facturas = facturas;
		this.esquemasTarifariosByEsquemaTarifariosArticulos = esquemasTarifariosByEsquemaTarifariosArticulos;
		this.estratosSociales = estratosSociales;
		this.pacientes = pacientes;
		this.convenios = convenios;
		this.ingresos = ingresos;
		this.naturalezaPacientes = naturalezaPacientes;
		this.contratos = contratos;
		this.esquemasTarifariosByEsquemaTarifariosServicios = esquemasTarifariosByEsquemaTarifariosServicios;
		this.montosCobro = montosCobro;
		this.usuarios = usuarios;
		this.tiposAfiliado = tiposAfiliado;
		this.esquemasTarifariosByEsquemaTarServOriginal = esquemasTarifariosByEsquemaTarServOriginal;
		this.esquemasTarifariosByEsquemaTarArtiOriginal = esquemasTarifariosByEsquemaTarArtiOriginal;
		this.nroPoliza = nroPoliza;
		this.nroCarnet = nroCarnet;
		this.nroAutorizacion = nroAutorizacion;
		this.fechaAfiliacion = fechaAfiliacion;
		this.semanasCotizacion = semanasCotizacion;
		this.valorUtilizadoSoat = valorUtilizadoSoat;
		this.nroPrioridad = nroPrioridad;
		this.porcentajeAutorizado = porcentajeAutorizado;
		this.montoAutorizado = montoAutorizado;
		this.obsParametrosDistribucion = obsParametrosDistribucion;
		this.facturado = facturado;
		this.fechaModifica = fechaModifica;
		this.horaModifica = horaModifica;
	}

	public HistoricoSubcuentasId getId() {
		return this.id;
	}

	public void setId(HistoricoSubcuentasId id) {
		this.id = id;
	}

	public Facturas getFacturas() {
		return this.facturas;
	}

	public void setFacturas(Facturas facturas) {
		this.facturas = facturas;
	}

	public EsquemasTarifarios getEsquemasTarifariosByEsquemaTarifariosArticulos() {
		return this.esquemasTarifariosByEsquemaTarifariosArticulos;
	}

	public void setEsquemasTarifariosByEsquemaTarifariosArticulos(
			EsquemasTarifarios esquemasTarifariosByEsquemaTarifariosArticulos) {
		this.esquemasTarifariosByEsquemaTarifariosArticulos = esquemasTarifariosByEsquemaTarifariosArticulos;
	}

	public EstratosSociales getEstratosSociales() {
		return this.estratosSociales;
	}

	public void setEstratosSociales(EstratosSociales estratosSociales) {
		this.estratosSociales = estratosSociales;
	}

	public Pacientes getPacientes() {
		return this.pacientes;
	}

	public void setPacientes(Pacientes pacientes) {
		this.pacientes = pacientes;
	}

	public Convenios getConvenios() {
		return this.convenios;
	}

	public void setConvenios(Convenios convenios) {
		this.convenios = convenios;
	}

	public Ingresos getIngresos() {
		return this.ingresos;
	}

	public void setIngresos(Ingresos ingresos) {
		this.ingresos = ingresos;
	}

	public NaturalezaPacientes getNaturalezaPacientes() {
		return this.naturalezaPacientes;
	}

	public void setNaturalezaPacientes(NaturalezaPacientes naturalezaPacientes) {
		this.naturalezaPacientes = naturalezaPacientes;
	}

	public Contratos getContratos() {
		return this.contratos;
	}

	public void setContratos(Contratos contratos) {
		this.contratos = contratos;
	}

	public EsquemasTarifarios getEsquemasTarifariosByEsquemaTarifariosServicios() {
		return this.esquemasTarifariosByEsquemaTarifariosServicios;
	}

	public void setEsquemasTarifariosByEsquemaTarifariosServicios(
			EsquemasTarifarios esquemasTarifariosByEsquemaTarifariosServicios) {
		this.esquemasTarifariosByEsquemaTarifariosServicios = esquemasTarifariosByEsquemaTarifariosServicios;
	}

	public MontosCobro getMontosCobro() {
		return this.montosCobro;
	}

	public void setMontosCobro(MontosCobro montosCobro) {
		this.montosCobro = montosCobro;
	}

	public Usuarios getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(Usuarios usuarios) {
		this.usuarios = usuarios;
	}

	public TiposAfiliado getTiposAfiliado() {
		return this.tiposAfiliado;
	}

	public void setTiposAfiliado(TiposAfiliado tiposAfiliado) {
		this.tiposAfiliado = tiposAfiliado;
	}

	public EsquemasTarifarios getEsquemasTarifariosByEsquemaTarServOriginal() {
		return this.esquemasTarifariosByEsquemaTarServOriginal;
	}

	public void setEsquemasTarifariosByEsquemaTarServOriginal(
			EsquemasTarifarios esquemasTarifariosByEsquemaTarServOriginal) {
		this.esquemasTarifariosByEsquemaTarServOriginal = esquemasTarifariosByEsquemaTarServOriginal;
	}

	public EsquemasTarifarios getEsquemasTarifariosByEsquemaTarArtiOriginal() {
		return this.esquemasTarifariosByEsquemaTarArtiOriginal;
	}

	public void setEsquemasTarifariosByEsquemaTarArtiOriginal(
			EsquemasTarifarios esquemasTarifariosByEsquemaTarArtiOriginal) {
		this.esquemasTarifariosByEsquemaTarArtiOriginal = esquemasTarifariosByEsquemaTarArtiOriginal;
	}

	public String getNroPoliza() {
		return this.nroPoliza;
	}

	public void setNroPoliza(String nroPoliza) {
		this.nroPoliza = nroPoliza;
	}

	public String getNroCarnet() {
		return this.nroCarnet;
	}

	public void setNroCarnet(String nroCarnet) {
		this.nroCarnet = nroCarnet;
	}

	public String getNroAutorizacion() {
		return this.nroAutorizacion;
	}

	public void setNroAutorizacion(String nroAutorizacion) {
		this.nroAutorizacion = nroAutorizacion;
	}

	public Date getFechaAfiliacion() {
		return this.fechaAfiliacion;
	}

	public void setFechaAfiliacion(Date fechaAfiliacion) {
		this.fechaAfiliacion = fechaAfiliacion;
	}

	public Integer getSemanasCotizacion() {
		return this.semanasCotizacion;
	}

	public void setSemanasCotizacion(Integer semanasCotizacion) {
		this.semanasCotizacion = semanasCotizacion;
	}

	public BigDecimal getValorUtilizadoSoat() {
		return this.valorUtilizadoSoat;
	}

	public void setValorUtilizadoSoat(BigDecimal valorUtilizadoSoat) {
		this.valorUtilizadoSoat = valorUtilizadoSoat;
	}

	public int getNroPrioridad() {
		return this.nroPrioridad;
	}

	public void setNroPrioridad(int nroPrioridad) {
		this.nroPrioridad = nroPrioridad;
	}

	public BigDecimal getPorcentajeAutorizado() {
		return this.porcentajeAutorizado;
	}

	public void setPorcentajeAutorizado(BigDecimal porcentajeAutorizado) {
		this.porcentajeAutorizado = porcentajeAutorizado;
	}

	public BigDecimal getMontoAutorizado() {
		return this.montoAutorizado;
	}

	public void setMontoAutorizado(BigDecimal montoAutorizado) {
		this.montoAutorizado = montoAutorizado;
	}

	public String getObsParametrosDistribucion() {
		return this.obsParametrosDistribucion;
	}

	public void setObsParametrosDistribucion(String obsParametrosDistribucion) {
		this.obsParametrosDistribucion = obsParametrosDistribucion;
	}

	public char getFacturado() {
		return this.facturado;
	}

	public void setFacturado(char facturado) {
		this.facturado = facturado;
	}

	public Date getFechaModifica() {
		return this.fechaModifica;
	}

	public void setFechaModifica(Date fechaModifica) {
		this.fechaModifica = fechaModifica;
	}

	public String getHoraModifica() {
		return this.horaModifica;
	}

	public void setHoraModifica(String horaModifica) {
		this.horaModifica = horaModifica;
	}

}
