package com.servinte.axioma.orm;

// Generated Apr 7, 2010 3:58:52 PM by Hibernate Tools 3.2.5.Beta

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * IncluExcluCc generated by hbm2java
 */
public class IncluExcluCc implements java.io.Serializable {

	private long codigo;
	private InclusionesExclusiones inclusionesExclusiones;
	private Usuarios usuarios;
	private Instituciones instituciones;
	private CentrosCosto centrosCosto;
	private Date fechaModifica;
	private String horaModifica;
	private Set artIncluexcluCcs = new HashSet(0);
	private Set serIncluexcluCcs = new HashSet(0);
	private Set agruSerIncluexcluCcs = new HashSet(0);
	private Set incluexcluContratos = new HashSet(0);
	private Set agruArtIncluexcluCcs = new HashSet(0);

	public IncluExcluCc() {
	}

	public IncluExcluCc(long codigo,
			InclusionesExclusiones inclusionesExclusiones, Usuarios usuarios,
			Instituciones instituciones, Date fechaModifica, String horaModifica) {
		this.codigo = codigo;
		this.inclusionesExclusiones = inclusionesExclusiones;
		this.usuarios = usuarios;
		this.instituciones = instituciones;
		this.fechaModifica = fechaModifica;
		this.horaModifica = horaModifica;
	}

	public IncluExcluCc(long codigo,
			InclusionesExclusiones inclusionesExclusiones, Usuarios usuarios,
			Instituciones instituciones, CentrosCosto centrosCosto,
			Date fechaModifica, String horaModifica, Set artIncluexcluCcs,
			Set serIncluexcluCcs, Set agruSerIncluexcluCcs,
			Set incluexcluContratos, Set agruArtIncluexcluCcs) {
		this.codigo = codigo;
		this.inclusionesExclusiones = inclusionesExclusiones;
		this.usuarios = usuarios;
		this.instituciones = instituciones;
		this.centrosCosto = centrosCosto;
		this.fechaModifica = fechaModifica;
		this.horaModifica = horaModifica;
		this.artIncluexcluCcs = artIncluexcluCcs;
		this.serIncluexcluCcs = serIncluexcluCcs;
		this.agruSerIncluexcluCcs = agruSerIncluexcluCcs;
		this.incluexcluContratos = incluexcluContratos;
		this.agruArtIncluexcluCcs = agruArtIncluexcluCcs;
	}

	public long getCodigo() {
		return this.codigo;
	}

	public void setCodigo(long codigo) {
		this.codigo = codigo;
	}

	public InclusionesExclusiones getInclusionesExclusiones() {
		return this.inclusionesExclusiones;
	}

	public void setInclusionesExclusiones(
			InclusionesExclusiones inclusionesExclusiones) {
		this.inclusionesExclusiones = inclusionesExclusiones;
	}

	public Usuarios getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(Usuarios usuarios) {
		this.usuarios = usuarios;
	}

	public Instituciones getInstituciones() {
		return this.instituciones;
	}

	public void setInstituciones(Instituciones instituciones) {
		this.instituciones = instituciones;
	}

	public CentrosCosto getCentrosCosto() {
		return this.centrosCosto;
	}

	public void setCentrosCosto(CentrosCosto centrosCosto) {
		this.centrosCosto = centrosCosto;
	}

	public Date getFechaModifica() {
		return this.fechaModifica;
	}

	public void setFechaModifica(Date fechaModifica) {
		this.fechaModifica = fechaModifica;
	}

	public String getHoraModifica() {
		return this.horaModifica;
	}

	public void setHoraModifica(String horaModifica) {
		this.horaModifica = horaModifica;
	}

	public Set getArtIncluexcluCcs() {
		return this.artIncluexcluCcs;
	}

	public void setArtIncluexcluCcs(Set artIncluexcluCcs) {
		this.artIncluexcluCcs = artIncluexcluCcs;
	}

	public Set getSerIncluexcluCcs() {
		return this.serIncluexcluCcs;
	}

	public void setSerIncluexcluCcs(Set serIncluexcluCcs) {
		this.serIncluexcluCcs = serIncluexcluCcs;
	}

	public Set getAgruSerIncluexcluCcs() {
		return this.agruSerIncluexcluCcs;
	}

	public void setAgruSerIncluexcluCcs(Set agruSerIncluexcluCcs) {
		this.agruSerIncluexcluCcs = agruSerIncluexcluCcs;
	}

	public Set getIncluexcluContratos() {
		return this.incluexcluContratos;
	}

	public void setIncluexcluContratos(Set incluexcluContratos) {
		this.incluexcluContratos = incluexcluContratos;
	}

	public Set getAgruArtIncluexcluCcs() {
		return this.agruArtIncluexcluCcs;
	}

	public void setAgruArtIncluexcluCcs(Set agruArtIncluexcluCcs) {
		this.agruArtIncluexcluCcs = agruArtIncluexcluCcs;
	}

}
