package com.servinte.axioma.orm;

// Generated Apr 7, 2010 3:58:52 PM by Hibernate Tools 3.2.5.Beta

/**
 * LecturaPlanosAtId generated by hbm2java
 */
public class LecturaPlanosAtId implements java.io.Serializable {

	private String numeroFactura;
	private String codigoPrestador;
	private String tipoIdentificacion;
	private String numeroIdentificacion;
	private String numeroAutorizacion;
	private String tipoServicio;
	private String codigoServicio;
	private String nombreServicio;
	private String cantidad;
	private String valorUnitario;
	private String valorTotal;
	private String usuario;
	private int centroAtencion;

	public LecturaPlanosAtId() {
	}

	public LecturaPlanosAtId(String numeroFactura, String codigoPrestador,
			String tipoIdentificacion, String numeroIdentificacion,
			String tipoServicio, String cantidad, String valorUnitario,
			String valorTotal, String usuario, int centroAtencion) {
		this.numeroFactura = numeroFactura;
		this.codigoPrestador = codigoPrestador;
		this.tipoIdentificacion = tipoIdentificacion;
		this.numeroIdentificacion = numeroIdentificacion;
		this.tipoServicio = tipoServicio;
		this.cantidad = cantidad;
		this.valorUnitario = valorUnitario;
		this.valorTotal = valorTotal;
		this.usuario = usuario;
		this.centroAtencion = centroAtencion;
	}

	public LecturaPlanosAtId(String numeroFactura, String codigoPrestador,
			String tipoIdentificacion, String numeroIdentificacion,
			String numeroAutorizacion, String tipoServicio,
			String codigoServicio, String nombreServicio, String cantidad,
			String valorUnitario, String valorTotal, String usuario,
			int centroAtencion) {
		this.numeroFactura = numeroFactura;
		this.codigoPrestador = codigoPrestador;
		this.tipoIdentificacion = tipoIdentificacion;
		this.numeroIdentificacion = numeroIdentificacion;
		this.numeroAutorizacion = numeroAutorizacion;
		this.tipoServicio = tipoServicio;
		this.codigoServicio = codigoServicio;
		this.nombreServicio = nombreServicio;
		this.cantidad = cantidad;
		this.valorUnitario = valorUnitario;
		this.valorTotal = valorTotal;
		this.usuario = usuario;
		this.centroAtencion = centroAtencion;
	}

	public String getNumeroFactura() {
		return this.numeroFactura;
	}

	public void setNumeroFactura(String numeroFactura) {
		this.numeroFactura = numeroFactura;
	}

	public String getCodigoPrestador() {
		return this.codigoPrestador;
	}

	public void setCodigoPrestador(String codigoPrestador) {
		this.codigoPrestador = codigoPrestador;
	}

	public String getTipoIdentificacion() {
		return this.tipoIdentificacion;
	}

	public void setTipoIdentificacion(String tipoIdentificacion) {
		this.tipoIdentificacion = tipoIdentificacion;
	}

	public String getNumeroIdentificacion() {
		return this.numeroIdentificacion;
	}

	public void setNumeroIdentificacion(String numeroIdentificacion) {
		this.numeroIdentificacion = numeroIdentificacion;
	}

	public String getNumeroAutorizacion() {
		return this.numeroAutorizacion;
	}

	public void setNumeroAutorizacion(String numeroAutorizacion) {
		this.numeroAutorizacion = numeroAutorizacion;
	}

	public String getTipoServicio() {
		return this.tipoServicio;
	}

	public void setTipoServicio(String tipoServicio) {
		this.tipoServicio = tipoServicio;
	}

	public String getCodigoServicio() {
		return this.codigoServicio;
	}

	public void setCodigoServicio(String codigoServicio) {
		this.codigoServicio = codigoServicio;
	}

	public String getNombreServicio() {
		return this.nombreServicio;
	}

	public void setNombreServicio(String nombreServicio) {
		this.nombreServicio = nombreServicio;
	}

	public String getCantidad() {
		return this.cantidad;
	}

	public void setCantidad(String cantidad) {
		this.cantidad = cantidad;
	}

	public String getValorUnitario() {
		return this.valorUnitario;
	}

	public void setValorUnitario(String valorUnitario) {
		this.valorUnitario = valorUnitario;
	}

	public String getValorTotal() {
		return this.valorTotal;
	}

	public void setValorTotal(String valorTotal) {
		this.valorTotal = valorTotal;
	}

	public String getUsuario() {
		return this.usuario;
	}

	public void setUsuario(String usuario) {
		this.usuario = usuario;
	}

	public int getCentroAtencion() {
		return this.centroAtencion;
	}

	public void setCentroAtencion(int centroAtencion) {
		this.centroAtencion = centroAtencion;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof LecturaPlanosAtId))
			return false;
		LecturaPlanosAtId castOther = (LecturaPlanosAtId) other;

		return ((this.getNumeroFactura() == castOther.getNumeroFactura()) || (this
				.getNumeroFactura() != null
				&& castOther.getNumeroFactura() != null && this
				.getNumeroFactura().equals(castOther.getNumeroFactura())))
				&& ((this.getCodigoPrestador() == castOther
						.getCodigoPrestador()) || (this.getCodigoPrestador() != null
						&& castOther.getCodigoPrestador() != null && this
						.getCodigoPrestador().equals(
								castOther.getCodigoPrestador())))
				&& ((this.getTipoIdentificacion() == castOther
						.getTipoIdentificacion()) || (this
						.getTipoIdentificacion() != null
						&& castOther.getTipoIdentificacion() != null && this
						.getTipoIdentificacion().equals(
								castOther.getTipoIdentificacion())))
				&& ((this.getNumeroIdentificacion() == castOther
						.getNumeroIdentificacion()) || (this
						.getNumeroIdentificacion() != null
						&& castOther.getNumeroIdentificacion() != null && this
						.getNumeroIdentificacion().equals(
								castOther.getNumeroIdentificacion())))
				&& ((this.getNumeroAutorizacion() == castOther
						.getNumeroAutorizacion()) || (this
						.getNumeroAutorizacion() != null
						&& castOther.getNumeroAutorizacion() != null && this
						.getNumeroAutorizacion().equals(
								castOther.getNumeroAutorizacion())))
				&& ((this.getTipoServicio() == castOther.getTipoServicio()) || (this
						.getTipoServicio() != null
						&& castOther.getTipoServicio() != null && this
						.getTipoServicio().equals(castOther.getTipoServicio())))
				&& ((this.getCodigoServicio() == castOther.getCodigoServicio()) || (this
						.getCodigoServicio() != null
						&& castOther.getCodigoServicio() != null && this
						.getCodigoServicio().equals(
								castOther.getCodigoServicio())))
				&& ((this.getNombreServicio() == castOther.getNombreServicio()) || (this
						.getNombreServicio() != null
						&& castOther.getNombreServicio() != null && this
						.getNombreServicio().equals(
								castOther.getNombreServicio())))
				&& ((this.getCantidad() == castOther.getCantidad()) || (this
						.getCantidad() != null
						&& castOther.getCantidad() != null && this
						.getCantidad().equals(castOther.getCantidad())))
				&& ((this.getValorUnitario() == castOther.getValorUnitario()) || (this
						.getValorUnitario() != null
						&& castOther.getValorUnitario() != null && this
						.getValorUnitario()
						.equals(castOther.getValorUnitario())))
				&& ((this.getValorTotal() == castOther.getValorTotal()) || (this
						.getValorTotal() != null
						&& castOther.getValorTotal() != null && this
						.getValorTotal().equals(castOther.getValorTotal())))
				&& ((this.getUsuario() == castOther.getUsuario()) || (this
						.getUsuario() != null
						&& castOther.getUsuario() != null && this.getUsuario()
						.equals(castOther.getUsuario())))
				&& (this.getCentroAtencion() == castOther.getCentroAtencion());
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getNumeroFactura() == null ? 0 : this.getNumeroFactura()
						.hashCode());
		result = 37
				* result
				+ (getCodigoPrestador() == null ? 0 : this.getCodigoPrestador()
						.hashCode());
		result = 37
				* result
				+ (getTipoIdentificacion() == null ? 0 : this
						.getTipoIdentificacion().hashCode());
		result = 37
				* result
				+ (getNumeroIdentificacion() == null ? 0 : this
						.getNumeroIdentificacion().hashCode());
		result = 37
				* result
				+ (getNumeroAutorizacion() == null ? 0 : this
						.getNumeroAutorizacion().hashCode());
		result = 37
				* result
				+ (getTipoServicio() == null ? 0 : this.getTipoServicio()
						.hashCode());
		result = 37
				* result
				+ (getCodigoServicio() == null ? 0 : this.getCodigoServicio()
						.hashCode());
		result = 37
				* result
				+ (getNombreServicio() == null ? 0 : this.getNombreServicio()
						.hashCode());
		result = 37 * result
				+ (getCantidad() == null ? 0 : this.getCantidad().hashCode());
		result = 37
				* result
				+ (getValorUnitario() == null ? 0 : this.getValorUnitario()
						.hashCode());
		result = 37
				* result
				+ (getValorTotal() == null ? 0 : this.getValorTotal()
						.hashCode());
		result = 37 * result
				+ (getUsuario() == null ? 0 : this.getUsuario().hashCode());
		result = 37 * result + this.getCentroAtencion();
		return result;
	}

}
