package com.servinte.axioma.orm;

// Generated Apr 7, 2010 3:58:52 PM by Hibernate Tools 3.2.5.Beta

import java.util.Date;

/**
 * LogEliminar generated by hbm2java
 */
public class LogEliminar implements java.io.Serializable {

	private int codigo;
	private Usuarios usuarios;
	private Date fecha;
	private String hora;
	private String observacion;

	public LogEliminar() {
	}

	public LogEliminar(int codigo, Usuarios usuarios, Date fecha, String hora,
			String observacion) {
		this.codigo = codigo;
		this.usuarios = usuarios;
		this.fecha = fecha;
		this.hora = hora;
		this.observacion = observacion;
	}

	public int getCodigo() {
		return this.codigo;
	}

	public void setCodigo(int codigo) {
		this.codigo = codigo;
	}

	public Usuarios getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(Usuarios usuarios) {
		this.usuarios = usuarios;
	}

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	public String getHora() {
		return this.hora;
	}

	public void setHora(String hora) {
		this.hora = hora;
	}

	public String getObservacion() {
		return this.observacion;
	}

	public void setObservacion(String observacion) {
		this.observacion = observacion;
	}

}
