package com.servinte.axioma.orm;

// Generated Jan 13, 2011 8:51:05 AM by Hibernate Tools 3.2.4.GA

import java.util.Date;

/**
 * LogProfSaludNoHonorario generated by hbm2java
 */
public class LogProfSaludNoHonorario implements java.io.Serializable {

	private long codigoPk;
	private Solicitudes solicitudes;
	private Servicios servicios;
	private Date fechaLiquidacionHonorarios;
	private String horaLiquidacionHonorarios;
	private String nombreProfesional;

	public LogProfSaludNoHonorario() {
	}
	
	public LogProfSaludNoHonorario(long codigoPk, Solicitudes solicitudes,
			Servicios servicios, Date fechaLiquidacionHonorarios,
			String horaLiquidacionHonorarios, String nombreProfesional) {
		this.codigoPk = codigoPk;
		this.solicitudes = solicitudes;
		this.servicios = servicios;
		this.fechaLiquidacionHonorarios = fechaLiquidacionHonorarios;
		this.horaLiquidacionHonorarios = horaLiquidacionHonorarios;
		this.nombreProfesional = nombreProfesional;
	}

	public LogProfSaludNoHonorario(int numeroSolicitud,
			int codigoServicio, Date fechaLiquidacionHonorarios,
			String horaLiquidacionHonorarios, String nombreProfesional) {
		this.solicitudes = new Solicitudes();
		this.servicios = new Servicios();
		this.solicitudes.setNumeroSolicitud(numeroSolicitud);
		this.servicios.setCodigo(codigoServicio);
		this.fechaLiquidacionHonorarios = fechaLiquidacionHonorarios;
		this.horaLiquidacionHonorarios = horaLiquidacionHonorarios;
		this.nombreProfesional = nombreProfesional;
	}

	public long getCodigoPk() {
		return this.codigoPk;
	}

	public void setCodigoPk(long codigoPk) {
		this.codigoPk = codigoPk;
	}

	public Solicitudes getSolicitudes() {
		return this.solicitudes;
	}

	public void setSolicitudes(Solicitudes solicitudes) {
		this.solicitudes = solicitudes;
	}

	public Servicios getServicios() {
		return this.servicios;
	}

	public void setServicios(Servicios servicios) {
		this.servicios = servicios;
	}

	public Date getFechaLiquidacionHonorarios() {
		return this.fechaLiquidacionHonorarios;
	}

	public void setFechaLiquidacionHonorarios(Date fechaLiquidacionHonorarios) {
		this.fechaLiquidacionHonorarios = fechaLiquidacionHonorarios;
	}

	public String getHoraLiquidacionHonorarios() {
		return this.horaLiquidacionHonorarios;
	}

	public void setHoraLiquidacionHonorarios(String horaLiquidacionHonorarios) {
		this.horaLiquidacionHonorarios = horaLiquidacionHonorarios;
	}

	public String getNombreProfesional() {
		return this.nombreProfesional;
	}

	public void setNombreProfesional(String nombreProfesional) {
		this.nombreProfesional = nombreProfesional;
	}

}
