package com.servinte.axioma.orm;

// Generated Apr 7, 2010 3:58:52 PM by Hibernate Tools 3.2.5.Beta

import java.util.HashSet;
import java.util.Set;

/**
 * NaturalezasServicio generated by hbm2java
 */
public class NaturalezasServicio implements java.io.Serializable {

	private String acronimo;
	private String nombre;
	private Set tiposSerNaturalezas = new HashSet(0);
	private Set finServNaturalezas = new HashSet(0);

	public NaturalezasServicio() {
	}

	public NaturalezasServicio(String acronimo, String nombre) {
		this.acronimo = acronimo;
		this.nombre = nombre;
	}

	public NaturalezasServicio(String acronimo, String nombre,
			Set tiposSerNaturalezas, Set finServNaturalezas) {
		this.acronimo = acronimo;
		this.nombre = nombre;
		this.tiposSerNaturalezas = tiposSerNaturalezas;
		this.finServNaturalezas = finServNaturalezas;
	}

	public String getAcronimo() {
		return this.acronimo;
	}

	public void setAcronimo(String acronimo) {
		this.acronimo = acronimo;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Set getTiposSerNaturalezas() {
		return this.tiposSerNaturalezas;
	}

	public void setTiposSerNaturalezas(Set tiposSerNaturalezas) {
		this.tiposSerNaturalezas = tiposSerNaturalezas;
	}

	public Set getFinServNaturalezas() {
		return this.finServNaturalezas;
	}

	public void setFinServNaturalezas(Set finServNaturalezas) {
		this.finServNaturalezas = finServNaturalezas;
	}

}
