package com.servinte.axioma.orm;

// Generated Jan 25, 2011 12:25:29 PM by Hibernate Tools 3.2.4.GA

import java.util.Date;

/**
 * NivelAutorAgrArt generated by hbm2java
 */
public class NivelAutorAgrArt implements java.io.Serializable {

	private int codigoPk;
	private GrupoInventario grupoInventario;
	private NaturalezaArticulo naturalezaArticulo;
	private NivelAutorServMedic nivelAutorServMedic;
	private ClaseInventario claseInventario;
	private Usuarios usuarios;
	private Integer subgrupoInventario;
	private Date fechaRegistro;
	private String horaRegistro;

	public NivelAutorAgrArt() {
	}

	public NivelAutorAgrArt(int codigoPk,
			NivelAutorServMedic nivelAutorServMedic, Usuarios usuarios,
			Date fechaRegistro, String horaRegistro) {
		this.codigoPk = codigoPk;
		this.nivelAutorServMedic = nivelAutorServMedic;
		this.usuarios = usuarios;
		this.fechaRegistro = fechaRegistro;
		this.horaRegistro = horaRegistro;
	}

	public NivelAutorAgrArt(int codigoPk, GrupoInventario grupoInventario,
			NaturalezaArticulo naturalezaArticulo,
			NivelAutorServMedic nivelAutorServMedic,
			ClaseInventario claseInventario, Usuarios usuarios,
			Integer subgrupoInventario, Date fechaRegistro, String horaRegistro) {
		this.codigoPk = codigoPk;
		this.grupoInventario = grupoInventario;
		this.naturalezaArticulo = naturalezaArticulo;
		this.nivelAutorServMedic = nivelAutorServMedic;
		this.claseInventario = claseInventario;
		this.usuarios = usuarios;
		this.subgrupoInventario = subgrupoInventario;
		this.fechaRegistro = fechaRegistro;
		this.horaRegistro = horaRegistro;
	}

	public int getCodigoPk() {
		return this.codigoPk;
	}

	public void setCodigoPk(int codigoPk) {
		this.codigoPk = codigoPk;
	}

	public GrupoInventario getGrupoInventario() {
		return this.grupoInventario;
	}

	public void setGrupoInventario(GrupoInventario grupoInventario) {
		this.grupoInventario = grupoInventario;
	}

	public NaturalezaArticulo getNaturalezaArticulo() {
		return this.naturalezaArticulo;
	}

	public void setNaturalezaArticulo(NaturalezaArticulo naturalezaArticulo) {
		this.naturalezaArticulo = naturalezaArticulo;
	}

	public NivelAutorServMedic getNivelAutorServMedic() {
		return this.nivelAutorServMedic;
	}

	public void setNivelAutorServMedic(NivelAutorServMedic nivelAutorServMedic) {
		this.nivelAutorServMedic = nivelAutorServMedic;
	}

	public ClaseInventario getClaseInventario() {
		return this.claseInventario;
	}

	public void setClaseInventario(ClaseInventario claseInventario) {
		this.claseInventario = claseInventario;
	}

	public Usuarios getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(Usuarios usuarios) {
		this.usuarios = usuarios;
	}

	public Integer getSubgrupoInventario() {
		return this.subgrupoInventario;
	}

	public void setSubgrupoInventario(Integer subgrupoInventario) {
		this.subgrupoInventario = subgrupoInventario;
	}

	public Date getFechaRegistro() {
		return this.fechaRegistro;
	}

	public void setFechaRegistro(Date fechaRegistro) {
		this.fechaRegistro = fechaRegistro;
	}

	public String getHoraRegistro() {
		return this.horaRegistro;
	}

	public void setHoraRegistro(String horaRegistro) {
		this.horaRegistro = horaRegistro;
	}

}
