package com.servinte.axioma.orm;

// Generated Apr 7, 2010 3:58:52 PM by Hibernate Tools 3.2.5.Beta

import java.math.BigDecimal;
import java.util.Date;

/**
 * OcupacionSalarioBase generated by hbm2java
 */
public class OcupacionSalarioBase implements java.io.Serializable {

	private OcupacionSalarioBaseId id;
	private TiposVinculacion tiposVinculacion;
	private Instituciones instituciones;
	private OcupacionesMedicas ocupacionesMedicas;
	private BigDecimal valor;
	private Date fechaFin;

	public OcupacionSalarioBase() {
	}

	public OcupacionSalarioBase(OcupacionSalarioBaseId id,
			TiposVinculacion tiposVinculacion, Instituciones instituciones,
			OcupacionesMedicas ocupacionesMedicas, BigDecimal valor,
			Date fechaFin) {
		this.id = id;
		this.tiposVinculacion = tiposVinculacion;
		this.instituciones = instituciones;
		this.ocupacionesMedicas = ocupacionesMedicas;
		this.valor = valor;
		this.fechaFin = fechaFin;
	}

	public OcupacionSalarioBaseId getId() {
		return this.id;
	}

	public void setId(OcupacionSalarioBaseId id) {
		this.id = id;
	}

	public TiposVinculacion getTiposVinculacion() {
		return this.tiposVinculacion;
	}

	public void setTiposVinculacion(TiposVinculacion tiposVinculacion) {
		this.tiposVinculacion = tiposVinculacion;
	}

	public Instituciones getInstituciones() {
		return this.instituciones;
	}

	public void setInstituciones(Instituciones instituciones) {
		this.instituciones = instituciones;
	}

	public OcupacionesMedicas getOcupacionesMedicas() {
		return this.ocupacionesMedicas;
	}

	public void setOcupacionesMedicas(OcupacionesMedicas ocupacionesMedicas) {
		this.ocupacionesMedicas = ocupacionesMedicas;
	}

	public BigDecimal getValor() {
		return this.valor;
	}

	public void setValor(BigDecimal valor) {
		this.valor = valor;
	}

	public Date getFechaFin() {
		return this.fechaFin;
	}

	public void setFechaFin(Date fechaFin) {
		this.fechaFin = fechaFin;
	}

}
