package com.servinte.axioma.orm;

// Generated Dec 2, 2010 7:02:43 PM by Hibernate Tools 3.2.4.GA

/**
 * OtrosSiExclusiones generated by hbm2java
 */
public class OtrosSiExclusiones implements java.io.Serializable {

	private long codigoPk;
	private ExclusionesPresupuesto exclusionesPresupuesto;
	private OtrosSi otrosSi;

	public OtrosSiExclusiones() {
	}

	public OtrosSiExclusiones(long codigoPk,
			ExclusionesPresupuesto exclusionesPresupuesto, OtrosSi otrosSi) {
		this.codigoPk = codigoPk;
		this.exclusionesPresupuesto = exclusionesPresupuesto;
		this.otrosSi = otrosSi;
	}

	public long getCodigoPk() {
		return this.codigoPk;
	}

	public void setCodigoPk(long codigoPk) {
		this.codigoPk = codigoPk;
	}

	public ExclusionesPresupuesto getExclusionesPresupuesto() {
		return this.exclusionesPresupuesto;
	}

	public void setExclusionesPresupuesto(
			ExclusionesPresupuesto exclusionesPresupuesto) {
		this.exclusionesPresupuesto = exclusionesPresupuesto;
	}

	public OtrosSi getOtrosSi() {
		return this.otrosSi;
	}

	public void setOtrosSi(OtrosSi otrosSi) {
		this.otrosSi = otrosSi;
	}

}
