package com.servinte.axioma.orm;

// Generated Apr 7, 2010 3:58:52 PM by Hibernate Tools 3.2.5.Beta

/**
 * ParamAsociadas generated by hbm2java
 */
public class ParamAsociadas implements java.io.Serializable {

	private int codigo;
	private TiposParametrizables tiposParametrizables;
	private Medicos medicos;
	private SeccionParametriza seccionParametriza;
	private AlcancesCamposP alcancesCamposP;
	private Instituciones instituciones;
	private CentrosCosto centrosCosto;
	private String orden;
	private String nombre;
	private boolean activo;

	public ParamAsociadas() {
	}

	public ParamAsociadas(int codigo,
			TiposParametrizables tiposParametrizables, Medicos medicos,
			SeccionParametriza seccionParametriza,
			AlcancesCamposP alcancesCamposP, Instituciones instituciones,
			CentrosCosto centrosCosto, String orden, String nombre,
			boolean activo) {
		this.codigo = codigo;
		this.tiposParametrizables = tiposParametrizables;
		this.medicos = medicos;
		this.seccionParametriza = seccionParametriza;
		this.alcancesCamposP = alcancesCamposP;
		this.instituciones = instituciones;
		this.centrosCosto = centrosCosto;
		this.orden = orden;
		this.nombre = nombre;
		this.activo = activo;
	}

	public int getCodigo() {
		return this.codigo;
	}

	public void setCodigo(int codigo) {
		this.codigo = codigo;
	}

	public TiposParametrizables getTiposParametrizables() {
		return this.tiposParametrizables;
	}

	public void setTiposParametrizables(
			TiposParametrizables tiposParametrizables) {
		this.tiposParametrizables = tiposParametrizables;
	}

	public Medicos getMedicos() {
		return this.medicos;
	}

	public void setMedicos(Medicos medicos) {
		this.medicos = medicos;
	}

	public SeccionParametriza getSeccionParametriza() {
		return this.seccionParametriza;
	}

	public void setSeccionParametriza(SeccionParametriza seccionParametriza) {
		this.seccionParametriza = seccionParametriza;
	}

	public AlcancesCamposP getAlcancesCamposP() {
		return this.alcancesCamposP;
	}

	public void setAlcancesCamposP(AlcancesCamposP alcancesCamposP) {
		this.alcancesCamposP = alcancesCamposP;
	}

	public Instituciones getInstituciones() {
		return this.instituciones;
	}

	public void setInstituciones(Instituciones instituciones) {
		this.instituciones = instituciones;
	}

	public CentrosCosto getCentrosCosto() {
		return this.centrosCosto;
	}

	public void setCentrosCosto(CentrosCosto centrosCosto) {
		this.centrosCosto = centrosCosto;
	}

	public String getOrden() {
		return this.orden;
	}

	public void setOrden(String orden) {
		this.orden = orden;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public boolean isActivo() {
		return this.activo;
	}

	public void setActivo(boolean activo) {
		this.activo = activo;
	}

}
