package com.servinte.axioma.orm;

// Generated Jul 6, 2010 10:39:14 AM by Hibernate Tools 3.2.4.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * PlanTratamiento generated by hbm2java
 */
public class PlanTratamiento implements java.io.Serializable {

	private long codigoPk;
	private EvolucionesOdo evolucionesOdo;
	private Pacientes pacientes;
	private Odontograma odontogramaByOdontogramaDiagnostico;
	private Ingresos ingresos;
	private CentroAtencion centroAtencion;
	private CitasOdontologicas citasOdontologicas;
	private Usuarios usuariosByUsuarioModifica;
	private Usuarios usuariosByUsuarioGrabacion;
	private Especialidades especialidades;
	private Odontograma odontogramaByOdontogramaEvolucion;
	private Instituciones instituciones;
	private ValoracionesOdonto valoracionesOdonto;
	private MotivosAtencion motivosAtencion;
	private long consecutivo;
	private Date fechaGrabacion;
	private String horaGrabacion;
	private String estado;
	private String indicativo;
	private String porConfirmar;
	private Date fechaModifica;
	private String horaModifica;
	private String imagen;
	private Integer codigoMedico;
	private Set presupuestoOdontologicos = new HashSet(0);
	private Set hisConfDetPlanTs = new HashSet(0);
	private Set detPlanTratamientos = new HashSet(0);
	private Set programasHallazgoPiezas = new HashSet(0);
	private Set hisConfPlanTratamientos = new HashSet(0);
	private Set logDetPlanTratamientos = new HashSet(0);
	private Set consentimientoInfoOdontos = new HashSet(0);
	private Set logPresupuestoOdonts = new HashSet(0);
	private Set logPlanTratamientos = new HashSet(0);

	public PlanTratamiento() {
	}

	public PlanTratamiento(long codigoPk, Pacientes pacientes,
			Ingresos ingresos, CentroAtencion centroAtencion,
			Usuarios usuariosByUsuarioModifica,
			Usuarios usuariosByUsuarioGrabacion, Instituciones instituciones,
			long consecutivo, Date fechaGrabacion, String horaGrabacion,
			String estado, String indicativo, String porConfirmar,
			Date fechaModifica, String horaModifica) {
		this.codigoPk = codigoPk;
		this.pacientes = pacientes;
		this.ingresos = ingresos;
		this.centroAtencion = centroAtencion;
		this.usuariosByUsuarioModifica = usuariosByUsuarioModifica;
		this.usuariosByUsuarioGrabacion = usuariosByUsuarioGrabacion;
		this.instituciones = instituciones;
		this.consecutivo = consecutivo;
		this.fechaGrabacion = fechaGrabacion;
		this.horaGrabacion = horaGrabacion;
		this.estado = estado;
		this.indicativo = indicativo;
		this.porConfirmar = porConfirmar;
		this.fechaModifica = fechaModifica;
		this.horaModifica = horaModifica;
	}

	public PlanTratamiento(long codigoPk, EvolucionesOdo evolucionesOdo,
			Pacientes pacientes,
			Odontograma odontogramaByOdontogramaDiagnostico, Ingresos ingresos,
			CentroAtencion centroAtencion,
			CitasOdontologicas citasOdontologicas,
			Usuarios usuariosByUsuarioModifica,
			Usuarios usuariosByUsuarioGrabacion, Especialidades especialidades,
			Odontograma odontogramaByOdontogramaEvolucion,
			Instituciones instituciones, ValoracionesOdonto valoracionesOdonto,
			MotivosAtencion motivosAtencion, long consecutivo,
			Date fechaGrabacion, String horaGrabacion, String estado,
			String indicativo, String porConfirmar, Date fechaModifica,
			String horaModifica, String imagen, Integer codigoMedico,
			Set presupuestoOdontologicos, Set hisConfDetPlanTs,
			Set detPlanTratamientos, Set programasHallazgoPiezas,
			Set hisConfPlanTratamientos, Set logDetPlanTratamientos,
			Set consentimientoInfoOdontos, Set logPresupuestoOdonts,
			Set logPlanTratamientos) {
		this.codigoPk = codigoPk;
		this.evolucionesOdo = evolucionesOdo;
		this.pacientes = pacientes;
		this.odontogramaByOdontogramaDiagnostico = odontogramaByOdontogramaDiagnostico;
		this.ingresos = ingresos;
		this.centroAtencion = centroAtencion;
		this.citasOdontologicas = citasOdontologicas;
		this.usuariosByUsuarioModifica = usuariosByUsuarioModifica;
		this.usuariosByUsuarioGrabacion = usuariosByUsuarioGrabacion;
		this.especialidades = especialidades;
		this.odontogramaByOdontogramaEvolucion = odontogramaByOdontogramaEvolucion;
		this.instituciones = instituciones;
		this.valoracionesOdonto = valoracionesOdonto;
		this.motivosAtencion = motivosAtencion;
		this.consecutivo = consecutivo;
		this.fechaGrabacion = fechaGrabacion;
		this.horaGrabacion = horaGrabacion;
		this.estado = estado;
		this.indicativo = indicativo;
		this.porConfirmar = porConfirmar;
		this.fechaModifica = fechaModifica;
		this.horaModifica = horaModifica;
		this.imagen = imagen;
		this.codigoMedico = codigoMedico;
		this.presupuestoOdontologicos = presupuestoOdontologicos;
		this.hisConfDetPlanTs = hisConfDetPlanTs;
		this.detPlanTratamientos = detPlanTratamientos;
		this.programasHallazgoPiezas = programasHallazgoPiezas;
		this.hisConfPlanTratamientos = hisConfPlanTratamientos;
		this.logDetPlanTratamientos = logDetPlanTratamientos;
		this.consentimientoInfoOdontos = consentimientoInfoOdontos;
		this.logPresupuestoOdonts = logPresupuestoOdonts;
		this.logPlanTratamientos = logPlanTratamientos;
	}

	public long getCodigoPk() {
		return this.codigoPk;
	}

	public void setCodigoPk(long codigoPk) {
		this.codigoPk = codigoPk;
	}

	public EvolucionesOdo getEvolucionesOdo() {
		return this.evolucionesOdo;
	}

	public void setEvolucionesOdo(EvolucionesOdo evolucionesOdo) {
		this.evolucionesOdo = evolucionesOdo;
	}

	public Pacientes getPacientes() {
		return this.pacientes;
	}

	public void setPacientes(Pacientes pacientes) {
		this.pacientes = pacientes;
	}

	public Odontograma getOdontogramaByOdontogramaDiagnostico() {
		return this.odontogramaByOdontogramaDiagnostico;
	}

	public void setOdontogramaByOdontogramaDiagnostico(
			Odontograma odontogramaByOdontogramaDiagnostico) {
		this.odontogramaByOdontogramaDiagnostico = odontogramaByOdontogramaDiagnostico;
	}

	public Ingresos getIngresos() {
		return this.ingresos;
	}

	public void setIngresos(Ingresos ingresos) {
		this.ingresos = ingresos;
	}

	public CentroAtencion getCentroAtencion() {
		return this.centroAtencion;
	}

	public void setCentroAtencion(CentroAtencion centroAtencion) {
		this.centroAtencion = centroAtencion;
	}

	public CitasOdontologicas getCitasOdontologicas() {
		return this.citasOdontologicas;
	}

	public void setCitasOdontologicas(CitasOdontologicas citasOdontologicas) {
		this.citasOdontologicas = citasOdontologicas;
	}

	public Usuarios getUsuariosByUsuarioModifica() {
		return this.usuariosByUsuarioModifica;
	}

	public void setUsuariosByUsuarioModifica(Usuarios usuariosByUsuarioModifica) {
		this.usuariosByUsuarioModifica = usuariosByUsuarioModifica;
	}

	public Usuarios getUsuariosByUsuarioGrabacion() {
		return this.usuariosByUsuarioGrabacion;
	}

	public void setUsuariosByUsuarioGrabacion(
			Usuarios usuariosByUsuarioGrabacion) {
		this.usuariosByUsuarioGrabacion = usuariosByUsuarioGrabacion;
	}

	public Especialidades getEspecialidades() {
		return this.especialidades;
	}

	public void setEspecialidades(Especialidades especialidades) {
		this.especialidades = especialidades;
	}

	public Odontograma getOdontogramaByOdontogramaEvolucion() {
		return this.odontogramaByOdontogramaEvolucion;
	}

	public void setOdontogramaByOdontogramaEvolucion(
			Odontograma odontogramaByOdontogramaEvolucion) {
		this.odontogramaByOdontogramaEvolucion = odontogramaByOdontogramaEvolucion;
	}

	public Instituciones getInstituciones() {
		return this.instituciones;
	}

	public void setInstituciones(Instituciones instituciones) {
		this.instituciones = instituciones;
	}

	public ValoracionesOdonto getValoracionesOdonto() {
		return this.valoracionesOdonto;
	}

	public void setValoracionesOdonto(ValoracionesOdonto valoracionesOdonto) {
		this.valoracionesOdonto = valoracionesOdonto;
	}

	public MotivosAtencion getMotivosAtencion() {
		return this.motivosAtencion;
	}

	public void setMotivosAtencion(MotivosAtencion motivosAtencion) {
		this.motivosAtencion = motivosAtencion;
	}

	public long getConsecutivo() {
		return this.consecutivo;
	}

	public void setConsecutivo(long consecutivo) {
		this.consecutivo = consecutivo;
	}

	public Date getFechaGrabacion() {
		return this.fechaGrabacion;
	}

	public void setFechaGrabacion(Date fechaGrabacion) {
		this.fechaGrabacion = fechaGrabacion;
	}

	public String getHoraGrabacion() {
		return this.horaGrabacion;
	}

	public void setHoraGrabacion(String horaGrabacion) {
		this.horaGrabacion = horaGrabacion;
	}

	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	public String getIndicativo() {
		return this.indicativo;
	}

	public void setIndicativo(String indicativo) {
		this.indicativo = indicativo;
	}

	public String getPorConfirmar() {
		return this.porConfirmar;
	}

	public void setPorConfirmar(String porConfirmar) {
		this.porConfirmar = porConfirmar;
	}

	public Date getFechaModifica() {
		return this.fechaModifica;
	}

	public void setFechaModifica(Date fechaModifica) {
		this.fechaModifica = fechaModifica;
	}

	public String getHoraModifica() {
		return this.horaModifica;
	}

	public void setHoraModifica(String horaModifica) {
		this.horaModifica = horaModifica;
	}

	public String getImagen() {
		return this.imagen;
	}

	public void setImagen(String imagen) {
		this.imagen = imagen;
	}

	public Integer getCodigoMedico() {
		return this.codigoMedico;
	}

	public void setCodigoMedico(Integer codigoMedico) {
		this.codigoMedico = codigoMedico;
	}

	public Set getPresupuestoOdontologicos() {
		return this.presupuestoOdontologicos;
	}

	public void setPresupuestoOdontologicos(Set presupuestoOdontologicos) {
		this.presupuestoOdontologicos = presupuestoOdontologicos;
	}

	public Set getHisConfDetPlanTs() {
		return this.hisConfDetPlanTs;
	}

	public void setHisConfDetPlanTs(Set hisConfDetPlanTs) {
		this.hisConfDetPlanTs = hisConfDetPlanTs;
	}

	public Set getDetPlanTratamientos() {
		return this.detPlanTratamientos;
	}

	public void setDetPlanTratamientos(Set detPlanTratamientos) {
		this.detPlanTratamientos = detPlanTratamientos;
	}

	public Set getProgramasHallazgoPiezas() {
		return this.programasHallazgoPiezas;
	}

	public void setProgramasHallazgoPiezas(Set programasHallazgoPiezas) {
		this.programasHallazgoPiezas = programasHallazgoPiezas;
	}

	public Set getHisConfPlanTratamientos() {
		return this.hisConfPlanTratamientos;
	}

	public void setHisConfPlanTratamientos(Set hisConfPlanTratamientos) {
		this.hisConfPlanTratamientos = hisConfPlanTratamientos;
	}

	public Set getLogDetPlanTratamientos() {
		return this.logDetPlanTratamientos;
	}

	public void setLogDetPlanTratamientos(Set logDetPlanTratamientos) {
		this.logDetPlanTratamientos = logDetPlanTratamientos;
	}

	public Set getConsentimientoInfoOdontos() {
		return this.consentimientoInfoOdontos;
	}

	public void setConsentimientoInfoOdontos(Set consentimientoInfoOdontos) {
		this.consentimientoInfoOdontos = consentimientoInfoOdontos;
	}

	public Set getLogPresupuestoOdonts() {
		return this.logPresupuestoOdonts;
	}

	public void setLogPresupuestoOdonts(Set logPresupuestoOdonts) {
		this.logPresupuestoOdonts = logPresupuestoOdonts;
	}

	public Set getLogPlanTratamientos() {
		return this.logPlanTratamientos;
	}

	public void setLogPlanTratamientos(Set logPlanTratamientos) {
		this.logPlanTratamientos = logPlanTratamientos;
	}

}
