package com.servinte.axioma.orm;

// Generated Jul 27, 2010 11:58:51 AM by Hibernate Tools 3.2.4.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * PresuContratoOdoImp generated by hbm2java
 */
public class PresuContratoOdoImp implements java.io.Serializable {

	private long codigoPk;
	private PresupuestoContratado presupuestoContratado;
	private Usuarios usuarios;
	private String clausulas;
	private String piePagina;
	private Date fechaModifica;
	private String horaModifica;
	private Set presuFirmasContratos = new HashSet(0);

	public PresuContratoOdoImp() {
	}

	public PresuContratoOdoImp(long codigoPk, Usuarios usuarios,
			Date fechaModifica, String horaModifica) {
		this.codigoPk = codigoPk;
		this.usuarios = usuarios;
		this.fechaModifica = fechaModifica;
		this.horaModifica = horaModifica;
	}

	public PresuContratoOdoImp(long codigoPk,
			PresupuestoContratado presupuestoContratado, Usuarios usuarios,
			String clausulas, String piePagina, Date fechaModifica,
			String horaModifica, Set presuFirmasContratos) {
		this.codigoPk = codigoPk;
		this.presupuestoContratado = presupuestoContratado;
		this.usuarios = usuarios;
		this.clausulas = clausulas;
		this.piePagina = piePagina;
		this.fechaModifica = fechaModifica;
		this.horaModifica = horaModifica;
		this.presuFirmasContratos = presuFirmasContratos;
	}

	public long getCodigoPk() {
		return this.codigoPk;
	}

	public void setCodigoPk(long codigoPk) {
		this.codigoPk = codigoPk;
	}

	public PresupuestoContratado getPresupuestoContratado() {
		return this.presupuestoContratado;
	}

	public void setPresupuestoContratado(
			PresupuestoContratado presupuestoContratado) {
		this.presupuestoContratado = presupuestoContratado;
	}

	public Usuarios getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(Usuarios usuarios) {
		this.usuarios = usuarios;
	}

	public String getClausulas() {
		return this.clausulas;
	}

	public void setClausulas(String clausulas) {
		this.clausulas = clausulas;
	}

	public String getPiePagina() {
		return this.piePagina;
	}

	public void setPiePagina(String piePagina) {
		this.piePagina = piePagina;
	}

	public Date getFechaModifica() {
		return this.fechaModifica;
	}

	public void setFechaModifica(Date fechaModifica) {
		this.fechaModifica = fechaModifica;
	}

	public String getHoraModifica() {
		return this.horaModifica;
	}

	public void setHoraModifica(String horaModifica) {
		this.horaModifica = horaModifica;
	}

	public Set getPresuFirmasContratos() {
		return this.presuFirmasContratos;
	}

	public void setPresuFirmasContratos(Set presuFirmasContratos) {
		this.presuFirmasContratos = presuFirmasContratos;
	}

}
