package com.servinte.axioma.orm;

// Generated Apr 7, 2010 3:58:52 PM by Hibernate Tools 3.2.5.Beta

import java.util.Date;

/**
 * ProcesoDevolucionRc generated by hbm2java
 */
public class ProcesoDevolucionRc implements java.io.Serializable {

	private ProcesoDevolucionRcId id;
	
	/**
	 *  Este atributo se documenta temporalmente mientras se resuelve el problema 
	 *  de la llave compuesta en la entidad RecibosCaja
	 *  private RecibosCaja recibosCaja;
	 */

	private Usuarios usuarios;
	private Date fecha;
	private String hora;
	private String idSesion;

	public ProcesoDevolucionRc() {
	}

	public ProcesoDevolucionRc(RecibosCaja recibosCaja, Usuarios usuarios,
			Date fecha, String hora, String idSesion) {
		//this.recibosCaja = recibosCaja;
		this.usuarios = usuarios;
		this.fecha = fecha;
		this.hora = hora;
		this.idSesion = idSesion;
	}

	public ProcesoDevolucionRcId getId() {
		return this.id;
	}

	public void setId(ProcesoDevolucionRcId id) {
		this.id = id;
	}

	/*
	public RecibosCaja getRecibosCaja() {
		return this.recibosCaja;
	}

	public void setRecibosCaja(RecibosCaja recibosCaja) {
		this.recibosCaja = recibosCaja;
	}
	*/

	public Usuarios getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(Usuarios usuarios) {
		this.usuarios = usuarios;
	}

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	public String getHora() {
		return this.hora;
	}

	public void setHora(String hora) {
		this.hora = hora;
	}

	public String getIdSesion() {
		return this.idSesion;
	}

	public void setIdSesion(String idSesion) {
		this.idSesion = idSesion;
	}

}
