package com.servinte.axioma.orm;

// Generated Apr 7, 2010 3:58:52 PM by Hibernate Tools 3.2.5.Beta

import java.math.BigDecimal;
import java.util.Date;

/**
 * ProgDescComConvxcont generated by hbm2java
 */
public class ProgDescComConvxcont implements java.io.Serializable {

	private long codigoPk;
	private DescComConvcont descComConvcont;
	private Programas programas;
	private BigDecimal porcentaje;
	private String usuarioModifica;
	private Date fechaModifica;
	private String horaModifica;
	private Date fechaVigencia;

	public ProgDescComConvxcont() {
	}

	public ProgDescComConvxcont(long codigoPk, DescComConvcont descComConvcont,
			Programas programas, BigDecimal porcentaje, String usuarioModifica,
			Date fechaModifica, String horaModifica) {
		this.codigoPk = codigoPk;
		this.descComConvcont = descComConvcont;
		this.programas = programas;
		this.porcentaje = porcentaje;
		this.usuarioModifica = usuarioModifica;
		this.fechaModifica = fechaModifica;
		this.horaModifica = horaModifica;
	}

	public ProgDescComConvxcont(long codigoPk, DescComConvcont descComConvcont,
			Programas programas, BigDecimal porcentaje, String usuarioModifica,
			Date fechaModifica, String horaModifica, Date fechaVigencia) {
		this.codigoPk = codigoPk;
		this.descComConvcont = descComConvcont;
		this.programas = programas;
		this.porcentaje = porcentaje;
		this.usuarioModifica = usuarioModifica;
		this.fechaModifica = fechaModifica;
		this.horaModifica = horaModifica;
		this.fechaVigencia = fechaVigencia;
	}

	public long getCodigoPk() {
		return this.codigoPk;
	}

	public void setCodigoPk(long codigoPk) {
		this.codigoPk = codigoPk;
	}

	public DescComConvcont getDescComConvcont() {
		return this.descComConvcont;
	}

	public void setDescComConvcont(DescComConvcont descComConvcont) {
		this.descComConvcont = descComConvcont;
	}

	public Programas getProgramas() {
		return this.programas;
	}

	public void setProgramas(Programas programas) {
		this.programas = programas;
	}

	public BigDecimal getPorcentaje() {
		return this.porcentaje;
	}

	public void setPorcentaje(BigDecimal porcentaje) {
		this.porcentaje = porcentaje;
	}

	public String getUsuarioModifica() {
		return this.usuarioModifica;
	}

	public void setUsuarioModifica(String usuarioModifica) {
		this.usuarioModifica = usuarioModifica;
	}

	public Date getFechaModifica() {
		return this.fechaModifica;
	}

	public void setFechaModifica(Date fechaModifica) {
		this.fechaModifica = fechaModifica;
	}

	public String getHoraModifica() {
		return this.horaModifica;
	}

	public void setHoraModifica(String horaModifica) {
		this.horaModifica = horaModifica;
	}

	public Date getFechaVigencia() {
		return this.fechaVigencia;
	}

	public void setFechaVigencia(Date fechaVigencia) {
		this.fechaVigencia = fechaVigencia;
	}

}
