package com.servinte.axioma.orm;

// Generated Dec 7, 2010 9:11:46 AM by Hibernate Tools 3.2.4.GA

/**
 * RegistroEntregaEntsubSolici generated by hbm2java
 */
public class RegistroEntregaEntsubSolici implements java.io.Serializable {

	private long codigoPk;
	private Solicitudes solicitudes;
	private RegistroEntregaEntSub registroEntregaEntSub;

	public RegistroEntregaEntsubSolici() {
	}

	public RegistroEntregaEntsubSolici(long codigoPk, Solicitudes solicitudes,
			RegistroEntregaEntSub registroEntregaEntSub) {
		this.codigoPk = codigoPk;
		this.solicitudes = solicitudes;
		this.registroEntregaEntSub = registroEntregaEntSub;
	}

	public long getCodigoPk() {
		return this.codigoPk;
	}

	public void setCodigoPk(long codigoPk) {
		this.codigoPk = codigoPk;
	}

	public Solicitudes getSolicitudes() {
		return this.solicitudes;
	}

	public void setSolicitudes(Solicitudes solicitudes) {
		this.solicitudes = solicitudes;
	}

	public RegistroEntregaEntSub getRegistroEntregaEntSub() {
		return this.registroEntregaEntSub;
	}

	public void setRegistroEntregaEntSub(
			RegistroEntregaEntSub registroEntregaEntSub) {
		this.registroEntregaEntSub = registroEntregaEntSub;
	}

}
