package com.servinte.axioma.orm;

// Generated Apr 7, 2010 3:58:52 PM by Hibernate Tools 3.2.5.Beta

import java.util.Date;

/**
 * SerIncluexcluEcont generated by hbm2java
 */
public class SerIncluexcluEcont implements java.io.Serializable {

	private long codigo;
	private ExcepIncluexcluContr excepIncluexcluContr;
	private Servicios servicios;
	private Usuarios usuarios;
	private char incluye;
	private Long cantidad;
	private Date fechaModifica;
	private String horaModifica;
	private Date fechaVigencia;

	public SerIncluexcluEcont() {
	}

	public SerIncluexcluEcont(long codigo,
			ExcepIncluexcluContr excepIncluexcluContr, Servicios servicios,
			Usuarios usuarios, char incluye, Date fechaModifica,
			String horaModifica, Date fechaVigencia) {
		this.codigo = codigo;
		this.excepIncluexcluContr = excepIncluexcluContr;
		this.servicios = servicios;
		this.usuarios = usuarios;
		this.incluye = incluye;
		this.fechaModifica = fechaModifica;
		this.horaModifica = horaModifica;
		this.fechaVigencia = fechaVigencia;
	}

	public SerIncluexcluEcont(long codigo,
			ExcepIncluexcluContr excepIncluexcluContr, Servicios servicios,
			Usuarios usuarios, char incluye, Long cantidad, Date fechaModifica,
			String horaModifica, Date fechaVigencia) {
		this.codigo = codigo;
		this.excepIncluexcluContr = excepIncluexcluContr;
		this.servicios = servicios;
		this.usuarios = usuarios;
		this.incluye = incluye;
		this.cantidad = cantidad;
		this.fechaModifica = fechaModifica;
		this.horaModifica = horaModifica;
		this.fechaVigencia = fechaVigencia;
	}

	public long getCodigo() {
		return this.codigo;
	}

	public void setCodigo(long codigo) {
		this.codigo = codigo;
	}

	public ExcepIncluexcluContr getExcepIncluexcluContr() {
		return this.excepIncluexcluContr;
	}

	public void setExcepIncluexcluContr(
			ExcepIncluexcluContr excepIncluexcluContr) {
		this.excepIncluexcluContr = excepIncluexcluContr;
	}

	public Servicios getServicios() {
		return this.servicios;
	}

	public void setServicios(Servicios servicios) {
		this.servicios = servicios;
	}

	public Usuarios getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(Usuarios usuarios) {
		this.usuarios = usuarios;
	}

	public char getIncluye() {
		return this.incluye;
	}

	public void setIncluye(char incluye) {
		this.incluye = incluye;
	}

	public Long getCantidad() {
		return this.cantidad;
	}

	public void setCantidad(Long cantidad) {
		this.cantidad = cantidad;
	}

	public Date getFechaModifica() {
		return this.fechaModifica;
	}

	public void setFechaModifica(Date fechaModifica) {
		this.fechaModifica = fechaModifica;
	}

	public String getHoraModifica() {
		return this.horaModifica;
	}

	public void setHoraModifica(String horaModifica) {
		this.horaModifica = horaModifica;
	}

	public Date getFechaVigencia() {
		return this.fechaVigencia;
	}

	public void setFechaVigencia(Date fechaVigencia) {
		this.fechaVigencia = fechaVigencia;
	}

}
