package com.servinte.axioma.orm;

// Generated 19/01/2012 07:35:02 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * TipoHallazgoCeoCop generated by hbm2java
 */
public class TipoHallazgoCeoCop implements java.io.Serializable {

	private long codigo;
	private String tipo;
	private Set hallazgosOdontologicoses = new HashSet(0);
	private Set historicoCopCeos = new HashSet(0);

	public TipoHallazgoCeoCop() {
	}

	public TipoHallazgoCeoCop(long codigo, String tipo) {
		this.codigo = codigo;
		this.tipo = tipo;
	}

	public TipoHallazgoCeoCop(long codigo, String tipo,
			Set hallazgosOdontologicoses, Set historicoCopCeos) {
		this.codigo = codigo;
		this.tipo = tipo;
		this.hallazgosOdontologicoses = hallazgosOdontologicoses;
		this.historicoCopCeos = historicoCopCeos;
	}

	public long getCodigo() {
		return this.codigo;
	}

	public void setCodigo(long codigo) {
		this.codigo = codigo;
	}

	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	public Set getHallazgosOdontologicoses() {
		return this.hallazgosOdontologicoses;
	}

	public void setHallazgosOdontologicoses(Set hallazgosOdontologicoses) {
		this.hallazgosOdontologicoses = hallazgosOdontologicoses;
	}

	public Set getHistoricoCopCeos() {
		return this.historicoCopCeos;
	}

	public void setHistoricoCopCeos(Set historicoCopCeos) {
		this.historicoCopCeos = historicoCopCeos;
	}

}
