package com.servinte.axioma.orm;

// Generated 18/07/2011 06:11:28 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * TiposMovAbonos generated by hbm2java
 */
public class TiposMovAbonos implements java.io.Serializable {

	private int codigo;
	private String nombre;
	private String operacion;
	private Set nombreMovAbonos = new HashSet(0);
	private Set movimientosAbonoses = new HashSet(0);

	public TiposMovAbonos() {
	}

	public TiposMovAbonos(int codigo, String nombre) {
		this.codigo = codigo;
		this.nombre = nombre;
	}

	public TiposMovAbonos(int codigo, String nombre, String operacion,
			Set nombreMovAbonos, Set movimientosAbonoses) {
		this.codigo = codigo;
		this.nombre = nombre;
		this.operacion = operacion;
		this.nombreMovAbonos = nombreMovAbonos;
		this.movimientosAbonoses = movimientosAbonoses;
	}

	public int getCodigo() {
		return this.codigo;
	}

	public void setCodigo(int codigo) {
		this.codigo = codigo;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getOperacion() {
		return this.operacion;
	}

	public void setOperacion(String operacion) {
		this.operacion = operacion;
	}

	public Set getNombreMovAbonos() {
		return this.nombreMovAbonos;
	}

	public void setNombreMovAbonos(Set nombreMovAbonos) {
		this.nombreMovAbonos = nombreMovAbonos;
	}

	public Set getMovimientosAbonoses() {
		return this.movimientosAbonoses;
	}

	public void setMovimientosAbonoses(Set movimientosAbonoses) {
		this.movimientosAbonoses = movimientosAbonoses;
	}

}
