package com.servinte.axioma.orm;

// Generated Apr 7, 2010 3:58:52 PM by Hibernate Tools 3.2.5.Beta

import java.util.HashSet;
import java.util.Set;

/**
 * TiposSerSol generated by hbm2java
 */
public class TiposSerSol implements java.io.Serializable {

	private int codigo;
	private Instituciones instituciones;
	private String nombre;
	private String activo;
	private Set autorizacioneses = new HashSet(0);

	public TiposSerSol() {
	}

	public TiposSerSol(int codigo, Instituciones instituciones, String nombre,
			String activo) {
		this.codigo = codigo;
		this.instituciones = instituciones;
		this.nombre = nombre;
		this.activo = activo;
	}

	public TiposSerSol(int codigo, Instituciones instituciones, String nombre,
			String activo, Set autorizacioneses) {
		this.codigo = codigo;
		this.instituciones = instituciones;
		this.nombre = nombre;
		this.activo = activo;
		this.autorizacioneses = autorizacioneses;
	}

	public int getCodigo() {
		return this.codigo;
	}

	public void setCodigo(int codigo) {
		this.codigo = codigo;
	}

	public Instituciones getInstituciones() {
		return this.instituciones;
	}

	public void setInstituciones(Instituciones instituciones) {
		this.instituciones = instituciones;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getActivo() {
		return this.activo;
	}

	public void setActivo(String activo) {
		this.activo = activo;
	}

	public Set getAutorizacioneses() {
		return this.autorizacioneses;
	}

	public void setAutorizacioneses(Set autorizacioneses) {
		this.autorizacioneses = autorizacioneses;
	}

}
