package com.servinte.axioma.orm;

// Generated 15/04/2010 03:20:47 PM by Hibernate Tools 3.2.5.Beta

import java.util.HashSet;
import java.util.Set;

/**
 * TiposTarjetaFinanciera generated by hbm2java
 */
public class TiposTarjetaFinanciera implements java.io.Serializable {

	private char codigo;
	private String descripcion;
	private Set tarjetasFinancierases = new HashSet(0);

	public TiposTarjetaFinanciera() {
	}

	public TiposTarjetaFinanciera(char codigo, String descripcion) {
		this.codigo = codigo;
		this.descripcion = descripcion;
	}

	public TiposTarjetaFinanciera(char codigo, String descripcion,
			Set tarjetasFinancierases) {
		this.codigo = codigo;
		this.descripcion = descripcion;
		this.tarjetasFinancierases = tarjetasFinancierases;
	}

	public char getCodigo() {
		return this.codigo;
	}

	public void setCodigo(char codigo) {
		this.codigo = codigo;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Set getTarjetasFinancierases() {
		return this.tarjetasFinancierases;
	}

	public void setTarjetasFinancierases(Set tarjetasFinancierases) {
		this.tarjetasFinancierases = tarjetasFinancierases;
	}

}
