package com.servinte.axioma.orm;

// Generated Jan 24, 2011 6:37:03 PM by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;

/**
 * TiposServicio generated by hbm2java
 */
public class TiposServicio implements java.io.Serializable {

	private String acronimo;
	private String nombre;
	private String descripcion;
	private boolean esQx;
	private boolean solicitar;
	private Set histoMontoAgrupServs = new HashSet(0);
	private Set tiposSerNaturalezas = new HashSet(0);
	private Set exCoberAgruSerEntSubs = new HashSet(0);
	private Set agruSerIncluexcluEconts = new HashSet(0);
	private Set cobAgrupServicioses = new HashSet(0);
	private Set agruSerDescComConvxconts = new HashSet(0);
	private Set especiServCueIngs = new HashSet(0);
	private Set montoAgrupacionServicioses = new HashSet(0);
	private Set agruSerExceTariConts = new HashSet(0);
	private Set agrupHonorariosPools = new HashSet(0);
	private Set agruSerExepCobConvxconts = new HashSet(0);
	private Set cargosDirectosHcs = new HashSet(0);
	private Set conceptPagPoolXConvs = new HashSet(0);
	private Set detAgruHonoraEspServs = new HashSet(0);
	private Set nivelAutorAgrServs = new HashSet(0);
	private Set agruSerIncluexcluCcs = new HashSet(0);
	private Set paqAgrupacionServicioses = new HashSet(0);

	public TiposServicio() {
	}

	public TiposServicio(String acronimo, String nombre, String descripcion,
			boolean esQx, boolean solicitar) {
		this.acronimo = acronimo;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.esQx = esQx;
		this.solicitar = solicitar;
	}

	public TiposServicio(String acronimo, String nombre, String descripcion,
			boolean esQx, boolean solicitar, Set histoMontoAgrupServs,
			Set tiposSerNaturalezas, Set exCoberAgruSerEntSubs,
			Set agruSerIncluexcluEconts, Set cobAgrupServicioses,
			Set agruSerDescComConvxconts, Set especiServCueIngs,
			Set montoAgrupacionServicioses, Set agruSerExceTariConts,
			Set agrupHonorariosPools, Set agruSerExepCobConvxconts,
			Set cargosDirectosHcs, Set conceptPagPoolXConvs,
			Set detAgruHonoraEspServs, Set nivelAutorAgrServs,
			Set agruSerIncluexcluCcs, Set paqAgrupacionServicioses) {
		this.acronimo = acronimo;
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.esQx = esQx;
		this.solicitar = solicitar;
		this.histoMontoAgrupServs = histoMontoAgrupServs;
		this.tiposSerNaturalezas = tiposSerNaturalezas;
		this.exCoberAgruSerEntSubs = exCoberAgruSerEntSubs;
		this.agruSerIncluexcluEconts = agruSerIncluexcluEconts;
		this.cobAgrupServicioses = cobAgrupServicioses;
		this.agruSerDescComConvxconts = agruSerDescComConvxconts;
		this.especiServCueIngs = especiServCueIngs;
		this.montoAgrupacionServicioses = montoAgrupacionServicioses;
		this.agruSerExceTariConts = agruSerExceTariConts;
		this.agrupHonorariosPools = agrupHonorariosPools;
		this.agruSerExepCobConvxconts = agruSerExepCobConvxconts;
		this.cargosDirectosHcs = cargosDirectosHcs;
		this.conceptPagPoolXConvs = conceptPagPoolXConvs;
		this.detAgruHonoraEspServs = detAgruHonoraEspServs;
		this.nivelAutorAgrServs = nivelAutorAgrServs;
		this.agruSerIncluexcluCcs = agruSerIncluexcluCcs;
		this.paqAgrupacionServicioses = paqAgrupacionServicioses;
	}

	public String getAcronimo() {
		return this.acronimo;
	}

	public void setAcronimo(String acronimo) {
		this.acronimo = acronimo;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public boolean isEsQx() {
		return this.esQx;
	}

	public void setEsQx(boolean esQx) {
		this.esQx = esQx;
	}

	public boolean isSolicitar() {
		return this.solicitar;
	}

	public void setSolicitar(boolean solicitar) {
		this.solicitar = solicitar;
	}

	public Set getHistoMontoAgrupServs() {
		return this.histoMontoAgrupServs;
	}

	public void setHistoMontoAgrupServs(Set histoMontoAgrupServs) {
		this.histoMontoAgrupServs = histoMontoAgrupServs;
	}

	public Set getTiposSerNaturalezas() {
		return this.tiposSerNaturalezas;
	}

	public void setTiposSerNaturalezas(Set tiposSerNaturalezas) {
		this.tiposSerNaturalezas = tiposSerNaturalezas;
	}

	public Set getExCoberAgruSerEntSubs() {
		return this.exCoberAgruSerEntSubs;
	}

	public void setExCoberAgruSerEntSubs(Set exCoberAgruSerEntSubs) {
		this.exCoberAgruSerEntSubs = exCoberAgruSerEntSubs;
	}

	public Set getAgruSerIncluexcluEconts() {
		return this.agruSerIncluexcluEconts;
	}

	public void setAgruSerIncluexcluEconts(Set agruSerIncluexcluEconts) {
		this.agruSerIncluexcluEconts = agruSerIncluexcluEconts;
	}

	public Set getCobAgrupServicioses() {
		return this.cobAgrupServicioses;
	}

	public void setCobAgrupServicioses(Set cobAgrupServicioses) {
		this.cobAgrupServicioses = cobAgrupServicioses;
	}

	public Set getAgruSerDescComConvxconts() {
		return this.agruSerDescComConvxconts;
	}

	public void setAgruSerDescComConvxconts(Set agruSerDescComConvxconts) {
		this.agruSerDescComConvxconts = agruSerDescComConvxconts;
	}

	public Set getEspeciServCueIngs() {
		return this.especiServCueIngs;
	}

	public void setEspeciServCueIngs(Set especiServCueIngs) {
		this.especiServCueIngs = especiServCueIngs;
	}

	public Set getMontoAgrupacionServicioses() {
		return this.montoAgrupacionServicioses;
	}

	public void setMontoAgrupacionServicioses(Set montoAgrupacionServicioses) {
		this.montoAgrupacionServicioses = montoAgrupacionServicioses;
	}

	public Set getAgruSerExceTariConts() {
		return this.agruSerExceTariConts;
	}

	public void setAgruSerExceTariConts(Set agruSerExceTariConts) {
		this.agruSerExceTariConts = agruSerExceTariConts;
	}

	public Set getAgrupHonorariosPools() {
		return this.agrupHonorariosPools;
	}

	public void setAgrupHonorariosPools(Set agrupHonorariosPools) {
		this.agrupHonorariosPools = agrupHonorariosPools;
	}

	public Set getAgruSerExepCobConvxconts() {
		return this.agruSerExepCobConvxconts;
	}

	public void setAgruSerExepCobConvxconts(Set agruSerExepCobConvxconts) {
		this.agruSerExepCobConvxconts = agruSerExepCobConvxconts;
	}

	public Set getCargosDirectosHcs() {
		return this.cargosDirectosHcs;
	}

	public void setCargosDirectosHcs(Set cargosDirectosHcs) {
		this.cargosDirectosHcs = cargosDirectosHcs;
	}

	public Set getConceptPagPoolXConvs() {
		return this.conceptPagPoolXConvs;
	}

	public void setConceptPagPoolXConvs(Set conceptPagPoolXConvs) {
		this.conceptPagPoolXConvs = conceptPagPoolXConvs;
	}

	public Set getDetAgruHonoraEspServs() {
		return this.detAgruHonoraEspServs;
	}

	public void setDetAgruHonoraEspServs(Set detAgruHonoraEspServs) {
		this.detAgruHonoraEspServs = detAgruHonoraEspServs;
	}

	public Set getNivelAutorAgrServs() {
		return this.nivelAutorAgrServs;
	}

	public void setNivelAutorAgrServs(Set nivelAutorAgrServs) {
		this.nivelAutorAgrServs = nivelAutorAgrServs;
	}

	public Set getAgruSerIncluexcluCcs() {
		return this.agruSerIncluexcluCcs;
	}

	public void setAgruSerIncluexcluCcs(Set agruSerIncluexcluCcs) {
		this.agruSerIncluexcluCcs = agruSerIncluexcluCcs;
	}

	public Set getPaqAgrupacionServicioses() {
		return this.paqAgrupacionServicioses;
	}

	public void setPaqAgrupacionServicioses(Set paqAgrupacionServicioses) {
		this.paqAgrupacionServicioses = paqAgrupacionServicioses;
	}

}
