package com.servinte.axioma.orm;

// Generated Apr 7, 2010 3:58:52 PM by Hibernate Tools 3.2.5.Beta

/**
 * TiposIdInstitucion generated by hbm2java
 */
public class TiposIdInstitucion implements java.io.Serializable {

	private TiposIdInstitucionId id;
	private TiposIdentificacion tiposIdentificacion;
	private Instituciones instituciones;
	private boolean esConsecutivo;
	private char excentoDeudor;

	public TiposIdInstitucion() {
	}

	public TiposIdInstitucion(TiposIdInstitucionId id,
			TiposIdentificacion tiposIdentificacion,
			Instituciones instituciones, boolean esConsecutivo,
			char excentoDeudor) {
		this.id = id;
		this.tiposIdentificacion = tiposIdentificacion;
		this.instituciones = instituciones;
		this.esConsecutivo = esConsecutivo;
		this.excentoDeudor = excentoDeudor;
	}

	public TiposIdInstitucionId getId() {
		return this.id;
	}

	public void setId(TiposIdInstitucionId id) {
		this.id = id;
	}

	public TiposIdentificacion getTiposIdentificacion() {
		return this.tiposIdentificacion;
	}

	public void setTiposIdentificacion(TiposIdentificacion tiposIdentificacion) {
		this.tiposIdentificacion = tiposIdentificacion;
	}

	public Instituciones getInstituciones() {
		return this.instituciones;
	}

	public void setInstituciones(Instituciones instituciones) {
		this.instituciones = instituciones;
	}

	public boolean isEsConsecutivo() {
		return this.esConsecutivo;
	}

	public void setEsConsecutivo(boolean esConsecutivo) {
		this.esConsecutivo = esConsecutivo;
	}

	public char getExcentoDeudor() {
		return this.excentoDeudor;
	}

	public void setExcentoDeudor(char excentoDeudor) {
		this.excentoDeudor = excentoDeudor;
	}

}
