package com.servinte.axioma.orm;

// Generated Jan 25, 2011 12:12:08 PM by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;

/**
 * UnidadMedida generated by hbm2java
 */
public class UnidadMedida implements java.io.Serializable {

	private String acronimo;
	private String nombre;
	private boolean unidosis;
	private boolean activo;
	private Set unidosisXArticulos = new HashSet(0);
	private Set articulos = new HashSet(0);

	public UnidadMedida() {
	}

	public UnidadMedida(String acronimo, String nombre, boolean unidosis,
			boolean activo) {
		this.acronimo = acronimo;
		this.nombre = nombre;
		this.unidosis = unidosis;
		this.activo = activo;
	}

	public UnidadMedida(String acronimo, String nombre, boolean unidosis,
			boolean activo, Set unidosisXArticulos, Set articulos) {
		this.acronimo = acronimo;
		this.nombre = nombre;
		this.unidosis = unidosis;
		this.activo = activo;
		this.unidosisXArticulos = unidosisXArticulos;
		this.articulos = articulos;
	}

	public String getAcronimo() {
		return this.acronimo;
	}

	public void setAcronimo(String acronimo) {
		this.acronimo = acronimo;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public boolean isUnidosis() {
		return this.unidosis;
	}

	public void setUnidosis(boolean unidosis) {
		this.unidosis = unidosis;
	}

	public boolean isActivo() {
		return this.activo;
	}

	public void setActivo(boolean activo) {
		this.activo = activo;
	}

	public Set getUnidosisXArticulos() {
		return this.unidosisXArticulos;
	}

	public void setUnidosisXArticulos(Set unidosisXArticulos) {
		this.unidosisXArticulos = unidosisXArticulos;
	}

	public Set getArticulos() {
		return this.articulos;
	}

	public void setArticulos(Set articulos) {
		this.articulos = articulos;
	}

}
