package com.servinte.axioma.orm;

// Generated 11/06/2011 11:20:57 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * UsuariosCapitados generated by hbm2java
 */
public class UsuariosCapitados implements java.io.Serializable {

	private long codigo;
	private Sexo sexo;
	private Barrios barrios;
	private Ciudades ciudades;
	private String numeroIdentificacion;
	private String tipoIdentificacion;
	private Date fechaNacimiento;
	private String primerNombre;
	private String segundoNombre;
	private String primerApellido;
	private String segundoApellido;
	private String direccion;
	private String telefono;
	private String email;
	private String localidad;
	private Set convUsuariosCapitadoses = new HashSet(0);

	public UsuariosCapitados() {
	}

	public UsuariosCapitados(long codigo, Sexo sexo,
			String numeroIdentificacion, String tipoIdentificacion,
			Date fechaNacimiento, String primerNombre, String primerApellido,
			String direccion) {
		this.codigo = codigo;
		this.sexo = sexo;
		this.numeroIdentificacion = numeroIdentificacion;
		this.tipoIdentificacion = tipoIdentificacion;
		this.fechaNacimiento = fechaNacimiento;
		this.primerNombre = primerNombre;
		this.primerApellido = primerApellido;
		this.direccion = direccion;
	}

	public UsuariosCapitados(long codigo, Sexo sexo, Barrios barrios,
			Ciudades ciudades, String numeroIdentificacion,
			String tipoIdentificacion, Date fechaNacimiento,
			String primerNombre, String segundoNombre, String primerApellido,
			String segundoApellido, String direccion, String telefono,
			String email, String localidad, Set convUsuariosCapitadoses) {
		this.codigo = codigo;
		this.sexo = sexo;
		this.barrios = barrios;
		this.ciudades = ciudades;
		this.numeroIdentificacion = numeroIdentificacion;
		this.tipoIdentificacion = tipoIdentificacion;
		this.fechaNacimiento = fechaNacimiento;
		this.primerNombre = primerNombre;
		this.segundoNombre = segundoNombre;
		this.primerApellido = primerApellido;
		this.segundoApellido = segundoApellido;
		this.direccion = direccion;
		this.telefono = telefono;
		this.email = email;
		this.localidad = localidad;
		this.convUsuariosCapitadoses = convUsuariosCapitadoses;
	}

	public long getCodigo() {
		return this.codigo;
	}

	public void setCodigo(long codigo) {
		this.codigo = codigo;
	}

	public Sexo getSexo() {
		return this.sexo;
	}

	public void setSexo(Sexo sexo) {
		this.sexo = sexo;
	}

	public Barrios getBarrios() {
		return this.barrios;
	}

	public void setBarrios(Barrios barrios) {
		this.barrios = barrios;
	}

	public Ciudades getCiudades() {
		return this.ciudades;
	}

	public void setCiudades(Ciudades ciudades) {
		this.ciudades = ciudades;
	}

	public String getNumeroIdentificacion() {
		return this.numeroIdentificacion;
	}

	public void setNumeroIdentificacion(String numeroIdentificacion) {
		this.numeroIdentificacion = numeroIdentificacion;
	}

	public String getTipoIdentificacion() {
		return this.tipoIdentificacion;
	}

	public void setTipoIdentificacion(String tipoIdentificacion) {
		this.tipoIdentificacion = tipoIdentificacion;
	}

	public Date getFechaNacimiento() {
		return this.fechaNacimiento;
	}

	public void setFechaNacimiento(Date fechaNacimiento) {
		this.fechaNacimiento = fechaNacimiento;
	}

	public String getPrimerNombre() {
		return this.primerNombre;
	}

	public void setPrimerNombre(String primerNombre) {
		this.primerNombre = primerNombre;
	}

	public String getSegundoNombre() {
		return this.segundoNombre;
	}

	public void setSegundoNombre(String segundoNombre) {
		this.segundoNombre = segundoNombre;
	}

	public String getPrimerApellido() {
		return this.primerApellido;
	}

	public void setPrimerApellido(String primerApellido) {
		this.primerApellido = primerApellido;
	}

	public String getSegundoApellido() {
		return this.segundoApellido;
	}

	public void setSegundoApellido(String segundoApellido) {
		this.segundoApellido = segundoApellido;
	}

	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getLocalidad() {
		return this.localidad;
	}

	public void setLocalidad(String localidad) {
		this.localidad = localidad;
	}

	public Set getConvUsuariosCapitadoses() {
		return this.convUsuariosCapitadoses;
	}

	public void setConvUsuariosCapitadoses(Set convUsuariosCapitadoses) {
		this.convUsuariosCapitadoses = convUsuariosCapitadoses;
	}

}
