package com.servinte.axioma.orm;

// Generated Apr 7, 2010 3:58:52 PM by Hibernate Tools 3.2.5.Beta

import java.util.Date;

/**
 * UsuariosEntidadSub generated by hbm2java
 */
public class UsuariosEntidadSub implements java.io.Serializable {

	private long consecutivo;
	private EntidadesSubcontratadas entidadesSubcontratadas;
	private Usuarios usuariosByUsuarioModifica;
	private Usuarios usuariosByUsuario;
	private Date fechaModifica;
	private String horaModifica;

	public UsuariosEntidadSub() {
	}

	public UsuariosEntidadSub(long consecutivo,
			EntidadesSubcontratadas entidadesSubcontratadas,
			Usuarios usuariosByUsuarioModifica, Date fechaModifica,
			String horaModifica) {
		this.consecutivo = consecutivo;
		this.entidadesSubcontratadas = entidadesSubcontratadas;
		this.usuariosByUsuarioModifica = usuariosByUsuarioModifica;
		this.fechaModifica = fechaModifica;
		this.horaModifica = horaModifica;
	}

	public UsuariosEntidadSub(long consecutivo,
			EntidadesSubcontratadas entidadesSubcontratadas,
			Usuarios usuariosByUsuarioModifica, Usuarios usuariosByUsuario,
			Date fechaModifica, String horaModifica) {
		this.consecutivo = consecutivo;
		this.entidadesSubcontratadas = entidadesSubcontratadas;
		this.usuariosByUsuarioModifica = usuariosByUsuarioModifica;
		this.usuariosByUsuario = usuariosByUsuario;
		this.fechaModifica = fechaModifica;
		this.horaModifica = horaModifica;
	}

	public long getConsecutivo() {
		return this.consecutivo;
	}

	public void setConsecutivo(long consecutivo) {
		this.consecutivo = consecutivo;
	}

	public EntidadesSubcontratadas getEntidadesSubcontratadas() {
		return this.entidadesSubcontratadas;
	}

	public void setEntidadesSubcontratadas(
			EntidadesSubcontratadas entidadesSubcontratadas) {
		this.entidadesSubcontratadas = entidadesSubcontratadas;
	}

	public Usuarios getUsuariosByUsuarioModifica() {
		return this.usuariosByUsuarioModifica;
	}

	public void setUsuariosByUsuarioModifica(Usuarios usuariosByUsuarioModifica) {
		this.usuariosByUsuarioModifica = usuariosByUsuarioModifica;
	}

	public Usuarios getUsuariosByUsuario() {
		return this.usuariosByUsuario;
	}

	public void setUsuariosByUsuario(Usuarios usuariosByUsuario) {
		this.usuariosByUsuario = usuariosByUsuario;
	}

	public Date getFechaModifica() {
		return this.fechaModifica;
	}

	public void setFechaModifica(Date fechaModifica) {
		this.fechaModifica = fechaModifica;
	}

	public String getHoraModifica() {
		return this.horaModifica;
	}

	public void setHoraModifica(String horaModifica) {
		this.horaModifica = horaModifica;
	}

}
