package com.servinte.axioma.orm;

// Generated Apr 7, 2010 3:58:52 PM by Hibernate Tools 3.2.5.Beta

/**
 * UsuariosInactivos generated by hbm2java
 */
public class UsuariosInactivos implements java.io.Serializable {

	private UsuariosInactivosId id;
	private Usuarios usuarios;
	private Instituciones instituciones;
	private String password;

	public UsuariosInactivos() {
	}

	public UsuariosInactivos(UsuariosInactivosId id, Usuarios usuarios,
			Instituciones instituciones) {
		this.id = id;
		this.usuarios = usuarios;
		this.instituciones = instituciones;
	}

	public UsuariosInactivos(UsuariosInactivosId id, Usuarios usuarios,
			Instituciones instituciones, String password) {
		this.id = id;
		this.usuarios = usuarios;
		this.instituciones = instituciones;
		this.password = password;
	}

	public UsuariosInactivosId getId() {
		return this.id;
	}

	public void setId(UsuariosInactivosId id) {
		this.id = id;
	}

	public Usuarios getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(Usuarios usuarios) {
		this.usuarios = usuarios;
	}

	public Instituciones getInstituciones() {
		return this.instituciones;
	}

	public void setInstituciones(Instituciones instituciones) {
		this.instituciones = instituciones;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

}
