package com.servinte.axioma.orm;

// Generated 21/07/2011 03:06:42 PM by Hibernate Tools 3.4.0.CR1

/**
 * ValDiagnosticos generated by hbm2java
 */
public class ValDiagnosticos implements java.io.Serializable {

	private ValDiagnosticosId id;
	private Diagnosticos diagnosticos;
	private Valoraciones valoraciones;
	private int numero;

	public ValDiagnosticos() {
	}

	public ValDiagnosticos(ValDiagnosticosId id, Diagnosticos diagnosticos,
			Valoraciones valoraciones, int numero) {
		this.id = id;
		this.diagnosticos = diagnosticos;
		this.valoraciones = valoraciones;
		this.numero = numero;
	}

	public ValDiagnosticosId getId() {
		return this.id;
	}

	public void setId(ValDiagnosticosId id) {
		this.id = id;
	}

	public Diagnosticos getDiagnosticos() {
		return this.diagnosticos;
	}

	public void setDiagnosticos(Diagnosticos diagnosticos) {
		this.diagnosticos = diagnosticos;
	}

	public Valoraciones getValoraciones() {
		return this.valoraciones;
	}

	public void setValoraciones(Valoraciones valoraciones) {
		this.valoraciones = valoraciones;
	}

	public int getNumero() {
		return this.numero;
	}

	public void setNumero(int numero) {
		this.numero = numero;
	}

}
