package com.servinte.axioma.orm;

// Generated 18/10/2012 04:00:07 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ValoracionCurva generated by hbm2java
 */
public class ValoracionCurva implements java.io.Serializable {

	private int id;
	private CurvaCrecimientoParametrizab curvaCrecimientoParametrizab;
	private Valoraciones valoraciones;
	private Date fechaCreacion;
	private Set historicoImagenPlantillas = new HashSet(0);

	public ValoracionCurva() {
	}

	public ValoracionCurva(int id) {
		this.id = id;
	}

	public ValoracionCurva(int id,
			CurvaCrecimientoParametrizab curvaCrecimientoParametrizab,
			Valoraciones valoraciones, Date fechaCreacion,
			Set historicoImagenPlantillas) {
		this.id = id;
		this.curvaCrecimientoParametrizab = curvaCrecimientoParametrizab;
		this.valoraciones = valoraciones;
		this.fechaCreacion = fechaCreacion;
		this.historicoImagenPlantillas = historicoImagenPlantillas;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public CurvaCrecimientoParametrizab getCurvaCrecimientoParametrizab() {
		return this.curvaCrecimientoParametrizab;
	}

	public void setCurvaCrecimientoParametrizab(
			CurvaCrecimientoParametrizab curvaCrecimientoParametrizab) {
		this.curvaCrecimientoParametrizab = curvaCrecimientoParametrizab;
	}

	public Valoraciones getValoraciones() {
		return this.valoraciones;
	}

	public void setValoraciones(Valoraciones valoraciones) {
		this.valoraciones = valoraciones;
	}

	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	public Set getHistoricoImagenPlantillas() {
		return this.historicoImagenPlantillas;
	}

	public void setHistoricoImagenPlantillas(Set historicoImagenPlantillas) {
		this.historicoImagenPlantillas = historicoImagenPlantillas;
	}

}
