package com.servinte.axioma.orm;

// Generated Apr 7, 2010 3:58:52 PM by Hibernate Tools 3.2.5.Beta

/**
 * ViewFinalidadesServ generated by hbm2java
 */
public class ViewFinalidadesServ implements java.io.Serializable {

	private ViewFinalidadesServId id;

	public ViewFinalidadesServ() {
	}

	public ViewFinalidadesServ(ViewFinalidadesServId id) {
		this.id = id;
	}

	public ViewFinalidadesServId getId() {
		return this.id;
	}

	public void setId(ViewFinalidadesServId id) {
		this.id = id;
	}

}
