package com.servinte.axioma.orm;

// Generated Apr 7, 2010 3:58:52 PM by Hibernate Tools 3.2.5.Beta

/**
 * ViewDetalleFacturacionHsuba generated by hbm2java
 */
public class ViewDetalleFacturacionHsuba implements java.io.Serializable {

	private ViewDetalleFacturacionHsubaId id;

	public ViewDetalleFacturacionHsuba() {
	}

	public ViewDetalleFacturacionHsuba(ViewDetalleFacturacionHsubaId id) {
		this.id = id;
	}

	public ViewDetalleFacturacionHsubaId getId() {
		return this.id;
	}

	public void setId(ViewDetalleFacturacionHsubaId id) {
		this.id = id;
	}

}
