package com.servinte.axioma.orm;

// Generated Apr 7, 2010 3:58:52 PM by Hibernate Tools 3.2.5.Beta

/**
 * VistaEquipoTonometriaId generated by hbm2java
 */
public class VistaEquipoTonometriaId implements java.io.Serializable {

	private Integer numeroSolicitud;
	private String od;
	private String os;
	private Integer equipoTonometria;
	private String nombreEquipo;

	public VistaEquipoTonometriaId() {
	}

	public VistaEquipoTonometriaId(Integer numeroSolicitud, String od,
			String os, Integer equipoTonometria, String nombreEquipo) {
		this.numeroSolicitud = numeroSolicitud;
		this.od = od;
		this.os = os;
		this.equipoTonometria = equipoTonometria;
		this.nombreEquipo = nombreEquipo;
	}

	public Integer getNumeroSolicitud() {
		return this.numeroSolicitud;
	}

	public void setNumeroSolicitud(Integer numeroSolicitud) {
		this.numeroSolicitud = numeroSolicitud;
	}

	public String getOd() {
		return this.od;
	}

	public void setOd(String od) {
		this.od = od;
	}

	public String getOs() {
		return this.os;
	}

	public void setOs(String os) {
		this.os = os;
	}

	public Integer getEquipoTonometria() {
		return this.equipoTonometria;
	}

	public void setEquipoTonometria(Integer equipoTonometria) {
		this.equipoTonometria = equipoTonometria;
	}

	public String getNombreEquipo() {
		return this.nombreEquipo;
	}

	public void setNombreEquipo(String nombreEquipo) {
		this.nombreEquipo = nombreEquipo;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof VistaEquipoTonometriaId))
			return false;
		VistaEquipoTonometriaId castOther = (VistaEquipoTonometriaId) other;

		return ((this.getNumeroSolicitud() == castOther.getNumeroSolicitud()) || (this
				.getNumeroSolicitud() != null
				&& castOther.getNumeroSolicitud() != null && this
				.getNumeroSolicitud().equals(castOther.getNumeroSolicitud())))
				&& ((this.getOd() == castOther.getOd()) || (this.getOd() != null
						&& castOther.getOd() != null && this.getOd().equals(
						castOther.getOd())))
				&& ((this.getOs() == castOther.getOs()) || (this.getOs() != null
						&& castOther.getOs() != null && this.getOs().equals(
						castOther.getOs())))
				&& ((this.getEquipoTonometria() == castOther
						.getEquipoTonometria()) || (this.getEquipoTonometria() != null
						&& castOther.getEquipoTonometria() != null && this
						.getEquipoTonometria().equals(
								castOther.getEquipoTonometria())))
				&& ((this.getNombreEquipo() == castOther.getNombreEquipo()) || (this
						.getNombreEquipo() != null
						&& castOther.getNombreEquipo() != null && this
						.getNombreEquipo().equals(castOther.getNombreEquipo())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getNumeroSolicitud() == null ? 0 : this.getNumeroSolicitud()
						.hashCode());
		result = 37 * result + (getOd() == null ? 0 : this.getOd().hashCode());
		result = 37 * result + (getOs() == null ? 0 : this.getOs().hashCode());
		result = 37
				* result
				+ (getEquipoTonometria() == null ? 0 : this
						.getEquipoTonometria().hashCode());
		result = 37
				* result
				+ (getNombreEquipo() == null ? 0 : this.getNombreEquipo()
						.hashCode());
		return result;
	}

}
