package com.servinte.axioma.orm;

// Generated Apr 7, 2010 3:58:52 PM by Hibernate Tools 3.2.5.Beta

/**
 * VistaSintomasOftalId generated by hbm2java
 */
public class VistaSintomasOftalId implements java.io.Serializable {

	private Integer numeroSolicitud;
	private Integer sintoma;
	private String nombreSintoma;
	private Integer localizacion;
	private String nombreLocalizacion;
	private Integer severidad;
	private String nombreSeveridad;
	private Integer tipoSintoma;
	private String nombreTipo;

	public VistaSintomasOftalId() {
	}

	public VistaSintomasOftalId(Integer numeroSolicitud, Integer sintoma,
			String nombreSintoma, Integer localizacion,
			String nombreLocalizacion, Integer severidad,
			String nombreSeveridad, Integer tipoSintoma, String nombreTipo) {
		this.numeroSolicitud = numeroSolicitud;
		this.sintoma = sintoma;
		this.nombreSintoma = nombreSintoma;
		this.localizacion = localizacion;
		this.nombreLocalizacion = nombreLocalizacion;
		this.severidad = severidad;
		this.nombreSeveridad = nombreSeveridad;
		this.tipoSintoma = tipoSintoma;
		this.nombreTipo = nombreTipo;
	}

	public Integer getNumeroSolicitud() {
		return this.numeroSolicitud;
	}

	public void setNumeroSolicitud(Integer numeroSolicitud) {
		this.numeroSolicitud = numeroSolicitud;
	}

	public Integer getSintoma() {
		return this.sintoma;
	}

	public void setSintoma(Integer sintoma) {
		this.sintoma = sintoma;
	}

	public String getNombreSintoma() {
		return this.nombreSintoma;
	}

	public void setNombreSintoma(String nombreSintoma) {
		this.nombreSintoma = nombreSintoma;
	}

	public Integer getLocalizacion() {
		return this.localizacion;
	}

	public void setLocalizacion(Integer localizacion) {
		this.localizacion = localizacion;
	}

	public String getNombreLocalizacion() {
		return this.nombreLocalizacion;
	}

	public void setNombreLocalizacion(String nombreLocalizacion) {
		this.nombreLocalizacion = nombreLocalizacion;
	}

	public Integer getSeveridad() {
		return this.severidad;
	}

	public void setSeveridad(Integer severidad) {
		this.severidad = severidad;
	}

	public String getNombreSeveridad() {
		return this.nombreSeveridad;
	}

	public void setNombreSeveridad(String nombreSeveridad) {
		this.nombreSeveridad = nombreSeveridad;
	}

	public Integer getTipoSintoma() {
		return this.tipoSintoma;
	}

	public void setTipoSintoma(Integer tipoSintoma) {
		this.tipoSintoma = tipoSintoma;
	}

	public String getNombreTipo() {
		return this.nombreTipo;
	}

	public void setNombreTipo(String nombreTipo) {
		this.nombreTipo = nombreTipo;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof VistaSintomasOftalId))
			return false;
		VistaSintomasOftalId castOther = (VistaSintomasOftalId) other;

		return ((this.getNumeroSolicitud() == castOther.getNumeroSolicitud()) || (this
				.getNumeroSolicitud() != null
				&& castOther.getNumeroSolicitud() != null && this
				.getNumeroSolicitud().equals(castOther.getNumeroSolicitud())))
				&& ((this.getSintoma() == castOther.getSintoma()) || (this
						.getSintoma() != null
						&& castOther.getSintoma() != null && this.getSintoma()
						.equals(castOther.getSintoma())))
				&& ((this.getNombreSintoma() == castOther.getNombreSintoma()) || (this
						.getNombreSintoma() != null
						&& castOther.getNombreSintoma() != null && this
						.getNombreSintoma()
						.equals(castOther.getNombreSintoma())))
				&& ((this.getLocalizacion() == castOther.getLocalizacion()) || (this
						.getLocalizacion() != null
						&& castOther.getLocalizacion() != null && this
						.getLocalizacion().equals(castOther.getLocalizacion())))
				&& ((this.getNombreLocalizacion() == castOther
						.getNombreLocalizacion()) || (this
						.getNombreLocalizacion() != null
						&& castOther.getNombreLocalizacion() != null && this
						.getNombreLocalizacion().equals(
								castOther.getNombreLocalizacion())))
				&& ((this.getSeveridad() == castOther.getSeveridad()) || (this
						.getSeveridad() != null
						&& castOther.getSeveridad() != null && this
						.getSeveridad().equals(castOther.getSeveridad())))
				&& ((this.getNombreSeveridad() == castOther
						.getNombreSeveridad()) || (this.getNombreSeveridad() != null
						&& castOther.getNombreSeveridad() != null && this
						.getNombreSeveridad().equals(
								castOther.getNombreSeveridad())))
				&& ((this.getTipoSintoma() == castOther.getTipoSintoma()) || (this
						.getTipoSintoma() != null
						&& castOther.getTipoSintoma() != null && this
						.getTipoSintoma().equals(castOther.getTipoSintoma())))
				&& ((this.getNombreTipo() == castOther.getNombreTipo()) || (this
						.getNombreTipo() != null
						&& castOther.getNombreTipo() != null && this
						.getNombreTipo().equals(castOther.getNombreTipo())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getNumeroSolicitud() == null ? 0 : this.getNumeroSolicitud()
						.hashCode());
		result = 37 * result
				+ (getSintoma() == null ? 0 : this.getSintoma().hashCode());
		result = 37
				* result
				+ (getNombreSintoma() == null ? 0 : this.getNombreSintoma()
						.hashCode());
		result = 37
				* result
				+ (getLocalizacion() == null ? 0 : this.getLocalizacion()
						.hashCode());
		result = 37
				* result
				+ (getNombreLocalizacion() == null ? 0 : this
						.getNombreLocalizacion().hashCode());
		result = 37 * result
				+ (getSeveridad() == null ? 0 : this.getSeveridad().hashCode());
		result = 37
				* result
				+ (getNombreSeveridad() == null ? 0 : this.getNombreSeveridad()
						.hashCode());
		result = 37
				* result
				+ (getTipoSintoma() == null ? 0 : this.getTipoSintoma()
						.hashCode());
		result = 37
				* result
				+ (getNombreTipo() == null ? 0 : this.getNombreTipo()
						.hashCode());
		return result;
	}

}
