package com.sysmedica.dao;

import java.sql.Connection;
import java.sql.ResultSet;

public interface FichaBrotesDao {

	public int insertarFicha(Connection con,
								String login,
								int estado,
							    
							    String sire,
								String loginUsuario,
							    int codigoFichaBrotes,
							    
							    int evento,
								String fechaNotificacion,
								String paisNotifica,
								int departamentoNotifica,
								int ciudadNotifica,
								String lugarNotifica,
								int unidadGeneradora,
								
								int pacientesGrupo1,
								int pacientesGrupo2,
								int pacientesGrupo3,
								int pacientesGrupo4,
								int pacientesGrupo5,
								int pacientesGrupo6,
								int probables,
								int confirmadosLaboratorio,
								int confirmadosClinica,
								int confirmadosNexo,
								int hombres,
								int mujeres,
								int vivos,
								int muertos,
								int departamentoProcedencia,
								int ciudadProcedencia,
								String lugarProcedencia,
								String nombreProfesional,
								String telefonoContacto,
								
								int muestraBiologica,
								String agenteEtiologico1,
								String alimentosImplicados,
								int muestraAlimentos,
								String agenteEtiologico2,
								String lugarConsumo,
								String observaciones,
								
								String fechaInvestigacion, 
								int muestraSuperficies,
								int estudioManipuladores, 
								int agenteBiologica1, 
								int agenteBiologica2, 
								int agenteBiologica3, 
								int agenteBiologica4, 
								int agenteAlimentos1, 
								int agenteAlimentos2, 
								int agenteAlimentos3, 
								int agenteAlimentos4, 
								int agenteSuperficies1, 
								int agenteSuperficies2, 
								int agenteSuperficies3, 
								int agenteSuperficies4, 
								int agenteManipuladores1,
								int agenteManipuladores2,
								int agenteManipuladores3,
								int agenteManipuladores4,
								int lugarConsumoImplicado,
								int factorDeterminante,
								int medidaSanitaria);
	
	
	public int modificarFicha(Connection con,
										String sire,
										String loginUsuario,
									    int codigoFichaBrotes,
									    int estado,
									    
									    int evento,
										String fechaNotificacion,
										String paisNotifica,
										int departamentoNotifica,
										int ciudadNotifica,
										String lugarNotifica,
										int unidadGeneradora,
										
										int pacientesGrupo1,
										int pacientesGrupo2,
										int pacientesGrupo3,
										int pacientesGrupo4,
										int pacientesGrupo5,
										int pacientesGrupo6,
										int probables,
										int confirmadosLaboratorio,
										int confirmadosClinica,
										int confirmadosNexo,
										int hombres,
										int mujeres,
										int vivos,
										int muertos,
										int departamentoProcedencia,
										int ciudadProcedencia,
										String lugarProcedencia,
										String nombreProfesional,
										String telefonoContacto,
										
										int muestraBiologica,
										String agenteEtiologico1,
										String alimentosImplicados,
										int muestraAlimentos,
										String agenteEtiologico2,
										String lugarConsumo,
										String observaciones,
										
										String fechaInvestigacion, 
										int muestraSuperficies,
										int estudioManipuladores, 
										int agenteBiologica1, 
										int agenteBiologica2, 
										int agenteBiologica3, 
										int agenteBiologica4, 
										int agenteAlimentos1, 
										int agenteAlimentos2, 
										int agenteAlimentos3, 
										int agenteAlimentos4, 
										int agenteSuperficies1, 
										int agenteSuperficies2, 
										int agenteSuperficies3, 
										int agenteSuperficies4, 
										int agenteManipuladores1,
										int agenteManipuladores2,
										int agenteManipuladores3,
										int agenteManipuladores4,
										int lugarConsumoImplicado,
										int factorDeterminante,
										int medidaSanitaria
									);
	
	
	
	public ResultSet consultaTodoFicha(Connection con, int codigo);
}
