package com.sysmedica.dao;

import java.sql.Connection;
import java.sql.ResultSet;

public interface FichaRubCongenitaDao {

	public int insertarFichaCompleta(Connection con,
								    		int numeroSolicitud,
											String login,
											int codigoPaciente,
											String codigoDiagnostico,
											int estado,
											int codigoAseguradora,
											String nombreProfesional,
										    
										    String sire,
											boolean notificar,
											
											int codigoFichaIntoxicacion,										    
										    String lugarProcedencia,
										    String fechaConsultaGeneral,
										    String fechaInicioSintomasGeneral,
										    int tipoCaso,
										    boolean hospitalizadoGeneral,
										    String fechaHospitalizacionGeneral,
										    boolean estaVivoGeneral,
										    String fechaDefuncion,
										    String lugarNoti,
										    int unidadGeneradora,
										    
										    int clasificacionInicial,
											String nombreTutor,
											String lugarNacimientoPaciente,
											int fuenteNotificacion,
											String nombreMadre,
											String edadMadre,
											int embarazos,
											int carneVacunacion,
											int vacunaRubeola,
											String numeroDosis,
											String fechaUltimaDosis,
											int rubeolaConfirmada,
											String semanasEmbarazo,
											int similarRubeola,
											String semanasEmbarazo2,
											int expuestaRubeola,
											String semanasEmbarazo3,
											String donde,
											int viajes,
											String semanasEmbarazo4,
											String dondeViajo,
											String apgar,
											int bajoPesoNacimiento,
											String peso,
											int pequenoEdadGesta,
											String semanasEdad,
											int cataratas,
											int glaucoma,
											int retinopatia,
											int otrosOjo,
											int arterioso,
											int estenosis,
											int otrosCorazon,
											int sordera,
											int otrosOido,
											int microCefalia,
											int sicomotor,
											int purpura,
											int hepatomegalia,
											int ictericia,
											int esplenomegalia,
											int osteopatia,
											int meningoencefalitis,
											int otrosGeneral,
											int examenesEspeciales,
											String examen,
											int anatomoPatologico,
											String examen2,
											int compatibleSrc,
											int dxFinal,
											String nombreInvestigador,
											String telefonoInvestigador,
										    
										    boolean activa,
										    String pais,
										    int areaProcedencia
										   );
	
	

	public int modificarFicha(Connection con,
										String sire,
										boolean notificar,
									    String loginUsuario,
									    int codigoFichaRubCongenita,
									    int codigoPaciente,
									    String codigoDiagnostico,
									    int codigoNotificacion,
									    int numeroSolicitud,
									    int estado,
									    
									    String lugarProcedencia,
									    String fechaConsultaGeneral,
									    String fechaInicioSintomasGeneral,
									    int tipoCaso,
									    boolean hospitalizadoGeneral,
									    String fechaHospitalizacionGeneral,
									    boolean estaVivoGeneral,
									    String fechaDefuncion,
									    String lugarNoti,
									    int unidadGeneradora,
									    
									    int clasificacionInicial,
										String nombreTutor,
										String lugarNacimientoPaciente,
										int fuenteNotificacion,
										String nombreMadre,
										String edadMadre,
										int embarazos,
										int carneVacunacion,
										int vacunaRubeola,
										String numeroDosis,
										String fechaUltimaDosis,
										int rubeolaConfirmada,
										String semanasEmbarazo,
										int similarRubeola,
										String semanasEmbarazo2,
										int expuestaRubeola,
										String semanasEmbarazo3,
										String donde,
										int viajes,
										String semanasEmbarazo4,
										String dondeViajo,
										String apgar,
										int bajoPesoNacimiento,
										String peso,
										int pequenoEdadGesta,
										String semanasEdad,
										int cataratas,
										int glaucoma,
										int retinopatia,
										int otrosOjo,
										int arterioso,
										int estenosis,
										int otrosCorazon,
										int sordera,
										int otrosOido,
										int microCefalia,
										int sicomotor,
										int purpura,
										int hepatomegalia,
										int ictericia,
										int esplenomegalia,
										int osteopatia,
										int meningoencefalitis,
										int otrosGeneral,
										int examenesEspeciales,
										String examen,
										int anatomoPatologico,
										String examen2,
										int compatibleSrc,
										int dxFinal,
										String nombreInvestigador,
										String telefonoInvestigador,
									    String pais,
									    int areaProcedencia
									    );
	
	
	
	public ResultSet consultaTodoFicha(Connection con, int codigo);
	
	
	public ResultSet consultarDatosPaciente(Connection con, int codigo, boolean empezarnuevo);
	
	
	public ResultSet consultarDatosLaboratorio(Connection con, int codigo);
}
