package com.servinte.axioma.orm;

// Generated Apr 7, 2010 3:58:52 PM by Hibernate Tools 3.2.5.Beta

/**
 * AdjuntosHistoriaAtencionesId generated by hbm2java
 */
public class AdjuntosHistoriaAtencionesId implements java.io.Serializable {

	private Integer cuenta;
	private String nombreOriginal;
	private String nombreArchivo;
	private int paciente;

	public AdjuntosHistoriaAtencionesId() {
	}

	public AdjuntosHistoriaAtencionesId(int paciente) {
		this.paciente = paciente;
	}

	public AdjuntosHistoriaAtencionesId(Integer cuenta, String nombreOriginal,
			String nombreArchivo, int paciente) {
		this.cuenta = cuenta;
		this.nombreOriginal = nombreOriginal;
		this.nombreArchivo = nombreArchivo;
		this.paciente = paciente;
	}

	public Integer getCuenta() {
		return this.cuenta;
	}

	public void setCuenta(Integer cuenta) {
		this.cuenta = cuenta;
	}

	public String getNombreOriginal() {
		return this.nombreOriginal;
	}

	public void setNombreOriginal(String nombreOriginal) {
		this.nombreOriginal = nombreOriginal;
	}

	public String getNombreArchivo() {
		return this.nombreArchivo;
	}

	public void setNombreArchivo(String nombreArchivo) {
		this.nombreArchivo = nombreArchivo;
	}

	public int getPaciente() {
		return this.paciente;
	}

	public void setPaciente(int paciente) {
		this.paciente = paciente;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AdjuntosHistoriaAtencionesId))
			return false;
		AdjuntosHistoriaAtencionesId castOther = (AdjuntosHistoriaAtencionesId) other;

		return ((this.getCuenta() == castOther.getCuenta()) || (this
				.getCuenta() != null
				&& castOther.getCuenta() != null && this.getCuenta().equals(
				castOther.getCuenta())))
				&& ((this.getNombreOriginal() == castOther.getNombreOriginal()) || (this
						.getNombreOriginal() != null
						&& castOther.getNombreOriginal() != null && this
						.getNombreOriginal().equals(
								castOther.getNombreOriginal())))
				&& ((this.getNombreArchivo() == castOther.getNombreArchivo()) || (this
						.getNombreArchivo() != null
						&& castOther.getNombreArchivo() != null && this
						.getNombreArchivo()
						.equals(castOther.getNombreArchivo())))
				&& (this.getPaciente() == castOther.getPaciente());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getCuenta() == null ? 0 : this.getCuenta().hashCode());
		result = 37
				* result
				+ (getNombreOriginal() == null ? 0 : this.getNombreOriginal()
						.hashCode());
		result = 37
				* result
				+ (getNombreArchivo() == null ? 0 : this.getNombreArchivo()
						.hashCode());
		result = 37 * result + this.getPaciente();
		return result;
	}

}
