package com.servinte.axioma.orm;

// Generated Feb 15, 2011 5:27:21 PM by Hibernate Tools 3.2.4.GA

import java.math.BigDecimal;

/**
 * AmparoXReclamar generated by hbm2java
 */
public class AmparoXReclamar implements java.io.Serializable {

	private long codigoReclamacion;
	private ReclamacionesAccEveFact reclamacionesAccEveFact;
	private BigDecimal totalFacAmpGastMedqx;
	private BigDecimal totalRecAmpGastMedqx;
	private BigDecimal totalFacAmpGastTransmov;
	private BigDecimal totalRecAmpGastTransmov;

	public AmparoXReclamar() {
	}

	public AmparoXReclamar(ReclamacionesAccEveFact reclamacionesAccEveFact) {
		this.reclamacionesAccEveFact = reclamacionesAccEveFact;
	}

	public AmparoXReclamar(ReclamacionesAccEveFact reclamacionesAccEveFact,
			BigDecimal totalFacAmpGastMedqx, BigDecimal totalRecAmpGastMedqx,
			BigDecimal totalFacAmpGastTransmov,
			BigDecimal totalRecAmpGastTransmov) {
		this.reclamacionesAccEveFact = reclamacionesAccEveFact;
		this.totalFacAmpGastMedqx = totalFacAmpGastMedqx;
		this.totalRecAmpGastMedqx = totalRecAmpGastMedqx;
		this.totalFacAmpGastTransmov = totalFacAmpGastTransmov;
		this.totalRecAmpGastTransmov = totalRecAmpGastTransmov;
	}

	public long getCodigoReclamacion() {
		return this.codigoReclamacion;
	}

	public void setCodigoReclamacion(long codigoReclamacion) {
		this.codigoReclamacion = codigoReclamacion;
	}

	public ReclamacionesAccEveFact getReclamacionesAccEveFact() {
		return this.reclamacionesAccEveFact;
	}

	public void setReclamacionesAccEveFact(
			ReclamacionesAccEveFact reclamacionesAccEveFact) {
		this.reclamacionesAccEveFact = reclamacionesAccEveFact;
	}

	public BigDecimal getTotalFacAmpGastMedqx() {
		return this.totalFacAmpGastMedqx;
	}

	public void setTotalFacAmpGastMedqx(BigDecimal totalFacAmpGastMedqx) {
		this.totalFacAmpGastMedqx = totalFacAmpGastMedqx;
	}

	public BigDecimal getTotalRecAmpGastMedqx() {
		return this.totalRecAmpGastMedqx;
	}

	public void setTotalRecAmpGastMedqx(BigDecimal totalRecAmpGastMedqx) {
		this.totalRecAmpGastMedqx = totalRecAmpGastMedqx;
	}

	public BigDecimal getTotalFacAmpGastTransmov() {
		return this.totalFacAmpGastTransmov;
	}

	public void setTotalFacAmpGastTransmov(BigDecimal totalFacAmpGastTransmov) {
		this.totalFacAmpGastTransmov = totalFacAmpGastTransmov;
	}

	public BigDecimal getTotalRecAmpGastTransmov() {
		return this.totalRecAmpGastTransmov;
	}

	public void setTotalRecAmpGastTransmov(BigDecimal totalRecAmpGastTransmov) {
		this.totalRecAmpGastTransmov = totalRecAmpGastTransmov;
	}

}
