package com.servinte.axioma.orm;

// Generated 4/05/2011 07:38:01 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * AntecedentesVarios generated by hbm2java
 */
public class AntecedentesVarios implements java.io.Serializable {

	private AntecedentesVariosId id;
	private Antecedentes antecedentes;
	private AntecedentesPacientes antecedentesPacientes;
	private Usuarios usuarios;
	private String descripcion;
	private Date fecha;
	//private Date hora; //FIXME el tipo de dato es diferente el postgres.
	private String hora;

	public AntecedentesVarios() {
	}

	public AntecedentesVarios(AntecedentesVariosId id,
			Antecedentes antecedentes,
			AntecedentesPacientes antecedentesPacientes, Usuarios usuarios,
			String descripcion, Date fecha, String hora) {
		this.id = id;
		this.antecedentes = antecedentes;
		this.antecedentesPacientes = antecedentesPacientes;
		this.usuarios = usuarios;
		this.descripcion = descripcion;
		this.fecha = fecha;
		this.hora = hora;
	}

	public AntecedentesVariosId getId() {
		return this.id;
	}

	public void setId(AntecedentesVariosId id) {
		this.id = id;
	}

	public Antecedentes getAntecedentes() {
		return this.antecedentes;
	}

	public void setAntecedentes(Antecedentes antecedentes) {
		this.antecedentes = antecedentes;
	}

	public AntecedentesPacientes getAntecedentesPacientes() {
		return this.antecedentesPacientes;
	}

	public void setAntecedentesPacientes(
			AntecedentesPacientes antecedentesPacientes) {
		this.antecedentesPacientes = antecedentesPacientes;
	}

	public Usuarios getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(Usuarios usuarios) {
		this.usuarios = usuarios;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	public String getHora() {
		return this.hora;
	}

	public void setHora(String hora) {
		this.hora = hora;
	}

}
