package com.servinte.axioma.orm;

// Generated Jan 25, 2011 12:12:08 PM by Hibernate Tools 3.2.4.GA

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * AutorizacionesEntSubArticu generated by hbm2java
 */
public class AutorizacionesEntSubArticu implements java.io.Serializable {

	private long codigoPk;
	private Contratos contratos;
	private UnidosisXArticulo unidosisXArticulo;
	private NivelAutorizacion nivelAutorizacion;
	private Articulo articulo;
	private AutorizacionesEntidadesSub autorizacionesEntidadesSub;
	private String dosis;
	private Integer frecuencia;
	private Long diasTratamiento;
	private String estado;
	private String via;
	private Integer nroDosisTotal;
	private BigDecimal valorTarifa;
	private String tipoFrecuencia;
	private Set autorizacionArticuloDespachos = new HashSet(0);

	public AutorizacionesEntSubArticu() {
	}

	public AutorizacionesEntSubArticu(long codigoPk, Articulo articulo,
			AutorizacionesEntidadesSub autorizacionesEntidadesSub, String estado) {
		this.codigoPk = codigoPk;
		this.articulo = articulo;
		this.autorizacionesEntidadesSub = autorizacionesEntidadesSub;
		this.estado = estado;
	}

	public AutorizacionesEntSubArticu(long codigoPk, Contratos contratos,
			UnidosisXArticulo unidosisXArticulo,
			NivelAutorizacion nivelAutorizacion, Articulo articulo,
			AutorizacionesEntidadesSub autorizacionesEntidadesSub,
			String dosis, Integer frecuencia, Long diasTratamiento,
			String estado, String via, Integer nroDosisTotal,
			BigDecimal valorTarifa, String tipoFrecuencia,
			Set autorizacionArticuloDespachos) {
		this.codigoPk = codigoPk;
		this.unidosisXArticulo = unidosisXArticulo;
		this.nivelAutorizacion = nivelAutorizacion;
		this.articulo = articulo;
		this.autorizacionesEntidadesSub = autorizacionesEntidadesSub;
		this.dosis = dosis;
		this.frecuencia = frecuencia;
		this.diasTratamiento = diasTratamiento;
		this.estado = estado;
		this.via = via;
		this.nroDosisTotal = nroDosisTotal;
		this.valorTarifa = valorTarifa;
		this.tipoFrecuencia = tipoFrecuencia;
		this.autorizacionArticuloDespachos = autorizacionArticuloDespachos;
	}

	public long getCodigoPk() {
		return this.codigoPk;
	}

	public void setCodigoPk(long codigoPk) {
		this.codigoPk = codigoPk;
	}

	public Contratos getContratos() {
		return this.contratos;
	}

	public void setContratos(Contratos contratos) {
		this.contratos = contratos;
	}


	public UnidosisXArticulo getUnidosisXArticulo() {
		return this.unidosisXArticulo;
	}

	public void setUnidosisXArticulo(UnidosisXArticulo unidosisXArticulo) {
		this.unidosisXArticulo = unidosisXArticulo;
	}

	public NivelAutorizacion getNivelAutorizacion() {
		return this.nivelAutorizacion;
	}

	public void setNivelAutorizacion(NivelAutorizacion nivelAutorizacion) {
		this.nivelAutorizacion = nivelAutorizacion;
	}

	public Articulo getArticulo() {
		return this.articulo;
	}

	public void setArticulo(Articulo articulo) {
		this.articulo = articulo;
	}

	public AutorizacionesEntidadesSub getAutorizacionesEntidadesSub() {
		return this.autorizacionesEntidadesSub;
	}

	public void setAutorizacionesEntidadesSub(
			AutorizacionesEntidadesSub autorizacionesEntidadesSub) {
		this.autorizacionesEntidadesSub = autorizacionesEntidadesSub;
	}

	public String getDosis() {
		return this.dosis;
	}

	public void setDosis(String dosis) {
		this.dosis = dosis;
	}

	public Integer getFrecuencia() {
		return this.frecuencia;
	}

	public void setFrecuencia(Integer frecuencia) {
		this.frecuencia = frecuencia;
	}

	public Long getDiasTratamiento() {
		return this.diasTratamiento;
	}

	public void setDiasTratamiento(Long diasTratamiento) {
		this.diasTratamiento = diasTratamiento;
	}

	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	public String getVia() {
		return this.via;
	}

	public void setVia(String via) {
		this.via = via;
	}

	public Integer getNroDosisTotal() {
		return this.nroDosisTotal;
	}

	public void setNroDosisTotal(Integer nroDosisTotal) {
		this.nroDosisTotal = nroDosisTotal;
	}

	public BigDecimal getValorTarifa() {
		return this.valorTarifa;
	}

	public void setValorTarifa(BigDecimal valorTarifa) {
		this.valorTarifa = valorTarifa;
	}

	public String getTipoFrecuencia() {
		return this.tipoFrecuencia;
	}

	public void setTipoFrecuencia(String tipoFrecuencia) {
		this.tipoFrecuencia = tipoFrecuencia;
	}

	public Set getAutorizacionArticuloDespachos() {
		return this.autorizacionArticuloDespachos;
	}

	public void setAutorizacionArticuloDespachos(
			Set autorizacionArticuloDespachos) {
		this.autorizacionArticuloDespachos = autorizacionArticuloDespachos;
	}

}
