package com.servinte.axioma.orm;

// Generated Feb 20, 2011 2:49:37 PM by Hibernate Tools 3.2.4.GA

import java.util.Date;

/**
 * AutorizacionesEntSubRips generated by hbm2java
 */
public class AutorizacionesEntSubRips implements java.io.Serializable {

	private long autorizacionEntidadSub;
	private AutorizacionesEntidadesSub autorizacionesEntidadesSub;
	private Usuarios usuarios;
	private Date fecha;
	private String hora;

	public AutorizacionesEntSubRips() {
	}

	public AutorizacionesEntSubRips(
			AutorizacionesEntidadesSub autorizacionesEntidadesSub,
			Usuarios usuarios, Date fecha, String hora) {
		this.autorizacionesEntidadesSub = autorizacionesEntidadesSub;
		this.usuarios = usuarios;
		this.fecha = fecha;
		this.hora = hora;
	}

	public long getAutorizacionEntidadSub() {
		return this.autorizacionEntidadSub;
	}

	public void setAutorizacionEntidadSub(long autorizacionEntidadSub) {
		this.autorizacionEntidadSub = autorizacionEntidadSub;
	}

	public AutorizacionesEntidadesSub getAutorizacionesEntidadesSub() {
		return this.autorizacionesEntidadesSub;
	}

	public void setAutorizacionesEntidadesSub(
			AutorizacionesEntidadesSub autorizacionesEntidadesSub) {
		this.autorizacionesEntidadesSub = autorizacionesEntidadesSub;
	}

	public Usuarios getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(Usuarios usuarios) {
		this.usuarios = usuarios;
	}

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	public String getHora() {
		return this.hora;
	}

	public void setHora(String hora) {
		this.hora = hora;
	}

}
