package com.servinte.axioma.orm;

// Generated Sep 13, 2010 5:03:24 PM by Hibernate Tools 3.2.4.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * BeneficiarioTarjetaCliente generated by hbm2java
 */
public class BeneficiarioTarjetaCliente implements java.io.Serializable {

	private long codigoPk;
	private Parentezco parentezco;
	private VentaTarjetaCliente ventaTarjetaCliente;
	private TiposTarjCliente tiposTarjCliente;
	private BeneficiarioTarjetaCliente beneficiarioTarjetaCliente;
	private Instituciones instituciones;
	private long serial;
	private String indicativoPrincipal;
	private String estadoTarjeta;
	private String indicadorAlidado;
	private Long alidadoOdontologico;
	private String observaciones;
	private Date fechaModifica;
	private String horaModifica;
	private String usuarioModifica;
	private Integer consecutivo;
	private String migrado;
	private String serialMigracion;
	private String numTarjeta;
	private Set beneficiarioTarjetaClientes = new HashSet(0);
	private BeneficiarioTcPaciente beneficiarioTcPaciente;

	public BeneficiarioTarjetaCliente() {
	}

	public BeneficiarioTarjetaCliente(long codigoPk,
			Instituciones instituciones, long serial,
			String indicativoPrincipal, String indicadorAlidado,
			Date fechaModifica, String horaModifica, String usuarioModifica) {
		this.codigoPk = codigoPk;
		this.instituciones = instituciones;
		this.serial = serial;
		this.indicativoPrincipal = indicativoPrincipal;
		this.indicadorAlidado = indicadorAlidado;
		this.fechaModifica = fechaModifica;
		this.horaModifica = horaModifica;
		this.usuarioModifica = usuarioModifica;
	}

	public BeneficiarioTarjetaCliente(long codigoPk, Parentezco parentezco,
			VentaTarjetaCliente ventaTarjetaCliente,
			TiposTarjCliente tiposTarjCliente,
			BeneficiarioTarjetaCliente beneficiarioTarjetaCliente,
			Instituciones instituciones, long serial,
			String indicativoPrincipal, String estadoTarjeta,
			String indicadorAlidado, Long alidadoOdontologico,
			String observaciones, Date fechaModifica, String horaModifica,
			String usuarioModifica, Integer consecutivo, String migrado,
			String serialMigracion, String numTarjeta,
			Set beneficiarioTarjetaClientes,
			BeneficiarioTcPaciente beneficiarioTcPaciente) {
		this.codigoPk = codigoPk;
		this.parentezco = parentezco;
		this.ventaTarjetaCliente = ventaTarjetaCliente;
		this.tiposTarjCliente = tiposTarjCliente;
		this.beneficiarioTarjetaCliente = beneficiarioTarjetaCliente;
		this.instituciones = instituciones;
		this.serial = serial;
		this.indicativoPrincipal = indicativoPrincipal;
		this.estadoTarjeta = estadoTarjeta;
		this.indicadorAlidado = indicadorAlidado;
		this.alidadoOdontologico = alidadoOdontologico;
		this.observaciones = observaciones;
		this.fechaModifica = fechaModifica;
		this.horaModifica = horaModifica;
		this.usuarioModifica = usuarioModifica;
		this.consecutivo = consecutivo;
		this.migrado = migrado;
		this.serialMigracion = serialMigracion;
		this.numTarjeta = numTarjeta;
		this.beneficiarioTarjetaClientes = beneficiarioTarjetaClientes;
		this.beneficiarioTcPaciente = beneficiarioTcPaciente;
	}

	public long getCodigoPk() {
		return this.codigoPk;
	}

	public void setCodigoPk(long codigoPk) {
		this.codigoPk = codigoPk;
	}

	public Parentezco getParentezco() {
		return this.parentezco;
	}

	public void setParentezco(Parentezco parentezco) {
		this.parentezco = parentezco;
	}

	public VentaTarjetaCliente getVentaTarjetaCliente() {
		return this.ventaTarjetaCliente;
	}

	public void setVentaTarjetaCliente(VentaTarjetaCliente ventaTarjetaCliente) {
		this.ventaTarjetaCliente = ventaTarjetaCliente;
	}

	public TiposTarjCliente getTiposTarjCliente() {
		return this.tiposTarjCliente;
	}

	public void setTiposTarjCliente(TiposTarjCliente tiposTarjCliente) {
		this.tiposTarjCliente = tiposTarjCliente;
	}

	public BeneficiarioTarjetaCliente getBeneficiarioTarjetaCliente() {
		return this.beneficiarioTarjetaCliente;
	}

	public void setBeneficiarioTarjetaCliente(
			BeneficiarioTarjetaCliente beneficiarioTarjetaCliente) {
		this.beneficiarioTarjetaCliente = beneficiarioTarjetaCliente;
	}

	public Instituciones getInstituciones() {
		return this.instituciones;
	}

	public void setInstituciones(Instituciones instituciones) {
		this.instituciones = instituciones;
	}

	public long getSerial() {
		return this.serial;
	}

	public void setSerial(long serial) {
		this.serial = serial;
	}

	public String getIndicativoPrincipal() {
		return this.indicativoPrincipal;
	}

	public void setIndicativoPrincipal(String indicativoPrincipal) {
		this.indicativoPrincipal = indicativoPrincipal;
	}

	public String getEstadoTarjeta() {
		return this.estadoTarjeta;
	}

	public void setEstadoTarjeta(String estadoTarjeta) {
		this.estadoTarjeta = estadoTarjeta;
	}

	public String getIndicadorAlidado() {
		return this.indicadorAlidado;
	}

	public void setIndicadorAlidado(String indicadorAlidado) {
		this.indicadorAlidado = indicadorAlidado;
	}

	public Long getAlidadoOdontologico() {
		return this.alidadoOdontologico;
	}

	public void setAlidadoOdontologico(Long alidadoOdontologico) {
		this.alidadoOdontologico = alidadoOdontologico;
	}

	public String getObservaciones() {
		return this.observaciones;
	}

	public void setObservaciones(String observaciones) {
		this.observaciones = observaciones;
	}

	public Date getFechaModifica() {
		return this.fechaModifica;
	}

	public void setFechaModifica(Date fechaModifica) {
		this.fechaModifica = fechaModifica;
	}

	public String getHoraModifica() {
		return this.horaModifica;
	}

	public void setHoraModifica(String horaModifica) {
		this.horaModifica = horaModifica;
	}

	public String getUsuarioModifica() {
		return this.usuarioModifica;
	}

	public void setUsuarioModifica(String usuarioModifica) {
		this.usuarioModifica = usuarioModifica;
	}

	public Integer getConsecutivo() {
		return this.consecutivo;
	}

	public void setConsecutivo(Integer consecutivo) {
		this.consecutivo = consecutivo;
	}

	public String getMigrado() {
		return this.migrado;
	}

	public void setMigrado(String migrado) {
		this.migrado = migrado;
	}

	public String getSerialMigracion() {
		return this.serialMigracion;
	}

	public void setSerialMigracion(String serialMigracion) {
		this.serialMigracion = serialMigracion;
	}

	public String getNumTarjeta() {
		return this.numTarjeta;
	}

	public void setNumTarjeta(String numTarjeta) {
		this.numTarjeta = numTarjeta;
	}

	public Set getBeneficiarioTarjetaClientes() {
		return this.beneficiarioTarjetaClientes;
	}

	public void setBeneficiarioTarjetaClientes(Set beneficiarioTarjetaClientes) {
		this.beneficiarioTarjetaClientes = beneficiarioTarjetaClientes;
	}

	public BeneficiarioTcPaciente getBeneficiarioTcPaciente() {
		return this.beneficiarioTcPaciente;
	}

	public void setBeneficiarioTcPaciente(
			BeneficiarioTcPaciente beneficiarioTcPaciente) {
		this.beneficiarioTcPaciente = beneficiarioTcPaciente;
	}

}
