package com.servinte.axioma.orm;

// Generated Apr 7, 2010 3:58:52 PM by Hibernate Tools 3.2.5.Beta

import java.util.HashSet;
import java.util.Set;

/**
 * CajasCajeros generated by hbm2java
 */
public class CajasCajeros implements java.io.Serializable {

	private CajasCajerosId id;
	private Cajas cajas;
	private Usuarios usuarios;
	private Instituciones instituciones;
	private boolean activo;
	private String aperturaTurno;
	private Set devolRecibosCajas = new HashSet(0);
	private Set recibosCajas = new HashSet(0);

	public CajasCajeros() {
	}

	public CajasCajeros(CajasCajerosId id, Cajas cajas, Usuarios usuarios,
			Instituciones instituciones, boolean activo) {
		this.id = id;
		this.cajas = cajas;
		this.usuarios = usuarios;
		this.instituciones = instituciones;
		this.activo = activo;
	}

	public CajasCajeros(CajasCajerosId id, Cajas cajas, Usuarios usuarios,
			Instituciones instituciones, boolean activo, String aperturaTurno,
			Set devolRecibosCajas, Set recibosCajas) {
		this.id = id;
		this.cajas = cajas;
		this.usuarios = usuarios;
		this.instituciones = instituciones;
		this.activo = activo;
		this.aperturaTurno = aperturaTurno;
		this.devolRecibosCajas = devolRecibosCajas;
		this.recibosCajas = recibosCajas;
	}

	public CajasCajerosId getId() {
		return this.id;
	}

	public void setId(CajasCajerosId id) {
		this.id = id;
	}

	public Cajas getCajas() {
		return this.cajas;
	}

	public void setCajas(Cajas cajas) {
		this.cajas = cajas;
	}

	public Usuarios getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(Usuarios usuarios) {
		this.usuarios = usuarios;
	}

	public Instituciones getInstituciones() {
		return this.instituciones;
	}

	public void setInstituciones(Instituciones instituciones) {
		this.instituciones = instituciones;
	}

	public boolean isActivo() {
		return this.activo;
	}

	public void setActivo(boolean activo) {
		this.activo = activo;
	}

	public String getAperturaTurno() {
		return this.aperturaTurno;
	}

	public void setAperturaTurno(String aperturaTurno) {
		this.aperturaTurno = aperturaTurno;
	}

	public Set getDevolRecibosCajas() {
		return this.devolRecibosCajas;
	}

	public void setDevolRecibosCajas(Set devolRecibosCajas) {
		this.devolRecibosCajas = devolRecibosCajas;
	}

	public Set getRecibosCajas() {
		return this.recibosCajas;
	}

	public void setRecibosCajas(Set recibosCajas) {
		this.recibosCajas = recibosCajas;
	}

}
