package com.servinte.axioma.orm;

// Generated Apr 7, 2010 3:58:52 PM by Hibernate Tools 3.2.5.Beta

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * CategoriasAtencion generated by hbm2java
 */
public class CategoriasAtencion implements java.io.Serializable {

	private long codigo;
	private Usuarios usuarios;
	private Instituciones instituciones;
	private String descripcion;
	private Date fechaModifica;
	private String horaModifica;
	private Set centroAtencions = new HashSet(0);
	private Set logDetPromocionesOdos = new HashSet(0);
	private Set detPromocionesOdos = new HashSet(0);

	public CategoriasAtencion() {
	}

	public CategoriasAtencion(long codigo, Usuarios usuarios,
			Instituciones instituciones, String descripcion,
			Date fechaModifica, String horaModifica) {
		this.codigo = codigo;
		this.usuarios = usuarios;
		this.instituciones = instituciones;
		this.descripcion = descripcion;
		this.fechaModifica = fechaModifica;
		this.horaModifica = horaModifica;
	}

	public CategoriasAtencion(long codigo, Usuarios usuarios,
			Instituciones instituciones, String descripcion,
			Date fechaModifica, String horaModifica, Set centroAtencions,
			Set logDetPromocionesOdos, Set detPromocionesOdos) {
		this.codigo = codigo;
		this.usuarios = usuarios;
		this.instituciones = instituciones;
		this.descripcion = descripcion;
		this.fechaModifica = fechaModifica;
		this.horaModifica = horaModifica;
		this.centroAtencions = centroAtencions;
		this.logDetPromocionesOdos = logDetPromocionesOdos;
		this.detPromocionesOdos = detPromocionesOdos;
	}

	public long getCodigo() {
		return this.codigo;
	}

	public void setCodigo(long codigo) {
		this.codigo = codigo;
	}

	public Usuarios getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(Usuarios usuarios) {
		this.usuarios = usuarios;
	}

	public Instituciones getInstituciones() {
		return this.instituciones;
	}

	public void setInstituciones(Instituciones instituciones) {
		this.instituciones = instituciones;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Date getFechaModifica() {
		return this.fechaModifica;
	}

	public void setFechaModifica(Date fechaModifica) {
		this.fechaModifica = fechaModifica;
	}

	public String getHoraModifica() {
		return this.horaModifica;
	}

	public void setHoraModifica(String horaModifica) {
		this.horaModifica = horaModifica;
	}

	public Set getCentroAtencions() {
		return this.centroAtencions;
	}

	public void setCentroAtencions(Set centroAtencions) {
		this.centroAtencions = centroAtencions;
	}

	public Set getLogDetPromocionesOdos() {
		return this.logDetPromocionesOdos;
	}

	public void setLogDetPromocionesOdos(Set logDetPromocionesOdos) {
		this.logDetPromocionesOdos = logDetPromocionesOdos;
	}

	public Set getDetPromocionesOdos() {
		return this.detPromocionesOdos;
	}

	public void setDetPromocionesOdos(Set detPromocionesOdos) {
		this.detPromocionesOdos = detPromocionesOdos;
	}

}
