package com.servinte.axioma.orm;

// Generated Jul 27, 2010 11:58:51 AM by Hibernate Tools 3.2.4.GA

/**
 * CierreCajaXReciboCaja generated by hbm2java
 */
public class CierreCajaXReciboCaja implements java.io.Serializable {

	private long codigoPk;
	private RecibosCaja recibosCaja;
	private MovimientosCaja movimientosCaja;

	public CierreCajaXReciboCaja() {
	}

	public CierreCajaXReciboCaja(long codigoPk, RecibosCaja recibosCaja,
			MovimientosCaja movimientosCaja) {
		this.codigoPk = codigoPk;
		this.recibosCaja = recibosCaja;
		this.movimientosCaja = movimientosCaja;
	}

	public long getCodigoPk() {
		return this.codigoPk;
	}

	public void setCodigoPk(long codigoPk) {
		this.codigoPk = codigoPk;
	}

	public RecibosCaja getRecibosCaja() {
		return this.recibosCaja;
	}

	public void setRecibosCaja(RecibosCaja recibosCaja) {
		this.recibosCaja = recibosCaja;
	}

	public MovimientosCaja getMovimientosCaja() {
		return this.movimientosCaja;
	}

	public void setMovimientosCaja(MovimientosCaja movimientosCaja) {
		this.movimientosCaja = movimientosCaja;
	}

}
