package com.servinte.axioma.orm;

// Generated Apr 7, 2010 3:58:52 PM by Hibernate Tools 3.2.5.Beta

/**
 * CobAccidentesTransitoId generated by hbm2java
 */
public class CobAccidentesTransitoId implements java.io.Serializable {

	private int institucion;
	private int responsable;

	public CobAccidentesTransitoId() {
	}

	public CobAccidentesTransitoId(int institucion, int responsable) {
		this.institucion = institucion;
		this.responsable = responsable;
	}

	public int getInstitucion() {
		return this.institucion;
	}

	public void setInstitucion(int institucion) {
		this.institucion = institucion;
	}

	public int getResponsable() {
		return this.responsable;
	}

	public void setResponsable(int responsable) {
		this.responsable = responsable;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CobAccidentesTransitoId))
			return false;
		CobAccidentesTransitoId castOther = (CobAccidentesTransitoId) other;

		return (this.getInstitucion() == castOther.getInstitucion())
				&& (this.getResponsable() == castOther.getResponsable());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getInstitucion();
		result = 37 * result + this.getResponsable();
		return result;
	}

}
