package com.servinte.axioma.orm;

// Generated Apr 7, 2010 3:58:52 PM by Hibernate Tools 3.2.5.Beta

import java.util.Date;

/**
 * CtTurnoObservacion generated by hbm2java
 */
public class CtTurnoObservacion implements java.io.Serializable {

	private int codigo;
	private TipoObservacion tipoObservacion;
	private CtTurno ctTurno;
	private Usuarios usuarios;
	private String ctobservacion;
	private Date fecha;
	private Date hora;
	private CtTurnoNovedad ctTurnoNovedad;

	public CtTurnoObservacion() {
	}

	public CtTurnoObservacion(int codigo, TipoObservacion tipoObservacion,
			CtTurno ctTurno, Usuarios usuarios, String ctobservacion,
			Date fecha, Date hora) {
		this.codigo = codigo;
		this.tipoObservacion = tipoObservacion;
		this.ctTurno = ctTurno;
		this.usuarios = usuarios;
		this.ctobservacion = ctobservacion;
		this.fecha = fecha;
		this.hora = hora;
	}

	public CtTurnoObservacion(int codigo, TipoObservacion tipoObservacion,
			CtTurno ctTurno, Usuarios usuarios, String ctobservacion,
			Date fecha, Date hora, CtTurnoNovedad ctTurnoNovedad) {
		this.codigo = codigo;
		this.tipoObservacion = tipoObservacion;
		this.ctTurno = ctTurno;
		this.usuarios = usuarios;
		this.ctobservacion = ctobservacion;
		this.fecha = fecha;
		this.hora = hora;
		this.ctTurnoNovedad = ctTurnoNovedad;
	}

	public int getCodigo() {
		return this.codigo;
	}

	public void setCodigo(int codigo) {
		this.codigo = codigo;
	}

	public TipoObservacion getTipoObservacion() {
		return this.tipoObservacion;
	}

	public void setTipoObservacion(TipoObservacion tipoObservacion) {
		this.tipoObservacion = tipoObservacion;
	}

	public CtTurno getCtTurno() {
		return this.ctTurno;
	}

	public void setCtTurno(CtTurno ctTurno) {
		this.ctTurno = ctTurno;
	}

	public Usuarios getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(Usuarios usuarios) {
		this.usuarios = usuarios;
	}

	public String getCtobservacion() {
		return this.ctobservacion;
	}

	public void setCtobservacion(String ctobservacion) {
		this.ctobservacion = ctobservacion;
	}

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	public Date getHora() {
		return this.hora;
	}

	public void setHora(Date hora) {
		this.hora = hora;
	}

	public CtTurnoNovedad getCtTurnoNovedad() {
		return this.ctTurnoNovedad;
	}

	public void setCtTurnoNovedad(CtTurnoNovedad ctTurnoNovedad) {
		this.ctTurnoNovedad = ctTurnoNovedad;
	}

}
