package com.servinte.axioma.orm;

// Generated Apr 7, 2010 3:58:52 PM by Hibernate Tools 3.2.5.Beta

/**
 * CtTurnoNovedad generated by hbm2java
 */
public class CtTurnoNovedad implements java.io.Serializable {

	private int codigoObservacion;
	private CtTurnoObservacion ctTurnoObservacion;
	private Novedad novedad;

	public CtTurnoNovedad() {
	}

	public CtTurnoNovedad(CtTurnoObservacion ctTurnoObservacion, Novedad novedad) {
		this.ctTurnoObservacion = ctTurnoObservacion;
		this.novedad = novedad;
	}

	public int getCodigoObservacion() {
		return this.codigoObservacion;
	}

	public void setCodigoObservacion(int codigoObservacion) {
		this.codigoObservacion = codigoObservacion;
	}

	public CtTurnoObservacion getCtTurnoObservacion() {
		return this.ctTurnoObservacion;
	}

	public void setCtTurnoObservacion(CtTurnoObservacion ctTurnoObservacion) {
		this.ctTurnoObservacion = ctTurnoObservacion;
	}

	public Novedad getNovedad() {
		return this.novedad;
	}

	public void setNovedad(Novedad novedad) {
		this.novedad = novedad;
	}

}
