package com.servinte.axioma.orm;

// Generated Apr 7, 2010 3:58:52 PM by Hibernate Tools 3.2.5.Beta

/**
 * DatosTemporalesSolicitud generated by hbm2java
 */
public class DatosTemporalesSolicitud implements java.io.Serializable {

	private DatosTemporalesSolicitudId id;

	public DatosTemporalesSolicitud() {
	}

	public DatosTemporalesSolicitud(DatosTemporalesSolicitudId id) {
		this.id = id;
	}

	public DatosTemporalesSolicitudId getId() {
		return this.id;
	}

	public void setId(DatosTemporalesSolicitudId id) {
		this.id = id;
	}

}
