package com.servinte.axioma.orm;

// Generated Apr 7, 2010 3:58:52 PM by Hibernate Tools 3.2.5.Beta

import java.math.BigDecimal;
import java.util.Date;

/**
 * DetAsociosDetFactura generated by hbm2java
 */
public class DetAsociosDetFactura implements java.io.Serializable {

	private long codigo;
	private Usuarios usuarios;
	private AsociosDetFactura asociosDetFactura;
	private int articulo;
	private int cantidad;
	private BigDecimal valorUnitario;
	private BigDecimal valorTotal;
	private Date fechaModifica;
	private String horaModifica;

	public DetAsociosDetFactura() {
	}

	public DetAsociosDetFactura(long codigo, Usuarios usuarios,
			AsociosDetFactura asociosDetFactura, int articulo, int cantidad,
			BigDecimal valorUnitario, BigDecimal valorTotal,
			Date fechaModifica, String horaModifica) {
		this.codigo = codigo;
		this.usuarios = usuarios;
		this.asociosDetFactura = asociosDetFactura;
		this.articulo = articulo;
		this.cantidad = cantidad;
		this.valorUnitario = valorUnitario;
		this.valorTotal = valorTotal;
		this.fechaModifica = fechaModifica;
		this.horaModifica = horaModifica;
	}

	public long getCodigo() {
		return this.codigo;
	}

	public void setCodigo(long codigo) {
		this.codigo = codigo;
	}

	public Usuarios getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(Usuarios usuarios) {
		this.usuarios = usuarios;
	}

	public AsociosDetFactura getAsociosDetFactura() {
		return this.asociosDetFactura;
	}

	public void setAsociosDetFactura(AsociosDetFactura asociosDetFactura) {
		this.asociosDetFactura = asociosDetFactura;
	}

	public int getArticulo() {
		return this.articulo;
	}

	public void setArticulo(int articulo) {
		this.articulo = articulo;
	}

	public int getCantidad() {
		return this.cantidad;
	}

	public void setCantidad(int cantidad) {
		this.cantidad = cantidad;
	}

	public BigDecimal getValorUnitario() {
		return this.valorUnitario;
	}

	public void setValorUnitario(BigDecimal valorUnitario) {
		this.valorUnitario = valorUnitario;
	}

	public BigDecimal getValorTotal() {
		return this.valorTotal;
	}

	public void setValorTotal(BigDecimal valorTotal) {
		this.valorTotal = valorTotal;
	}

	public Date getFechaModifica() {
		return this.fechaModifica;
	}

	public void setFechaModifica(Date fechaModifica) {
		this.fechaModifica = fechaModifica;
	}

	public String getHoraModifica() {
		return this.horaModifica;
	}

	public void setHoraModifica(String horaModifica) {
		this.horaModifica = horaModifica;
	}

}
