package com.servinte.axioma.orm;

// Generated Apr 7, 2010 3:58:52 PM by Hibernate Tools 3.2.5.Beta

import java.math.BigDecimal;
import java.util.Date;

/**
 * DetAgruHonoraEspServ generated by hbm2java
 */
public class DetAgruHonoraEspServ implements java.io.Serializable {

	private long codigo;
	private CuentasContables cuentasContablesByCuentaVigAntInst;
	private Usuarios usuarios;
	private CuentasContables cuentasContablesByCuentaHonorarios;
	private TiposServicio tiposServicio;
	private HonorariosEspServ honorariosEspServ;
	private CuentasContables cuentasContablesByCuentaIngresoInst;
	private Especialidades especialidades;
	private GruposServicios gruposServicios;
	private BigDecimal porcentajeParticipacion;
	private BigDecimal valorParticipacion;
	private Date fechaModifica;
	private String horaModifica;

	public DetAgruHonoraEspServ() {
	}

	public DetAgruHonoraEspServ(long codigo, Usuarios usuarios,
			HonorariosEspServ honorariosEspServ, Date fechaModifica,
			String horaModifica) {
		this.codigo = codigo;
		this.usuarios = usuarios;
		this.honorariosEspServ = honorariosEspServ;
		this.fechaModifica = fechaModifica;
		this.horaModifica = horaModifica;
	}

	public DetAgruHonoraEspServ(long codigo,
			CuentasContables cuentasContablesByCuentaVigAntInst,
			Usuarios usuarios,
			CuentasContables cuentasContablesByCuentaHonorarios,
			TiposServicio tiposServicio, HonorariosEspServ honorariosEspServ,
			CuentasContables cuentasContablesByCuentaIngresoInst,
			Especialidades especialidades, GruposServicios gruposServicios,
			BigDecimal porcentajeParticipacion, BigDecimal valorParticipacion,
			Date fechaModifica, String horaModifica) {
		this.codigo = codigo;
		this.cuentasContablesByCuentaVigAntInst = cuentasContablesByCuentaVigAntInst;
		this.usuarios = usuarios;
		this.cuentasContablesByCuentaHonorarios = cuentasContablesByCuentaHonorarios;
		this.tiposServicio = tiposServicio;
		this.honorariosEspServ = honorariosEspServ;
		this.cuentasContablesByCuentaIngresoInst = cuentasContablesByCuentaIngresoInst;
		this.especialidades = especialidades;
		this.gruposServicios = gruposServicios;
		this.porcentajeParticipacion = porcentajeParticipacion;
		this.valorParticipacion = valorParticipacion;
		this.fechaModifica = fechaModifica;
		this.horaModifica = horaModifica;
	}

	public long getCodigo() {
		return this.codigo;
	}

	public void setCodigo(long codigo) {
		this.codigo = codigo;
	}

	public CuentasContables getCuentasContablesByCuentaVigAntInst() {
		return this.cuentasContablesByCuentaVigAntInst;
	}

	public void setCuentasContablesByCuentaVigAntInst(
			CuentasContables cuentasContablesByCuentaVigAntInst) {
		this.cuentasContablesByCuentaVigAntInst = cuentasContablesByCuentaVigAntInst;
	}

	public Usuarios getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(Usuarios usuarios) {
		this.usuarios = usuarios;
	}

	public CuentasContables getCuentasContablesByCuentaHonorarios() {
		return this.cuentasContablesByCuentaHonorarios;
	}

	public void setCuentasContablesByCuentaHonorarios(
			CuentasContables cuentasContablesByCuentaHonorarios) {
		this.cuentasContablesByCuentaHonorarios = cuentasContablesByCuentaHonorarios;
	}

	public TiposServicio getTiposServicio() {
		return this.tiposServicio;
	}

	public void setTiposServicio(TiposServicio tiposServicio) {
		this.tiposServicio = tiposServicio;
	}

	public HonorariosEspServ getHonorariosEspServ() {
		return this.honorariosEspServ;
	}

	public void setHonorariosEspServ(HonorariosEspServ honorariosEspServ) {
		this.honorariosEspServ = honorariosEspServ;
	}

	public CuentasContables getCuentasContablesByCuentaIngresoInst() {
		return this.cuentasContablesByCuentaIngresoInst;
	}

	public void setCuentasContablesByCuentaIngresoInst(
			CuentasContables cuentasContablesByCuentaIngresoInst) {
		this.cuentasContablesByCuentaIngresoInst = cuentasContablesByCuentaIngresoInst;
	}

	public Especialidades getEspecialidades() {
		return this.especialidades;
	}

	public void setEspecialidades(Especialidades especialidades) {
		this.especialidades = especialidades;
	}

	public GruposServicios getGruposServicios() {
		return this.gruposServicios;
	}

	public void setGruposServicios(GruposServicios gruposServicios) {
		this.gruposServicios = gruposServicios;
	}

	public BigDecimal getPorcentajeParticipacion() {
		return this.porcentajeParticipacion;
	}

	public void setPorcentajeParticipacion(BigDecimal porcentajeParticipacion) {
		this.porcentajeParticipacion = porcentajeParticipacion;
	}

	public BigDecimal getValorParticipacion() {
		return this.valorParticipacion;
	}

	public void setValorParticipacion(BigDecimal valorParticipacion) {
		this.valorParticipacion = valorParticipacion;
	}

	public Date getFechaModifica() {
		return this.fechaModifica;
	}

	public void setFechaModifica(Date fechaModifica) {
		this.fechaModifica = fechaModifica;
	}

	public String getHoraModifica() {
		return this.horaModifica;
	}

	public void setHoraModifica(String horaModifica) {
		this.horaModifica = horaModifica;
	}

}
