package com.servinte.axioma.orm;

// Generated 19/05/2011 10:17:47 AM by Hibernate Tools 3.4.0.CR1

/**
 * DetOrdenAmbArticuloId generated by hbm2java
 */
public class DetOrdenAmbArticuloId implements java.io.Serializable {

	private long codigoOrden;
	private int articulo;

	public DetOrdenAmbArticuloId() {
	}

	public DetOrdenAmbArticuloId(long codigoOrden, int articulo) {
		this.codigoOrden = codigoOrden;
		this.articulo = articulo;
	}

	public long getCodigoOrden() {
		return this.codigoOrden;
	}

	public void setCodigoOrden(long codigoOrden) {
		this.codigoOrden = codigoOrden;
	}

	public int getArticulo() {
		return this.articulo;
	}

	public void setArticulo(int articulo) {
		this.articulo = articulo;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DetOrdenAmbArticuloId))
			return false;
		DetOrdenAmbArticuloId castOther = (DetOrdenAmbArticuloId) other;

		return (this.getCodigoOrden() == castOther.getCodigoOrden())
				&& (this.getArticulo() == castOther.getArticulo());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getCodigoOrden();
		result = 37 * result + this.getArticulo();
		return result;
	}

}
