package com.servinte.axioma.orm;

// Generated Nov 30, 2010 11:44:21 AM by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;

/**
 * EstadosPedido generated by hbm2java
 */
public class EstadosPedido implements java.io.Serializable {

	private int codigo;
	private String descripcion;
	private Set pedidos = new HashSet(0);

	public EstadosPedido() {
	}

	public EstadosPedido(int codigo, String descripcion) {
		this.codigo = codigo;
		this.descripcion = descripcion;
	}

	public EstadosPedido(int codigo, String descripcion, Set pedidos) {
		this.codigo = codigo;
		this.descripcion = descripcion;
		this.pedidos = pedidos;
	}

	public int getCodigo() {
		return this.codigo;
	}

	public void setCodigo(int codigo) {
		this.codigo = codigo;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Set getPedidos() {
		return this.pedidos;
	}

	public void setPedidos(Set pedidos) {
		this.pedidos = pedidos;
	}

}
