package com.servinte.axioma.orm;

// Generated Apr 7, 2010 3:58:52 PM by Hibernate Tools 3.2.5.Beta

/**
 * FinServNaturaleza generated by hbm2java
 */
public class FinServNaturaleza implements java.io.Serializable {

	private FinServNaturalezaId id;
	private FinalidadesServicio finalidadesServicio;
	private Instituciones instituciones;
	private NaturalezasServicio naturalezasServicio;

	public FinServNaturaleza() {
	}

	public FinServNaturaleza(FinServNaturalezaId id,
			FinalidadesServicio finalidadesServicio,
			Instituciones instituciones, NaturalezasServicio naturalezasServicio) {
		this.id = id;
		this.finalidadesServicio = finalidadesServicio;
		this.instituciones = instituciones;
		this.naturalezasServicio = naturalezasServicio;
	}

	public FinServNaturalezaId getId() {
		return this.id;
	}

	public void setId(FinServNaturalezaId id) {
		this.id = id;
	}

	public FinalidadesServicio getFinalidadesServicio() {
		return this.finalidadesServicio;
	}

	public void setFinalidadesServicio(FinalidadesServicio finalidadesServicio) {
		this.finalidadesServicio = finalidadesServicio;
	}

	public Instituciones getInstituciones() {
		return this.instituciones;
	}

	public void setInstituciones(Instituciones instituciones) {
		this.instituciones = instituciones;
	}

	public NaturalezasServicio getNaturalezasServicio() {
		return this.naturalezasServicio;
	}

	public void setNaturalezasServicio(NaturalezasServicio naturalezasServicio) {
		this.naturalezasServicio = naturalezasServicio;
	}

}
