package com.servinte.axioma.orm;

// Generated Jan 25, 2011 9:01:47 AM by Hibernate Tools 3.2.4.GA

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * IncluServicioConvenio generated by hbm2java
 */
public class IncluServicioConvenio implements java.io.Serializable {

	private long codigoPk;
	private Servicios servicios;
	private EsquemasTarifarios esquemasTarifarios;
	private IncluPresuConvenio incluPresuConvenio;
	private BigDecimal valorUnitario;
	private int cantidad;
	private char seleccionadoPromocion;
	private char seleccionadoBono;
	private BigDecimal porcentajeDctoPromocion;
	private BigDecimal valorDescuentoPromocion;
	private BigDecimal porcentajeDctoBono;
	private BigDecimal valorDescuentoBono;
	private BigDecimal dctoComercialUnitario;
	private BigDecimal valorHonorarioPromocion;
	private BigDecimal porcHonorarioPromocion;
	private char contratado;
	private BigDecimal porcentajeDctoOdontologico;
	private Set incluProgramaConvenios = new HashSet(0);

	public IncluServicioConvenio() {
	}

	public IncluServicioConvenio(long codigoPk, Servicios servicios,
			EsquemasTarifarios esquemasTarifarios,
			IncluPresuConvenio incluPresuConvenio, BigDecimal valorUnitario,
			int cantidad, char seleccionadoPromocion, char seleccionadoBono,
			char contratado) {
		this.codigoPk = codigoPk;
		this.servicios = servicios;
		this.esquemasTarifarios = esquemasTarifarios;
		this.incluPresuConvenio = incluPresuConvenio;
		this.valorUnitario = valorUnitario;
		this.cantidad = cantidad;
		this.seleccionadoPromocion = seleccionadoPromocion;
		this.seleccionadoBono = seleccionadoBono;
		this.contratado = contratado;
	}

	public IncluServicioConvenio(long codigoPk, Servicios servicios,
			EsquemasTarifarios esquemasTarifarios,
			IncluPresuConvenio incluPresuConvenio, BigDecimal valorUnitario,
			int cantidad, char seleccionadoPromocion, char seleccionadoBono,
			BigDecimal porcentajeDctoPromocion,
			BigDecimal valorDescuentoPromocion, BigDecimal porcentajeDctoBono,
			BigDecimal valorDescuentoBono, BigDecimal dctoComercialUnitario,
			BigDecimal valorHonorarioPromocion,
			BigDecimal porcHonorarioPromocion, char contratado,
			BigDecimal porcentajeDctoOdontologico, Set incluProgramaConvenios) {
		this.codigoPk = codigoPk;
		this.servicios = servicios;
		this.esquemasTarifarios = esquemasTarifarios;
		this.incluPresuConvenio = incluPresuConvenio;
		this.valorUnitario = valorUnitario;
		this.cantidad = cantidad;
		this.seleccionadoPromocion = seleccionadoPromocion;
		this.seleccionadoBono = seleccionadoBono;
		this.porcentajeDctoPromocion = porcentajeDctoPromocion;
		this.valorDescuentoPromocion = valorDescuentoPromocion;
		this.porcentajeDctoBono = porcentajeDctoBono;
		this.valorDescuentoBono = valorDescuentoBono;
		this.dctoComercialUnitario = dctoComercialUnitario;
		this.valorHonorarioPromocion = valorHonorarioPromocion;
		this.porcHonorarioPromocion = porcHonorarioPromocion;
		this.contratado = contratado;
		this.porcentajeDctoOdontologico = porcentajeDctoOdontologico;
		this.incluProgramaConvenios = incluProgramaConvenios;
	}

	public long getCodigoPk() {
		return this.codigoPk;
	}

	public void setCodigoPk(long codigoPk) {
		this.codigoPk = codigoPk;
	}

	public Servicios getServicios() {
		return this.servicios;
	}

	public void setServicios(Servicios servicios) {
		this.servicios = servicios;
	}

	public EsquemasTarifarios getEsquemasTarifarios() {
		return this.esquemasTarifarios;
	}

	public void setEsquemasTarifarios(EsquemasTarifarios esquemasTarifarios) {
		this.esquemasTarifarios = esquemasTarifarios;
	}

	public IncluPresuConvenio getIncluPresuConvenio() {
		return this.incluPresuConvenio;
	}

	public void setIncluPresuConvenio(IncluPresuConvenio incluPresuConvenio) {
		this.incluPresuConvenio = incluPresuConvenio;
	}

	public BigDecimal getValorUnitario() {
		return this.valorUnitario;
	}

	public void setValorUnitario(BigDecimal valorUnitario) {
		this.valorUnitario = valorUnitario;
	}

	public int getCantidad() {
		return this.cantidad;
	}

	public void setCantidad(int cantidad) {
		this.cantidad = cantidad;
	}

	public char getSeleccionadoPromocion() {
		return this.seleccionadoPromocion;
	}

	public void setSeleccionadoPromocion(char seleccionadoPromocion) {
		this.seleccionadoPromocion = seleccionadoPromocion;
	}

	public char getSeleccionadoBono() {
		return this.seleccionadoBono;
	}

	public void setSeleccionadoBono(char seleccionadoBono) {
		this.seleccionadoBono = seleccionadoBono;
	}

	public BigDecimal getPorcentajeDctoPromocion() {
		return this.porcentajeDctoPromocion;
	}

	public void setPorcentajeDctoPromocion(BigDecimal porcentajeDctoPromocion) {
		this.porcentajeDctoPromocion = porcentajeDctoPromocion;
	}

	public BigDecimal getValorDescuentoPromocion() {
		return this.valorDescuentoPromocion;
	}

	public void setValorDescuentoPromocion(BigDecimal valorDescuentoPromocion) {
		this.valorDescuentoPromocion = valorDescuentoPromocion;
	}

	public BigDecimal getPorcentajeDctoBono() {
		return this.porcentajeDctoBono;
	}

	public void setPorcentajeDctoBono(BigDecimal porcentajeDctoBono) {
		this.porcentajeDctoBono = porcentajeDctoBono;
	}

	public BigDecimal getValorDescuentoBono() {
		return this.valorDescuentoBono;
	}

	public void setValorDescuentoBono(BigDecimal valorDescuentoBono) {
		this.valorDescuentoBono = valorDescuentoBono;
	}

	public BigDecimal getDctoComercialUnitario() {
		return this.dctoComercialUnitario;
	}

	public void setDctoComercialUnitario(BigDecimal dctoComercialUnitario) {
		this.dctoComercialUnitario = dctoComercialUnitario;
	}

	public BigDecimal getValorHonorarioPromocion() {
		return this.valorHonorarioPromocion;
	}

	public void setValorHonorarioPromocion(BigDecimal valorHonorarioPromocion) {
		this.valorHonorarioPromocion = valorHonorarioPromocion;
	}

	public BigDecimal getPorcHonorarioPromocion() {
		return this.porcHonorarioPromocion;
	}

	public void setPorcHonorarioPromocion(BigDecimal porcHonorarioPromocion) {
		this.porcHonorarioPromocion = porcHonorarioPromocion;
	}

	public char getContratado() {
		return this.contratado;
	}

	public void setContratado(char contratado) {
		this.contratado = contratado;
	}

	public BigDecimal getPorcentajeDctoOdontologico() {
		return this.porcentajeDctoOdontologico;
	}

	public void setPorcentajeDctoOdontologico(
			BigDecimal porcentajeDctoOdontologico) {
		this.porcentajeDctoOdontologico = porcentajeDctoOdontologico;
	}

	public Set getIncluProgramaConvenios() {
		return this.incluProgramaConvenios;
	}

	public void setIncluProgramaConvenios(Set incluProgramaConvenios) {
		this.incluProgramaConvenios = incluProgramaConvenios;
	}

}
