package com.servinte.axioma.orm;

// Generated 10/12/2012 12:05:02 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * JustificacionArtSol generated by hbm2java
 */
public class JustificacionArtSol implements java.io.Serializable {

	private long codigo;
	private Solicitudes solicitudes;
	private OrdenesAmbulatorias ordenesAmbulatorias;
	private Instituciones instituciones;
	private int articulo;
	private Integer frecuencia;
	private String tipoFrecuencia;
	private String concentracion;
	private Long tiempoTratamiento;
	private int grupoTerapeutico;
	private String tiempoRespuesta;
	private String registroInvima;
	private String efectoDeseado;
	private String efectosSecundarios;
	private String bibliografia;
	private Date fechaModifica;
	private String horaModifica;
	private String consecutivo;
	private Double dosis;
	private String unidosis;
	private String formaFarmaceutica;
	private String usuarioModifica;
	private String dosificacion;
	private String documentosadj;
	private Date fecha;
	private String tipoJus;
	private Set solicitudeses = new HashSet(0);
	private Set ordAmbJustArtSols = new HashSet(0);

	public JustificacionArtSol() {
	}

	public JustificacionArtSol(long codigo, Instituciones instituciones,
			int articulo, int grupoTerapeutico, Date fechaModifica,
			String horaModifica, String consecutivo, String usuarioModifica,
			Date fecha) {
		this.codigo = codigo;
		this.instituciones = instituciones;
		this.articulo = articulo;
		this.grupoTerapeutico = grupoTerapeutico;
		this.fechaModifica = fechaModifica;
		this.horaModifica = horaModifica;
		this.consecutivo = consecutivo;
		this.usuarioModifica = usuarioModifica;
		this.fecha = fecha;
	}

	public JustificacionArtSol(long codigo, Solicitudes solicitudes,
			OrdenesAmbulatorias ordenesAmbulatorias,
			Instituciones instituciones, int articulo, Integer frecuencia,
			String tipoFrecuencia, String concentracion,
			Long tiempoTratamiento, int grupoTerapeutico,
			String tiempoRespuesta, String registroInvima,
			String efectoDeseado, String efectosSecundarios,
			String bibliografia, Date fechaModifica, String horaModifica,
			String consecutivo, Double dosis, String unidosis,
			String formaFarmaceutica, String usuarioModifica,
			String dosificacion, String documentosadj, Date fecha,
			String tipoJus, Set solicitudeses, Set ordAmbJustArtSols) {
		this.codigo = codigo;
		this.solicitudes = solicitudes;
		this.ordenesAmbulatorias = ordenesAmbulatorias;
		this.instituciones = instituciones;
		this.articulo = articulo;
		this.frecuencia = frecuencia;
		this.tipoFrecuencia = tipoFrecuencia;
		this.concentracion = concentracion;
		this.tiempoTratamiento = tiempoTratamiento;
		this.grupoTerapeutico = grupoTerapeutico;
		this.tiempoRespuesta = tiempoRespuesta;
		this.registroInvima = registroInvima;
		this.efectoDeseado = efectoDeseado;
		this.efectosSecundarios = efectosSecundarios;
		this.bibliografia = bibliografia;
		this.fechaModifica = fechaModifica;
		this.horaModifica = horaModifica;
		this.consecutivo = consecutivo;
		this.dosis = dosis;
		this.unidosis = unidosis;
		this.formaFarmaceutica = formaFarmaceutica;
		this.usuarioModifica = usuarioModifica;
		this.dosificacion = dosificacion;
		this.documentosadj = documentosadj;
		this.fecha = fecha;
		this.tipoJus = tipoJus;
		this.solicitudeses = solicitudeses;
		this.ordAmbJustArtSols = ordAmbJustArtSols;
	}

	public long getCodigo() {
		return this.codigo;
	}

	public void setCodigo(long codigo) {
		this.codigo = codigo;
	}

	public Solicitudes getSolicitudes() {
		return this.solicitudes;
	}

	public void setSolicitudes(Solicitudes solicitudes) {
		this.solicitudes = solicitudes;
	}

	public OrdenesAmbulatorias getOrdenesAmbulatorias() {
		return this.ordenesAmbulatorias;
	}

	public void setOrdenesAmbulatorias(OrdenesAmbulatorias ordenesAmbulatorias) {
		this.ordenesAmbulatorias = ordenesAmbulatorias;
	}

	public Instituciones getInstituciones() {
		return this.instituciones;
	}

	public void setInstituciones(Instituciones instituciones) {
		this.instituciones = instituciones;
	}

	public int getArticulo() {
		return this.articulo;
	}

	public void setArticulo(int articulo) {
		this.articulo = articulo;
	}

	public Integer getFrecuencia() {
		return this.frecuencia;
	}

	public void setFrecuencia(Integer frecuencia) {
		this.frecuencia = frecuencia;
	}

	public String getTipoFrecuencia() {
		return this.tipoFrecuencia;
	}

	public void setTipoFrecuencia(String tipoFrecuencia) {
		this.tipoFrecuencia = tipoFrecuencia;
	}

	public String getConcentracion() {
		return this.concentracion;
	}

	public void setConcentracion(String concentracion) {
		this.concentracion = concentracion;
	}

	public Long getTiempoTratamiento() {
		return this.tiempoTratamiento;
	}

	public void setTiempoTratamiento(Long tiempoTratamiento) {
		this.tiempoTratamiento = tiempoTratamiento;
	}

	public int getGrupoTerapeutico() {
		return this.grupoTerapeutico;
	}

	public void setGrupoTerapeutico(int grupoTerapeutico) {
		this.grupoTerapeutico = grupoTerapeutico;
	}

	public String getTiempoRespuesta() {
		return this.tiempoRespuesta;
	}

	public void setTiempoRespuesta(String tiempoRespuesta) {
		this.tiempoRespuesta = tiempoRespuesta;
	}

	public String getRegistroInvima() {
		return this.registroInvima;
	}

	public void setRegistroInvima(String registroInvima) {
		this.registroInvima = registroInvima;
	}

	public String getEfectoDeseado() {
		return this.efectoDeseado;
	}

	public void setEfectoDeseado(String efectoDeseado) {
		this.efectoDeseado = efectoDeseado;
	}

	public String getEfectosSecundarios() {
		return this.efectosSecundarios;
	}

	public void setEfectosSecundarios(String efectosSecundarios) {
		this.efectosSecundarios = efectosSecundarios;
	}

	public String getBibliografia() {
		return this.bibliografia;
	}

	public void setBibliografia(String bibliografia) {
		this.bibliografia = bibliografia;
	}

	public Date getFechaModifica() {
		return this.fechaModifica;
	}

	public void setFechaModifica(Date fechaModifica) {
		this.fechaModifica = fechaModifica;
	}

	public String getHoraModifica() {
		return this.horaModifica;
	}

	public void setHoraModifica(String horaModifica) {
		this.horaModifica = horaModifica;
	}

	public String getConsecutivo() {
		return this.consecutivo;
	}

	public void setConsecutivo(String consecutivo) {
		this.consecutivo = consecutivo;
	}

	public Double getDosis() {
		return this.dosis;
	}

	public void setDosis(Double dosis) {
		this.dosis = dosis;
	}

	public String getUnidosis() {
		return this.unidosis;
	}

	public void setUnidosis(String unidosis) {
		this.unidosis = unidosis;
	}

	public String getFormaFarmaceutica() {
		return this.formaFarmaceutica;
	}

	public void setFormaFarmaceutica(String formaFarmaceutica) {
		this.formaFarmaceutica = formaFarmaceutica;
	}

	public String getUsuarioModifica() {
		return this.usuarioModifica;
	}

	public void setUsuarioModifica(String usuarioModifica) {
		this.usuarioModifica = usuarioModifica;
	}

	public String getDosificacion() {
		return this.dosificacion;
	}

	public void setDosificacion(String dosificacion) {
		this.dosificacion = dosificacion;
	}

	public String getDocumentosadj() {
		return this.documentosadj;
	}

	public void setDocumentosadj(String documentosadj) {
		this.documentosadj = documentosadj;
	}

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	public String getTipoJus() {
		return this.tipoJus;
	}

	public void setTipoJus(String tipoJus) {
		this.tipoJus = tipoJus;
	}

	public Set getSolicitudeses() {
		return this.solicitudeses;
	}

	public void setSolicitudeses(Set solicitudeses) {
		this.solicitudeses = solicitudeses;
	}

	public Set getOrdAmbJustArtSols() {
		return this.ordAmbJustArtSols;
	}

	public void setOrdAmbJustArtSols(Set ordAmbJustArtSols) {
		this.ordAmbJustArtSols = ordAmbJustArtSols;
	}

}
