package com.servinte.axioma.orm;

// Generated Apr 7, 2010 3:58:52 PM by Hibernate Tools 3.2.5.Beta

/**
 * LogAutorizacionIngEven generated by hbm2java
 */
public class LogAutorizacionIngEven implements java.io.Serializable {

	private LogAutorizacionIngEvenId id;
	private Usuarios usuarios;
	private Funcionalidades funcionalidades;
	private TiposIdentificacion tiposIdentificacion;
	private Instituciones instituciones;
	private Personas personas;

	public LogAutorizacionIngEven() {
	}

	public LogAutorizacionIngEven(LogAutorizacionIngEvenId id,
			Usuarios usuarios, Funcionalidades funcionalidades,
			TiposIdentificacion tiposIdentificacion, Instituciones instituciones) {
		this.id = id;
		this.usuarios = usuarios;
		this.funcionalidades = funcionalidades;
		this.tiposIdentificacion = tiposIdentificacion;
		this.instituciones = instituciones;
	}

	public LogAutorizacionIngEven(LogAutorizacionIngEvenId id,
			Usuarios usuarios, Funcionalidades funcionalidades,
			TiposIdentificacion tiposIdentificacion,
			Instituciones instituciones, Personas personas) {
		this.id = id;
		this.usuarios = usuarios;
		this.funcionalidades = funcionalidades;
		this.tiposIdentificacion = tiposIdentificacion;
		this.instituciones = instituciones;
		this.personas = personas;
	}

	public LogAutorizacionIngEvenId getId() {
		return this.id;
	}

	public void setId(LogAutorizacionIngEvenId id) {
		this.id = id;
	}

	public Usuarios getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(Usuarios usuarios) {
		this.usuarios = usuarios;
	}

	public Funcionalidades getFuncionalidades() {
		return this.funcionalidades;
	}

	public void setFuncionalidades(Funcionalidades funcionalidades) {
		this.funcionalidades = funcionalidades;
	}

	public TiposIdentificacion getTiposIdentificacion() {
		return this.tiposIdentificacion;
	}

	public void setTiposIdentificacion(TiposIdentificacion tiposIdentificacion) {
		this.tiposIdentificacion = tiposIdentificacion;
	}

	public Instituciones getInstituciones() {
		return this.instituciones;
	}

	public void setInstituciones(Instituciones instituciones) {
		this.instituciones = instituciones;
	}

	public Personas getPersonas() {
		return this.personas;
	}

	public void setPersonas(Personas personas) {
		this.personas = personas;
	}

}
