package com.servinte.axioma.orm;

// Generated Apr 7, 2010 3:58:52 PM by Hibernate Tools 3.2.5.Beta

import java.util.Date;

/**
 * LogCentrosCostoEntSub generated by hbm2java
 */
public class LogCentrosCostoEntSub implements java.io.Serializable {

	private long consecutivo;
	private EntidadesSubcontratadas entidadesSubcontratadas;
	private CentrosCosto centrosCosto;
	private String eliminado;
	private Integer nroPrioridadAnterior;
	private Integer nroPrioridadNueva;
	private String respOtrosUsuAnterior;
	private String respOtrosUsuNuevo;
	private String usuarioModifica;
	private Date fechaModifica;
	private String horaModifica;

	public LogCentrosCostoEntSub() {
	}

	public LogCentrosCostoEntSub(long consecutivo,
			EntidadesSubcontratadas entidadesSubcontratadas,
			CentrosCosto centrosCosto, String eliminado,
			String usuarioModifica, Date fechaModifica, String horaModifica) {
		this.consecutivo = consecutivo;
		this.entidadesSubcontratadas = entidadesSubcontratadas;
		this.centrosCosto = centrosCosto;
		this.eliminado = eliminado;
		this.usuarioModifica = usuarioModifica;
		this.fechaModifica = fechaModifica;
		this.horaModifica = horaModifica;
	}

	public LogCentrosCostoEntSub(long consecutivo,
			EntidadesSubcontratadas entidadesSubcontratadas,
			CentrosCosto centrosCosto, String eliminado,
			Integer nroPrioridadAnterior, Integer nroPrioridadNueva,
			String respOtrosUsuAnterior, String respOtrosUsuNuevo,
			String usuarioModifica, Date fechaModifica, String horaModifica) {
		this.consecutivo = consecutivo;
		this.entidadesSubcontratadas = entidadesSubcontratadas;
		this.centrosCosto = centrosCosto;
		this.eliminado = eliminado;
		this.nroPrioridadAnterior = nroPrioridadAnterior;
		this.nroPrioridadNueva = nroPrioridadNueva;
		this.respOtrosUsuAnterior = respOtrosUsuAnterior;
		this.respOtrosUsuNuevo = respOtrosUsuNuevo;
		this.usuarioModifica = usuarioModifica;
		this.fechaModifica = fechaModifica;
		this.horaModifica = horaModifica;
	}

	public long getConsecutivo() {
		return this.consecutivo;
	}

	public void setConsecutivo(long consecutivo) {
		this.consecutivo = consecutivo;
	}

	public EntidadesSubcontratadas getEntidadesSubcontratadas() {
		return this.entidadesSubcontratadas;
	}

	public void setEntidadesSubcontratadas(
			EntidadesSubcontratadas entidadesSubcontratadas) {
		this.entidadesSubcontratadas = entidadesSubcontratadas;
	}

	public CentrosCosto getCentrosCosto() {
		return this.centrosCosto;
	}

	public void setCentrosCosto(CentrosCosto centrosCosto) {
		this.centrosCosto = centrosCosto;
	}

	public String getEliminado() {
		return this.eliminado;
	}

	public void setEliminado(String eliminado) {
		this.eliminado = eliminado;
	}

	public Integer getNroPrioridadAnterior() {
		return this.nroPrioridadAnterior;
	}

	public void setNroPrioridadAnterior(Integer nroPrioridadAnterior) {
		this.nroPrioridadAnterior = nroPrioridadAnterior;
	}

	public Integer getNroPrioridadNueva() {
		return this.nroPrioridadNueva;
	}

	public void setNroPrioridadNueva(Integer nroPrioridadNueva) {
		this.nroPrioridadNueva = nroPrioridadNueva;
	}

	public String getRespOtrosUsuAnterior() {
		return this.respOtrosUsuAnterior;
	}

	public void setRespOtrosUsuAnterior(String respOtrosUsuAnterior) {
		this.respOtrosUsuAnterior = respOtrosUsuAnterior;
	}

	public String getRespOtrosUsuNuevo() {
		return this.respOtrosUsuNuevo;
	}

	public void setRespOtrosUsuNuevo(String respOtrosUsuNuevo) {
		this.respOtrosUsuNuevo = respOtrosUsuNuevo;
	}

	public String getUsuarioModifica() {
		return this.usuarioModifica;
	}

	public void setUsuarioModifica(String usuarioModifica) {
		this.usuarioModifica = usuarioModifica;
	}

	public Date getFechaModifica() {
		return this.fechaModifica;
	}

	public void setFechaModifica(Date fechaModifica) {
		this.fechaModifica = fechaModifica;
	}

	public String getHoraModifica() {
		return this.horaModifica;
	}

	public void setHoraModifica(String horaModifica) {
		this.horaModifica = horaModifica;
	}

}
