package com.servinte.axioma.orm;

// Generated Apr 7, 2010 3:58:52 PM by Hibernate Tools 3.2.5.Beta

/**
 * LogProgramas generated by hbm2java
 */
public class LogProgramas implements java.io.Serializable {

	private long codigoPk;
	private Especialidades especialidades;
	private Usuarios usuarios;
	private long programa;
	private String codigoPrograma;
	private String nombre;
	private String activo;
	private String eliminado;
	private String fecha;
	private String hora;

	public LogProgramas() {
	}

	public LogProgramas(long codigoPk, Especialidades especialidades,
			Usuarios usuarios, long programa, String codigoPrograma,
			String nombre, String activo, String eliminado, String fecha,
			String hora) {
		this.codigoPk = codigoPk;
		this.especialidades = especialidades;
		this.usuarios = usuarios;
		this.programa = programa;
		this.codigoPrograma = codigoPrograma;
		this.nombre = nombre;
		this.activo = activo;
		this.eliminado = eliminado;
		this.fecha = fecha;
		this.hora = hora;
	}

	public long getCodigoPk() {
		return this.codigoPk;
	}

	public void setCodigoPk(long codigoPk) {
		this.codigoPk = codigoPk;
	}

	public Especialidades getEspecialidades() {
		return this.especialidades;
	}

	public void setEspecialidades(Especialidades especialidades) {
		this.especialidades = especialidades;
	}

	public Usuarios getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(Usuarios usuarios) {
		this.usuarios = usuarios;
	}

	public long getPrograma() {
		return this.programa;
	}

	public void setPrograma(long programa) {
		this.programa = programa;
	}

	public String getCodigoPrograma() {
		return this.codigoPrograma;
	}

	public void setCodigoPrograma(String codigoPrograma) {
		this.codigoPrograma = codigoPrograma;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getActivo() {
		return this.activo;
	}

	public void setActivo(String activo) {
		this.activo = activo;
	}

	public String getEliminado() {
		return this.eliminado;
	}

	public void setEliminado(String eliminado) {
		this.eliminado = eliminado;
	}

	public String getFecha() {
		return this.fecha;
	}

	public void setFecha(String fecha) {
		this.fecha = fecha;
	}

	public String getHora() {
		return this.hora;
	}

	public void setHora(String hora) {
		this.hora = hora;
	}

}
