package com.servinte.axioma.orm;

// Generated Feb 18, 2011 11:00:55 AM by Hibernate Tools 3.2.4.GA

/**
 * LogRipsEntSubInconsisArch generated by hbm2java
 */
public class LogRipsEntSubInconsisArch implements java.io.Serializable {

	private long codigoPk;
	private LogRipsEntidadesSubArchivo logRipsEntidadesSubArchivo;
	private String tipoInconsistencia;

	public LogRipsEntSubInconsisArch() {
	}

	public LogRipsEntSubInconsisArch(long codigoPk,
			LogRipsEntidadesSubArchivo logRipsEntidadesSubArchivo,
			String tipoInconsistencia) {
		this.codigoPk = codigoPk;
		this.logRipsEntidadesSubArchivo = logRipsEntidadesSubArchivo;
		this.tipoInconsistencia = tipoInconsistencia;
	}

	public long getCodigoPk() {
		return this.codigoPk;
	}

	public void setCodigoPk(long codigoPk) {
		this.codigoPk = codigoPk;
	}

	public LogRipsEntidadesSubArchivo getLogRipsEntidadesSubArchivo() {
		return this.logRipsEntidadesSubArchivo;
	}

	public void setLogRipsEntidadesSubArchivo(
			LogRipsEntidadesSubArchivo logRipsEntidadesSubArchivo) {
		this.logRipsEntidadesSubArchivo = logRipsEntidadesSubArchivo;
	}

	public String getTipoInconsistencia() {
		return this.tipoInconsistencia;
	}

	public void setTipoInconsistencia(String tipoInconsistencia) {
		this.tipoInconsistencia = tipoInconsistencia;
	}

}
