package com.servinte.axioma.orm;

// Generated Apr 7, 2010 3:58:52 PM by Hibernate Tools 3.2.5.Beta

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * MotivosDescuentosOdon generated by hbm2java
 */
public class MotivosDescuentosOdon implements java.io.Serializable {

	private long codigoPk;
	private Usuarios usuarios;
	private Instituciones instituciones;
	private String codigoMotivo;
	private String descripcion;
	private String tipo;
	private char activo;
	private Date fechaModifica;
	private String horaModifica;
	private String indicativo;
	private Set presupuestoDctoOdons = new HashSet(0);

	public MotivosDescuentosOdon() {
	}

	public MotivosDescuentosOdon(long codigoPk, Usuarios usuarios,
			Instituciones instituciones, String codigoMotivo,
			String descripcion, String tipo, char activo, Date fechaModifica,
			String horaModifica, String indicativo) {
		this.codigoPk = codigoPk;
		this.usuarios = usuarios;
		this.instituciones = instituciones;
		this.codigoMotivo = codigoMotivo;
		this.descripcion = descripcion;
		this.tipo = tipo;
		this.activo = activo;
		this.fechaModifica = fechaModifica;
		this.horaModifica = horaModifica;
		this.indicativo = indicativo;
	}

	public MotivosDescuentosOdon(long codigoPk, Usuarios usuarios,
			Instituciones instituciones, String codigoMotivo,
			String descripcion, String tipo, char activo, Date fechaModifica,
			String horaModifica, String indicativo, Set presupuestoDctoOdons) {
		this.codigoPk = codigoPk;
		this.usuarios = usuarios;
		this.instituciones = instituciones;
		this.codigoMotivo = codigoMotivo;
		this.descripcion = descripcion;
		this.tipo = tipo;
		this.activo = activo;
		this.fechaModifica = fechaModifica;
		this.horaModifica = horaModifica;
		this.indicativo = indicativo;
		this.presupuestoDctoOdons = presupuestoDctoOdons;
	}

	public long getCodigoPk() {
		return this.codigoPk;
	}

	public void setCodigoPk(long codigoPk) {
		this.codigoPk = codigoPk;
	}

	public Usuarios getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(Usuarios usuarios) {
		this.usuarios = usuarios;
	}

	public Instituciones getInstituciones() {
		return this.instituciones;
	}

	public void setInstituciones(Instituciones instituciones) {
		this.instituciones = instituciones;
	}

	public String getCodigoMotivo() {
		return this.codigoMotivo;
	}

	public void setCodigoMotivo(String codigoMotivo) {
		this.codigoMotivo = codigoMotivo;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	public char getActivo() {
		return this.activo;
	}

	public void setActivo(char activo) {
		this.activo = activo;
	}

	public Date getFechaModifica() {
		return this.fechaModifica;
	}

	public void setFechaModifica(Date fechaModifica) {
		this.fechaModifica = fechaModifica;
	}

	public String getHoraModifica() {
		return this.horaModifica;
	}

	public void setHoraModifica(String horaModifica) {
		this.horaModifica = horaModifica;
	}

	public String getIndicativo() {
		return this.indicativo;
	}

	public void setIndicativo(String indicativo) {
		this.indicativo = indicativo;
	}

	public Set getPresupuestoDctoOdons() {
		return this.presupuestoDctoOdons;
	}

	public void setPresupuestoDctoOdons(Set presupuestoDctoOdons) {
		this.presupuestoDctoOdons = presupuestoDctoOdons;
	}

}
