package com.servinte.axioma.orm;

// Generated Jan 25, 2011 4:25:29 PM by Hibernate Tools 3.2.4.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * NivelAutorServMedic generated by hbm2java
 */
public class NivelAutorServMedic implements java.io.Serializable {

	private int codigoPk;
	private NivelAutorizacion nivelAutorizacion;
	private Usuarios usuarios;
	private Date fechaRegistro;
	private String horaRegistro;
	private Set nivelAutorAgrServs = new HashSet(0);
	private Set nivelAutorServicios = new HashSet(0);
	private Set nivelAutorAgrArts = new HashSet(0);
	private Set nivelAutorArticulos = new HashSet(0);

	public NivelAutorServMedic() {
	}

	public NivelAutorServMedic(int codigoPk,
			NivelAutorizacion nivelAutorizacion, Usuarios usuarios,
			Date fechaRegistro, String horaRegistro) {
		this.codigoPk = codigoPk;
		this.nivelAutorizacion = nivelAutorizacion;
		this.usuarios = usuarios;
		this.fechaRegistro = fechaRegistro;
		this.horaRegistro = horaRegistro;
	}

	public NivelAutorServMedic(int codigoPk,
			NivelAutorizacion nivelAutorizacion, Usuarios usuarios,
			Date fechaRegistro, String horaRegistro, Set nivelAutorAgrServs,
			Set nivelAutorServicios, Set nivelAutorAgrArts,
			Set nivelAutorArticulos) {
		this.codigoPk = codigoPk;
		this.nivelAutorizacion = nivelAutorizacion;
		this.usuarios = usuarios;
		this.fechaRegistro = fechaRegistro;
		this.horaRegistro = horaRegistro;
		this.nivelAutorAgrServs = nivelAutorAgrServs;
		this.nivelAutorServicios = nivelAutorServicios;
		this.nivelAutorAgrArts = nivelAutorAgrArts;
		this.nivelAutorArticulos = nivelAutorArticulos;
	}

	public int getCodigoPk() {
		return this.codigoPk;
	}

	public void setCodigoPk(int codigoPk) {
		this.codigoPk = codigoPk;
	}

	public NivelAutorizacion getNivelAutorizacion() {
		return this.nivelAutorizacion;
	}

	public void setNivelAutorizacion(NivelAutorizacion nivelAutorizacion) {
		this.nivelAutorizacion = nivelAutorizacion;
	}

	public Usuarios getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(Usuarios usuarios) {
		this.usuarios = usuarios;
	}

	public Date getFechaRegistro() {
		return this.fechaRegistro;
	}

	public void setFechaRegistro(Date fechaRegistro) {
		this.fechaRegistro = fechaRegistro;
	}

	public String getHoraRegistro() {
		return this.horaRegistro;
	}

	public void setHoraRegistro(String horaRegistro) {
		this.horaRegistro = horaRegistro;
	}

	public Set getNivelAutorAgrServs() {
		return this.nivelAutorAgrServs;
	}

	public void setNivelAutorAgrServs(Set nivelAutorAgrServs) {
		this.nivelAutorAgrServs = nivelAutorAgrServs;
	}

	public Set getNivelAutorServicios() {
		return this.nivelAutorServicios;
	}

	public void setNivelAutorServicios(Set nivelAutorServicios) {
		this.nivelAutorServicios = nivelAutorServicios;
	}

	public Set getNivelAutorAgrArts() {
		return this.nivelAutorAgrArts;
	}

	public void setNivelAutorAgrArts(Set nivelAutorAgrArts) {
		this.nivelAutorAgrArts = nivelAutorAgrArts;
	}

	public Set getNivelAutorArticulos() {
		return this.nivelAutorArticulos;
	}

	public void setNivelAutorArticulos(Set nivelAutorArticulos) {
		this.nivelAutorArticulos = nivelAutorArticulos;
	}

}
