package com.servinte.axioma.orm;

// Generated Apr 7, 2010 3:58:52 PM by Hibernate Tools 3.2.5.Beta

import java.util.Date;

/**
 * PaqAgrupacionArticulos generated by hbm2java
 */
public class PaqAgrupacionArticulos implements java.io.Serializable {

	private long codigoPaqAgrupArticulo;
	private Paquetes paquetes;
	private Instituciones instituciones;
	private Integer clase;
	private Integer grupo;
	private Integer subgrupo;
	private String naturaleza;
	private Integer cantidad;
	private String usuarioModifica;
	private Date fechaModifica;
	private String horaModifica;
	private Long grupoEspecialArticulo;

	public PaqAgrupacionArticulos() {
	}

	public PaqAgrupacionArticulos(long codigoPaqAgrupArticulo,
			Paquetes paquetes, Instituciones instituciones,
			String usuarioModifica, Date fechaModifica, String horaModifica) {
		this.codigoPaqAgrupArticulo = codigoPaqAgrupArticulo;
		this.paquetes = paquetes;
		this.instituciones = instituciones;
		this.usuarioModifica = usuarioModifica;
		this.fechaModifica = fechaModifica;
		this.horaModifica = horaModifica;
	}

	public PaqAgrupacionArticulos(long codigoPaqAgrupArticulo,
			Paquetes paquetes, Instituciones instituciones, Integer clase,
			Integer grupo, Integer subgrupo, String naturaleza,
			Integer cantidad, String usuarioModifica, Date fechaModifica,
			String horaModifica, Long grupoEspecialArticulo) {
		this.codigoPaqAgrupArticulo = codigoPaqAgrupArticulo;
		this.paquetes = paquetes;
		this.instituciones = instituciones;
		this.clase = clase;
		this.grupo = grupo;
		this.subgrupo = subgrupo;
		this.naturaleza = naturaleza;
		this.cantidad = cantidad;
		this.usuarioModifica = usuarioModifica;
		this.fechaModifica = fechaModifica;
		this.horaModifica = horaModifica;
		this.grupoEspecialArticulo = grupoEspecialArticulo;
	}

	public long getCodigoPaqAgrupArticulo() {
		return this.codigoPaqAgrupArticulo;
	}

	public void setCodigoPaqAgrupArticulo(long codigoPaqAgrupArticulo) {
		this.codigoPaqAgrupArticulo = codigoPaqAgrupArticulo;
	}

	public Paquetes getPaquetes() {
		return this.paquetes;
	}

	public void setPaquetes(Paquetes paquetes) {
		this.paquetes = paquetes;
	}

	public Instituciones getInstituciones() {
		return this.instituciones;
	}

	public void setInstituciones(Instituciones instituciones) {
		this.instituciones = instituciones;
	}

	public Integer getClase() {
		return this.clase;
	}

	public void setClase(Integer clase) {
		this.clase = clase;
	}

	public Integer getGrupo() {
		return this.grupo;
	}

	public void setGrupo(Integer grupo) {
		this.grupo = grupo;
	}

	public Integer getSubgrupo() {
		return this.subgrupo;
	}

	public void setSubgrupo(Integer subgrupo) {
		this.subgrupo = subgrupo;
	}

	public String getNaturaleza() {
		return this.naturaleza;
	}

	public void setNaturaleza(String naturaleza) {
		this.naturaleza = naturaleza;
	}

	public Integer getCantidad() {
		return this.cantidad;
	}

	public void setCantidad(Integer cantidad) {
		this.cantidad = cantidad;
	}

	public String getUsuarioModifica() {
		return this.usuarioModifica;
	}

	public void setUsuarioModifica(String usuarioModifica) {
		this.usuarioModifica = usuarioModifica;
	}

	public Date getFechaModifica() {
		return this.fechaModifica;
	}

	public void setFechaModifica(Date fechaModifica) {
		this.fechaModifica = fechaModifica;
	}

	public String getHoraModifica() {
		return this.horaModifica;
	}

	public void setHoraModifica(String horaModifica) {
		this.horaModifica = horaModifica;
	}

	public Long getGrupoEspecialArticulo() {
		return this.grupoEspecialArticulo;
	}

	public void setGrupoEspecialArticulo(Long grupoEspecialArticulo) {
		this.grupoEspecialArticulo = grupoEspecialArticulo;
	}

}
