package com.servinte.axioma.orm;

// Generated 1/06/2011 12:09:44 PM by Hibernate Tools 3.4.0.CR1

/**
 * PeticionesServicioId generated by hbm2java
 */
public class PeticionesServicioId implements java.io.Serializable {

	private static final long serialVersionUID = -479530645097037493L;
	private int peticionQx;
	private int servicio;

	public PeticionesServicioId() {
	}

	public PeticionesServicioId(int peticionQx, int servicio) {
		this.peticionQx = peticionQx;
		this.servicio = servicio;
	}

	public int getPeticionQx() {
		return this.peticionQx;
	}

	public void setPeticionQx(int peticionQx) {
		this.peticionQx = peticionQx;
	}

	public int getServicio() {
		return this.servicio;
	}

	public void setServicio(int servicio) {
		this.servicio = servicio;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PeticionesServicioId))
			return false;
		PeticionesServicioId castOther = (PeticionesServicioId) other;

		return (this.getPeticionQx() == castOther.getPeticionQx())
				&& (this.getServicio() == castOther.getServicio());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getPeticionQx();
		result = 37 * result + this.getServicio();
		return result;
	}

}
