package com.servinte.axioma.orm;

// Generated 30/05/2011 09:37:59 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * PeticionesPosponer generated by hbm2java
 */
public class PeticionesPosponer implements java.io.Serializable {

	private long codigoPk;
	private Usuarios usuarios;
	private PeticionQx peticionQx;
	private Date fechaModifica;
	private String horaModifica;
	private Date fechaPosponer;
	private String observacion;

	public PeticionesPosponer() {
	}

	public PeticionesPosponer(long codigoPk, Usuarios usuarios,
			PeticionQx peticionQx, Date fechaModifica, String horaModifica,
			Date fechaPosponer) {
		this.codigoPk = codigoPk;
		this.usuarios = usuarios;
		this.peticionQx = peticionQx;
		this.fechaModifica = fechaModifica;
		this.horaModifica = horaModifica;
		this.fechaPosponer = fechaPosponer;
	}

	public PeticionesPosponer(long codigoPk, Usuarios usuarios,
			PeticionQx peticionQx, Date fechaModifica, String horaModifica,
			Date fechaPosponer, String observacion) {
		this.codigoPk = codigoPk;
		this.usuarios = usuarios;
		this.peticionQx = peticionQx;
		this.fechaModifica = fechaModifica;
		this.horaModifica = horaModifica;
		this.fechaPosponer = fechaPosponer;
		this.observacion = observacion;
	}

	public long getCodigoPk() {
		return this.codigoPk;
	}

	public void setCodigoPk(long codigoPk) {
		this.codigoPk = codigoPk;
	}

	public Usuarios getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(Usuarios usuarios) {
		this.usuarios = usuarios;
	}

	public PeticionQx getPeticionQx() {
		return this.peticionQx;
	}

	public void setPeticionQx(PeticionQx peticionQx) {
		this.peticionQx = peticionQx;
	}

	public Date getFechaModifica() {
		return this.fechaModifica;
	}

	public void setFechaModifica(Date fechaModifica) {
		this.fechaModifica = fechaModifica;
	}

	public String getHoraModifica() {
		return this.horaModifica;
	}

	public void setHoraModifica(String horaModifica) {
		this.horaModifica = horaModifica;
	}

	public Date getFechaPosponer() {
		return this.fechaPosponer;
	}

	public void setFechaPosponer(Date fechaPosponer) {
		this.fechaPosponer = fechaPosponer;
	}

	public String getObservacion() {
		return this.observacion;
	}

	public void setObservacion(String observacion) {
		this.observacion = observacion;
	}

}
