package com.servinte.axioma.orm;

// Generated Jan 12, 2011 9:11:28 AM by Hibernate Tools 3.2.4.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * PresupuestoOdontologico generated by hbm2java
 */
public class PresupuestoOdontologico implements java.io.Serializable {

	private long codigoPk;
	private Ingresos ingresos;
	private PlanTratamiento planTratamiento;
	private Cuentas cuentas;
	private CentroAtencion centroAtencion;
	private Pacientes pacientes;
	private Usuarios usuariosByUsuarioModifica;
	private Especialidades especialidades;
	private Usuarios usuariosByUsuarioGeneracion;
	private Instituciones instituciones;
	private String estado;
	private Integer motivo;
	private Date fechaModifica;
	private String horaModifica;
	private long consecutivo;
	private Date fechaGeneracion;
	private String horaGeneracion;
	private String migrado;
	private Set excluPresuEncabezados = new HashSet(0);
	private Set logPresupuestoOdos = new HashSet(0);
	private Set incluPresuEncabezados = new HashSet(0);
	private Set exclusionesPresupuestos = new HashSet(0);
	private Set presuPlanTtoNumSupers = new HashSet(0);
	private Set presupuestoOdoProgServs = new HashSet(0);
	private PresupuestoContratado presupuestoContratado;
	private Set presupuestoLogImpresions = new HashSet(0);
	private Set logPresupuestoOdonts = new HashSet(0);
	private Set otrosSis = new HashSet(0);
	private Set logPresupuestoDctoOdons = new HashSet(0);
	private Set presupuestoDctoOdons = new HashSet(0);
	private Set presupuestoPaqueteses = new HashSet(0);

	public PresupuestoOdontologico() {
	}

	public PresupuestoOdontologico(long codigoPk, Ingresos ingresos,
			PlanTratamiento planTratamiento, Cuentas cuentas,
			CentroAtencion centroAtencion, Pacientes pacientes,
			Usuarios usuariosByUsuarioModifica,
			Usuarios usuariosByUsuarioGeneracion, Instituciones instituciones,
			String estado, Date fechaModifica, String horaModifica,
			long consecutivo, Date fechaGeneracion, String horaGeneracion) {
		this.codigoPk = codigoPk;
		this.ingresos = ingresos;
		this.planTratamiento = planTratamiento;
		this.cuentas = cuentas;
		this.centroAtencion = centroAtencion;
		this.pacientes = pacientes;
		this.usuariosByUsuarioModifica = usuariosByUsuarioModifica;
		this.usuariosByUsuarioGeneracion = usuariosByUsuarioGeneracion;
		this.instituciones = instituciones;
		this.estado = estado;
		this.fechaModifica = fechaModifica;
		this.horaModifica = horaModifica;
		this.consecutivo = consecutivo;
		this.fechaGeneracion = fechaGeneracion;
		this.horaGeneracion = horaGeneracion;
	}

	public PresupuestoOdontologico(long codigoPk, Ingresos ingresos,
			PlanTratamiento planTratamiento, Cuentas cuentas,
			CentroAtencion centroAtencion, Pacientes pacientes,
			Usuarios usuariosByUsuarioModifica, Especialidades especialidades,
			Usuarios usuariosByUsuarioGeneracion, Instituciones instituciones,
			String estado, Integer motivo, Date fechaModifica,
			String horaModifica, long consecutivo, Date fechaGeneracion,
			String horaGeneracion, String migrado, Set excluPresuEncabezados,
			Set logPresupuestoOdos, Set incluPresuEncabezados,
			Set exclusionesPresupuestos, Set presuPlanTtoNumSupers,
			Set presupuestoOdoProgServs,
			PresupuestoContratado presupuestoContratado,
			Set presupuestoLogImpresions, Set logPresupuestoOdonts,
			Set otrosSis, Set logPresupuestoDctoOdons,
			Set presupuestoDctoOdons, Set presupuestoPaqueteses) {
		this.codigoPk = codigoPk;
		this.ingresos = ingresos;
		this.planTratamiento = planTratamiento;
		this.cuentas = cuentas;
		this.centroAtencion = centroAtencion;
		this.pacientes = pacientes;
		this.usuariosByUsuarioModifica = usuariosByUsuarioModifica;
		this.especialidades = especialidades;
		this.usuariosByUsuarioGeneracion = usuariosByUsuarioGeneracion;
		this.instituciones = instituciones;
		this.estado = estado;
		this.motivo = motivo;
		this.fechaModifica = fechaModifica;
		this.horaModifica = horaModifica;
		this.consecutivo = consecutivo;
		this.fechaGeneracion = fechaGeneracion;
		this.horaGeneracion = horaGeneracion;
		this.migrado = migrado;
		this.excluPresuEncabezados = excluPresuEncabezados;
		this.logPresupuestoOdos = logPresupuestoOdos;
		this.incluPresuEncabezados = incluPresuEncabezados;
		this.exclusionesPresupuestos = exclusionesPresupuestos;
		this.presuPlanTtoNumSupers = presuPlanTtoNumSupers;
		this.presupuestoOdoProgServs = presupuestoOdoProgServs;
		this.presupuestoContratado = presupuestoContratado;
		this.presupuestoLogImpresions = presupuestoLogImpresions;
		this.logPresupuestoOdonts = logPresupuestoOdonts;
		this.otrosSis = otrosSis;
		this.logPresupuestoDctoOdons = logPresupuestoDctoOdons;
		this.presupuestoDctoOdons = presupuestoDctoOdons;
		this.presupuestoPaqueteses = presupuestoPaqueteses;
	}

	public long getCodigoPk() {
		return this.codigoPk;
	}

	public void setCodigoPk(long codigoPk) {
		this.codigoPk = codigoPk;
	}

	public Ingresos getIngresos() {
		return this.ingresos;
	}

	public void setIngresos(Ingresos ingresos) {
		this.ingresos = ingresos;
	}

	public PlanTratamiento getPlanTratamiento() {
		return this.planTratamiento;
	}

	public void setPlanTratamiento(PlanTratamiento planTratamiento) {
		this.planTratamiento = planTratamiento;
	}

	public Cuentas getCuentas() {
		return this.cuentas;
	}

	public void setCuentas(Cuentas cuentas) {
		this.cuentas = cuentas;
	}

	public CentroAtencion getCentroAtencion() {
		return this.centroAtencion;
	}

	public void setCentroAtencion(CentroAtencion centroAtencion) {
		this.centroAtencion = centroAtencion;
	}

	public Pacientes getPacientes() {
		return this.pacientes;
	}

	public void setPacientes(Pacientes pacientes) {
		this.pacientes = pacientes;
	}

	public Usuarios getUsuariosByUsuarioModifica() {
		return this.usuariosByUsuarioModifica;
	}

	public void setUsuariosByUsuarioModifica(Usuarios usuariosByUsuarioModifica) {
		this.usuariosByUsuarioModifica = usuariosByUsuarioModifica;
	}

	public Especialidades getEspecialidades() {
		return this.especialidades;
	}

	public void setEspecialidades(Especialidades especialidades) {
		this.especialidades = especialidades;
	}

	public Usuarios getUsuariosByUsuarioGeneracion() {
		return this.usuariosByUsuarioGeneracion;
	}

	public void setUsuariosByUsuarioGeneracion(
			Usuarios usuariosByUsuarioGeneracion) {
		this.usuariosByUsuarioGeneracion = usuariosByUsuarioGeneracion;
	}

	public Instituciones getInstituciones() {
		return this.instituciones;
	}

	public void setInstituciones(Instituciones instituciones) {
		this.instituciones = instituciones;
	}

	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	public Integer getMotivo() {
		return this.motivo;
	}

	public void setMotivo(Integer motivo) {
		this.motivo = motivo;
	}

	public Date getFechaModifica() {
		return this.fechaModifica;
	}

	public void setFechaModifica(Date fechaModifica) {
		this.fechaModifica = fechaModifica;
	}

	public String getHoraModifica() {
		return this.horaModifica;
	}

	public void setHoraModifica(String horaModifica) {
		this.horaModifica = horaModifica;
	}

	public long getConsecutivo() {
		return this.consecutivo;
	}

	public void setConsecutivo(long consecutivo) {
		this.consecutivo = consecutivo;
	}

	public Date getFechaGeneracion() {
		return this.fechaGeneracion;
	}

	public void setFechaGeneracion(Date fechaGeneracion) {
		this.fechaGeneracion = fechaGeneracion;
	}

	public String getHoraGeneracion() {
		return this.horaGeneracion;
	}

	public void setHoraGeneracion(String horaGeneracion) {
		this.horaGeneracion = horaGeneracion;
	}

	public String getMigrado() {
		return this.migrado;
	}

	public void setMigrado(String migrado) {
		this.migrado = migrado;
	}

	public Set getExcluPresuEncabezados() {
		return this.excluPresuEncabezados;
	}

	public void setExcluPresuEncabezados(Set excluPresuEncabezados) {
		this.excluPresuEncabezados = excluPresuEncabezados;
	}

	public Set getLogPresupuestoOdos() {
		return this.logPresupuestoOdos;
	}

	public void setLogPresupuestoOdos(Set logPresupuestoOdos) {
		this.logPresupuestoOdos = logPresupuestoOdos;
	}

	public Set getIncluPresuEncabezados() {
		return this.incluPresuEncabezados;
	}

	public void setIncluPresuEncabezados(Set incluPresuEncabezados) {
		this.incluPresuEncabezados = incluPresuEncabezados;
	}

	public Set getExclusionesPresupuestos() {
		return this.exclusionesPresupuestos;
	}

	public void setExclusionesPresupuestos(Set exclusionesPresupuestos) {
		this.exclusionesPresupuestos = exclusionesPresupuestos;
	}

	public Set getPresuPlanTtoNumSupers() {
		return this.presuPlanTtoNumSupers;
	}

	public void setPresuPlanTtoNumSupers(Set presuPlanTtoNumSupers) {
		this.presuPlanTtoNumSupers = presuPlanTtoNumSupers;
	}

	public Set getPresupuestoOdoProgServs() {
		return this.presupuestoOdoProgServs;
	}

	public void setPresupuestoOdoProgServs(Set presupuestoOdoProgServs) {
		this.presupuestoOdoProgServs = presupuestoOdoProgServs;
	}

	public PresupuestoContratado getPresupuestoContratado() {
		return this.presupuestoContratado;
	}

	public void setPresupuestoContratado(
			PresupuestoContratado presupuestoContratado) {
		this.presupuestoContratado = presupuestoContratado;
	}

	public Set getPresupuestoLogImpresions() {
		return this.presupuestoLogImpresions;
	}

	public void setPresupuestoLogImpresions(Set presupuestoLogImpresions) {
		this.presupuestoLogImpresions = presupuestoLogImpresions;
	}

	public Set getLogPresupuestoOdonts() {
		return this.logPresupuestoOdonts;
	}

	public void setLogPresupuestoOdonts(Set logPresupuestoOdonts) {
		this.logPresupuestoOdonts = logPresupuestoOdonts;
	}

	public Set getOtrosSis() {
		return this.otrosSis;
	}

	public void setOtrosSis(Set otrosSis) {
		this.otrosSis = otrosSis;
	}

	public Set getLogPresupuestoDctoOdons() {
		return this.logPresupuestoDctoOdons;
	}

	public void setLogPresupuestoDctoOdons(Set logPresupuestoDctoOdons) {
		this.logPresupuestoDctoOdons = logPresupuestoDctoOdons;
	}

	public Set getPresupuestoDctoOdons() {
		return this.presupuestoDctoOdons;
	}

	public void setPresupuestoDctoOdons(Set presupuestoDctoOdons) {
		this.presupuestoDctoOdons = presupuestoDctoOdons;
	}

	public Set getPresupuestoPaqueteses() {
		return this.presupuestoPaqueteses;
	}

	public void setPresupuestoPaqueteses(Set presupuestoPaqueteses) {
		this.presupuestoPaqueteses = presupuestoPaqueteses;
	}

}
