package com.servinte.axioma.orm;

// Generated Apr 7, 2010 3:58:52 PM by Hibernate Tools 3.2.5.Beta

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * PromocionesOdontologicas generated by hbm2java
 */
public class PromocionesOdontologicas implements java.io.Serializable {

	private int codigoPk;
	private Usuarios usuarios;
	private Instituciones instituciones;
	private String nombre;
	private Date fechaInicialVigencia;
	private Date fechaFinalVigencia;
	private String horaInicialVigencia;
	private String horaFinalVigencia;
	private String activo;
	private Date fechaModifica;
	private String horaModifica;
	private Date fechaGeneracion;
	private Set detPromocionesOdos = new HashSet(0);

	public PromocionesOdontologicas() {
	}

	public PromocionesOdontologicas(int codigoPk, Usuarios usuarios,
			Instituciones instituciones, String nombre,
			Date fechaInicialVigencia, Date fechaFinalVigencia, String activo,
			Date fechaModifica, String horaModifica) {
		this.codigoPk = codigoPk;
		this.usuarios = usuarios;
		this.instituciones = instituciones;
		this.nombre = nombre;
		this.fechaInicialVigencia = fechaInicialVigencia;
		this.fechaFinalVigencia = fechaFinalVigencia;
		this.activo = activo;
		this.fechaModifica = fechaModifica;
		this.horaModifica = horaModifica;
	}

	public PromocionesOdontologicas(int codigoPk, Usuarios usuarios,
			Instituciones instituciones, String nombre,
			Date fechaInicialVigencia, Date fechaFinalVigencia,
			String horaInicialVigencia, String horaFinalVigencia,
			String activo, Date fechaModifica, String horaModifica,
			Date fechaGeneracion, Set detPromocionesOdos) {
		this.codigoPk = codigoPk;
		this.usuarios = usuarios;
		this.instituciones = instituciones;
		this.nombre = nombre;
		this.fechaInicialVigencia = fechaInicialVigencia;
		this.fechaFinalVigencia = fechaFinalVigencia;
		this.horaInicialVigencia = horaInicialVigencia;
		this.horaFinalVigencia = horaFinalVigencia;
		this.activo = activo;
		this.fechaModifica = fechaModifica;
		this.horaModifica = horaModifica;
		this.fechaGeneracion = fechaGeneracion;
		this.detPromocionesOdos = detPromocionesOdos;
	}

	public int getCodigoPk() {
		return this.codigoPk;
	}

	public void setCodigoPk(int codigoPk) {
		this.codigoPk = codigoPk;
	}

	public Usuarios getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(Usuarios usuarios) {
		this.usuarios = usuarios;
	}

	public Instituciones getInstituciones() {
		return this.instituciones;
	}

	public void setInstituciones(Instituciones instituciones) {
		this.instituciones = instituciones;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Date getFechaInicialVigencia() {
		return this.fechaInicialVigencia;
	}

	public void setFechaInicialVigencia(Date fechaInicialVigencia) {
		this.fechaInicialVigencia = fechaInicialVigencia;
	}

	public Date getFechaFinalVigencia() {
		return this.fechaFinalVigencia;
	}

	public void setFechaFinalVigencia(Date fechaFinalVigencia) {
		this.fechaFinalVigencia = fechaFinalVigencia;
	}

	public String getHoraInicialVigencia() {
		return this.horaInicialVigencia;
	}

	public void setHoraInicialVigencia(String horaInicialVigencia) {
		this.horaInicialVigencia = horaInicialVigencia;
	}

	public String getHoraFinalVigencia() {
		return this.horaFinalVigencia;
	}

	public void setHoraFinalVigencia(String horaFinalVigencia) {
		this.horaFinalVigencia = horaFinalVigencia;
	}

	public String getActivo() {
		return this.activo;
	}

	public void setActivo(String activo) {
		this.activo = activo;
	}

	public Date getFechaModifica() {
		return this.fechaModifica;
	}

	public void setFechaModifica(Date fechaModifica) {
		this.fechaModifica = fechaModifica;
	}

	public String getHoraModifica() {
		return this.horaModifica;
	}

	public void setHoraModifica(String horaModifica) {
		this.horaModifica = horaModifica;
	}

	public Date getFechaGeneracion() {
		return this.fechaGeneracion;
	}

	public void setFechaGeneracion(Date fechaGeneracion) {
		this.fechaGeneracion = fechaGeneracion;
	}

	public Set getDetPromocionesOdos() {
		return this.detPromocionesOdos;
	}

	public void setDetPromocionesOdos(Set detPromocionesOdos) {
		this.detPromocionesOdos = detPromocionesOdos;
	}

}
