package com.servinte.axioma.orm;

// Generated Apr 7, 2010 3:58:52 PM by Hibernate Tools 3.2.5.Beta

/**
 * SeccionXCampoId generated by hbm2java
 */
public class SeccionXCampoId implements java.io.Serializable {

	private int codigoSeccion;
	private int campo;

	public SeccionXCampoId() {
	}

	public SeccionXCampoId(int codigoSeccion, int campo) {
		this.codigoSeccion = codigoSeccion;
		this.campo = campo;
	}

	public int getCodigoSeccion() {
		return this.codigoSeccion;
	}

	public void setCodigoSeccion(int codigoSeccion) {
		this.codigoSeccion = codigoSeccion;
	}

	public int getCampo() {
		return this.campo;
	}

	public void setCampo(int campo) {
		this.campo = campo;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SeccionXCampoId))
			return false;
		SeccionXCampoId castOther = (SeccionXCampoId) other;

		return (this.getCodigoSeccion() == castOther.getCodigoSeccion())
				&& (this.getCampo() == castOther.getCampo());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCodigoSeccion();
		result = 37 * result + this.getCampo();
		return result;
	}

}
