package com.servinte.axioma.orm;

// Generated Dec 15, 2010 5:58:33 PM by Hibernate Tools 3.2.4.GA

import java.util.Date;

/**
 * SolicitudesPosponer generated by hbm2java
 */
public class SolicitudesPosponer implements java.io.Serializable {

	private long codigoPk;
	private Solicitudes solicitudes;
	private Usuarios usuarios;
	private Date fechaModifica;
	private String horaModifica;
	private Date fechaPosponer;
	private String observacion;

	public SolicitudesPosponer() {
	}

	public SolicitudesPosponer(long codigoPk, Solicitudes solicitudes,
			Usuarios usuarios, Date fechaModifica, String horaModifica,
			Date fechaPosponer) {
		this.codigoPk = codigoPk;
		this.solicitudes = solicitudes;
		this.usuarios = usuarios;
		this.fechaModifica = fechaModifica;
		this.horaModifica = horaModifica;
		this.fechaPosponer = fechaPosponer;
	}

	public SolicitudesPosponer(long codigoPk, Solicitudes solicitudes,
			Usuarios usuarios, Date fechaModifica, String horaModifica,
			Date fechaPosponer, String observacion) {
		this.codigoPk = codigoPk;
		this.solicitudes = solicitudes;
		this.usuarios = usuarios;
		this.fechaModifica = fechaModifica;
		this.horaModifica = horaModifica;
		this.fechaPosponer = fechaPosponer;
		this.observacion = observacion;
	}

	public long getCodigoPk() {
		return this.codigoPk;
	}

	public void setCodigoPk(long codigoPk) {
		this.codigoPk = codigoPk;
	}

	public Solicitudes getSolicitudes() {
		return this.solicitudes;
	}

	public void setSolicitudes(Solicitudes solicitudes) {
		this.solicitudes = solicitudes;
	}

	public Usuarios getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(Usuarios usuarios) {
		this.usuarios = usuarios;
	}

	public Date getFechaModifica() {
		return this.fechaModifica;
	}

	public void setFechaModifica(Date fechaModifica) {
		this.fechaModifica = fechaModifica;
	}

	public String getHoraModifica() {
		return this.horaModifica;
	}

	public void setHoraModifica(String horaModifica) {
		this.horaModifica = horaModifica;
	}

	public Date getFechaPosponer() {
		return this.fechaPosponer;
	}

	public void setFechaPosponer(Date fechaPosponer) {
		this.fechaPosponer = fechaPosponer;
	}

	public String getObservacion() {
		return this.observacion;
	}

	public void setObservacion(String observacion) {
		this.observacion = observacion;
	}

}
