package com.servinte.axioma.orm;

// Generated Apr 7, 2010 3:58:52 PM by Hibernate Tools 3.2.5.Beta

import java.util.HashSet;
import java.util.Set;

/**
 * TiposEntFinancieras generated by hbm2java
 */
public class TiposEntFinancieras implements java.io.Serializable {

	private int codigo;
	private String descripcion;
	private Set entidadesFinancierases = new HashSet(0);

	public TiposEntFinancieras() {
	}

	public TiposEntFinancieras(int codigo, String descripcion) {
		this.codigo = codigo;
		this.descripcion = descripcion;
	}

	public TiposEntFinancieras(int codigo, String descripcion,
			Set entidadesFinancierases) {
		this.codigo = codigo;
		this.descripcion = descripcion;
		this.entidadesFinancierases = entidadesFinancierases;
	}

	public int getCodigo() {
		return this.codigo;
	}

	public void setCodigo(int codigo) {
		this.codigo = codigo;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Set getEntidadesFinancierases() {
		return this.entidadesFinancierases;
	}

	public void setEntidadesFinancierases(Set entidadesFinancierases) {
		this.entidadesFinancierases = entidadesFinancierases;
	}

}
