package com.servinte.axioma.orm;

// Generated Apr 7, 2010 3:58:52 PM by Hibernate Tools 3.2.5.Beta

import java.util.HashSet;
import java.util.Set;

/**
 * TiposDiagnostico generated by hbm2java
 */
public class TiposDiagnostico implements java.io.Serializable {

	private int codigo;
	private String nombre;
	private String acronimo;
	private Set ripsConsultorioses = new HashSet(0);
	private Set valoracionesOdontos = new HashSet(0);

	public TiposDiagnostico() {
	}

	public TiposDiagnostico(int codigo, String acronimo) {
		this.codigo = codigo;
		this.acronimo = acronimo;
	}

	public TiposDiagnostico(int codigo, String nombre, String acronimo,
			Set ripsConsultorioses, Set valoracionesOdontos) {
		this.codigo = codigo;
		this.nombre = nombre;
		this.acronimo = acronimo;
		this.ripsConsultorioses = ripsConsultorioses;
		this.valoracionesOdontos = valoracionesOdontos;
	}

	public int getCodigo() {
		return this.codigo;
	}

	public void setCodigo(int codigo) {
		this.codigo = codigo;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getAcronimo() {
		return this.acronimo;
	}

	public void setAcronimo(String acronimo) {
		this.acronimo = acronimo;
	}

	public Set getRipsConsultorioses() {
		return this.ripsConsultorioses;
	}

	public void setRipsConsultorioses(Set ripsConsultorioses) {
		this.ripsConsultorioses = ripsConsultorioses;
	}

	public Set getValoracionesOdontos() {
		return this.valoracionesOdontos;
	}

	public void setValoracionesOdontos(Set valoracionesOdontos) {
		this.valoracionesOdontos = valoracionesOdontos;
	}

}
