package com.servinte.axioma.orm;

// Generated Apr 7, 2010 3:58:52 PM by Hibernate Tools 3.2.5.Beta

import java.util.HashSet;
import java.util.Set;

/**
 * TipoServVehiculos generated by hbm2java
 */
public class TipoServVehiculos implements java.io.Serializable {

	private int codigo;
	private String descripcion;
	private Set registroAccidentesTransitos = new HashSet(0);

	public TipoServVehiculos() {
	}

	public TipoServVehiculos(int codigo, String descripcion) {
		this.codigo = codigo;
		this.descripcion = descripcion;
	}

	public TipoServVehiculos(int codigo, String descripcion,
			Set registroAccidentesTransitos) {
		this.codigo = codigo;
		this.descripcion = descripcion;
		this.registroAccidentesTransitos = registroAccidentesTransitos;
	}

	public int getCodigo() {
		return this.codigo;
	}

	public void setCodigo(int codigo) {
		this.codigo = codigo;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Set getRegistroAccidentesTransitos() {
		return this.registroAccidentesTransitos;
	}

	public void setRegistroAccidentesTransitos(Set registroAccidentesTransitos) {
		this.registroAccidentesTransitos = registroAccidentesTransitos;
	}

}
