package com.servinte.axioma.orm;

// Generated Apr 7, 2010 3:58:52 PM by Hibernate Tools 3.2.5.Beta

import java.util.HashSet;
import java.util.Set;

/**
 * TiposLiquidacionSoat generated by hbm2java
 */
public class TiposLiquidacionSoat implements java.io.Serializable {

	private int codigo;
	private String nombre;
	private String acronimo;
	private Set tarifasSoats = new HashSet(0);
	private Set logTarifasServicioses = new HashSet(0);
	private Set tarifasIsses = new HashSet(0);

	public TiposLiquidacionSoat() {
	}

	public TiposLiquidacionSoat(int codigo, String nombre, String acronimo) {
		this.codigo = codigo;
		this.nombre = nombre;
		this.acronimo = acronimo;
	}

	public TiposLiquidacionSoat(int codigo, String nombre, String acronimo,
			Set tarifasSoats, Set logTarifasServicioses, Set tarifasIsses) {
		this.codigo = codigo;
		this.nombre = nombre;
		this.acronimo = acronimo;
		this.tarifasSoats = tarifasSoats;
		this.logTarifasServicioses = logTarifasServicioses;
		this.tarifasIsses = tarifasIsses;
	}

	public int getCodigo() {
		return this.codigo;
	}

	public void setCodigo(int codigo) {
		this.codigo = codigo;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getAcronimo() {
		return this.acronimo;
	}

	public void setAcronimo(String acronimo) {
		this.acronimo = acronimo;
	}

	public Set getTarifasSoats() {
		return this.tarifasSoats;
	}

	public void setTarifasSoats(Set tarifasSoats) {
		this.tarifasSoats = tarifasSoats;
	}

	public Set getLogTarifasServicioses() {
		return this.logTarifasServicioses;
	}

	public void setLogTarifasServicioses(Set logTarifasServicioses) {
		this.logTarifasServicioses = logTarifasServicioses;
	}

	public Set getTarifasIsses() {
		return this.tarifasIsses;
	}

	public void setTarifasIsses(Set tarifasIsses) {
		this.tarifasIsses = tarifasIsses;
	}

}
