package com.servinte.axioma.orm;

// Generated Jan 28, 2011 9:03:28 AM by Hibernate Tools 3.2.4.GA

import java.math.BigDecimal;
import java.util.Date;

/**
 * UsoConsecutivosCaducados generated by hbm2java
 */
public class UsoConsecutivosCaducados implements java.io.Serializable {

	private long codigo;
	private String nombre;
	private int institucion;
	private String anioVigencia;
	private BigDecimal valor;
	private Date fechaToma;

	public UsoConsecutivosCaducados() {
	}

	public UsoConsecutivosCaducados(long codigo, String nombre,
			int institucion, BigDecimal valor, Date fechaToma) {
		this.codigo = codigo;
		this.nombre = nombre;
		this.institucion = institucion;
		this.valor = valor;
		this.fechaToma = fechaToma;
	}

	public UsoConsecutivosCaducados(long codigo, String nombre,
			int institucion, String anioVigencia, BigDecimal valor,
			Date fechaToma) {
		this.codigo = codigo;
		this.nombre = nombre;
		this.institucion = institucion;
		this.anioVigencia = anioVigencia;
		this.valor = valor;
		this.fechaToma = fechaToma;
	}

	public long getCodigo() {
		return this.codigo;
	}

	public void setCodigo(long codigo) {
		this.codigo = codigo;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public int getInstitucion() {
		return this.institucion;
	}

	public void setInstitucion(int institucion) {
		this.institucion = institucion;
	}

	public String getAnioVigencia() {
		return this.anioVigencia;
	}

	public void setAnioVigencia(String anioVigencia) {
		this.anioVigencia = anioVigencia;
	}

	public BigDecimal getValor() {
		return this.valor;
	}

	public void setValor(BigDecimal valor) {
		this.valor = valor;
	}

	public Date getFechaToma() {
		return this.fechaToma;
	}

	public void setFechaToma(Date fechaToma) {
		this.fechaToma = fechaToma;
	}

}
