package com.servinte.axioma.orm;

// Generated Nov 30, 2010 11:44:21 AM by Hibernate Tools 3.2.4.GA

/**
 * ValoracionEnfermeria generated by hbm2java
 */
public class ValoracionEnfermeria implements java.io.Serializable {

	private int codigoPk;
	private SeccionesValEnfermeria seccionesValEnfermeria;
	private CamposValEnfermeria camposValEnfermeria;
	private CentrosCosto centrosCosto;
	private int codigoHistoEnca;
	private String etiquietaCampo;
	private String etiquetaSeccion;
	private int ordenSeccion;
	private int ordenCampo;
	private String valor;
	private String campoOtro;

	public ValoracionEnfermeria() {
	}

	public ValoracionEnfermeria(int codigoPk, int codigoHistoEnca,
			String etiquietaCampo, int ordenSeccion, int ordenCampo,
			String campoOtro) {
		this.codigoPk = codigoPk;
		this.codigoHistoEnca = codigoHistoEnca;
		this.etiquietaCampo = etiquietaCampo;
		this.ordenSeccion = ordenSeccion;
		this.ordenCampo = ordenCampo;
		this.campoOtro = campoOtro;
	}

	public ValoracionEnfermeria(int codigoPk,
			SeccionesValEnfermeria seccionesValEnfermeria,
			CamposValEnfermeria camposValEnfermeria, CentrosCosto centrosCosto,
			int codigoHistoEnca, String etiquietaCampo, String etiquetaSeccion,
			int ordenSeccion, int ordenCampo, String valor, String campoOtro) {
		this.codigoPk = codigoPk;
		this.seccionesValEnfermeria = seccionesValEnfermeria;
		this.camposValEnfermeria = camposValEnfermeria;
		this.centrosCosto = centrosCosto;
		this.codigoHistoEnca = codigoHistoEnca;
		this.etiquietaCampo = etiquietaCampo;
		this.etiquetaSeccion = etiquetaSeccion;
		this.ordenSeccion = ordenSeccion;
		this.ordenCampo = ordenCampo;
		this.valor = valor;
		this.campoOtro = campoOtro;
	}

	public int getCodigoPk() {
		return this.codigoPk;
	}

	public void setCodigoPk(int codigoPk) {
		this.codigoPk = codigoPk;
	}

	public SeccionesValEnfermeria getSeccionesValEnfermeria() {
		return this.seccionesValEnfermeria;
	}

	public void setSeccionesValEnfermeria(
			SeccionesValEnfermeria seccionesValEnfermeria) {
		this.seccionesValEnfermeria = seccionesValEnfermeria;
	}

	public CamposValEnfermeria getCamposValEnfermeria() {
		return this.camposValEnfermeria;
	}

	public void setCamposValEnfermeria(CamposValEnfermeria camposValEnfermeria) {
		this.camposValEnfermeria = camposValEnfermeria;
	}

	public CentrosCosto getCentrosCosto() {
		return this.centrosCosto;
	}

	public void setCentrosCosto(CentrosCosto centrosCosto) {
		this.centrosCosto = centrosCosto;
	}

	public int getCodigoHistoEnca() {
		return this.codigoHistoEnca;
	}

	public void setCodigoHistoEnca(int codigoHistoEnca) {
		this.codigoHistoEnca = codigoHistoEnca;
	}

	public String getEtiquietaCampo() {
		return this.etiquietaCampo;
	}

	public void setEtiquietaCampo(String etiquietaCampo) {
		this.etiquietaCampo = etiquietaCampo;
	}

	public String getEtiquetaSeccion() {
		return this.etiquetaSeccion;
	}

	public void setEtiquetaSeccion(String etiquetaSeccion) {
		this.etiquetaSeccion = etiquetaSeccion;
	}

	public int getOrdenSeccion() {
		return this.ordenSeccion;
	}

	public void setOrdenSeccion(int ordenSeccion) {
		this.ordenSeccion = ordenSeccion;
	}

	public int getOrdenCampo() {
		return this.ordenCampo;
	}

	public void setOrdenCampo(int ordenCampo) {
		this.ordenCampo = ordenCampo;
	}

	public String getValor() {
		return this.valor;
	}

	public void setValor(String valor) {
		this.valor = valor;
	}

	public String getCampoOtro() {
		return this.campoOtro;
	}

	public void setCampoOtro(String campoOtro) {
		this.campoOtro = campoOtro;
	}

}
