package com.servinte.axioma.orm;

// Generated Apr 7, 2010 3:58:52 PM by Hibernate Tools 3.2.5.Beta

/**
 * ViewTempDx generated by hbm2java
 */
public class ViewTempDx implements java.io.Serializable {

	private ViewTempDxId id;

	public ViewTempDx() {
	}

	public ViewTempDx(ViewTempDxId id) {
		this.id = id;
	}

	public ViewTempDxId getId() {
		return this.id;
	}

	public void setId(ViewTempDxId id) {
		this.id = id;
	}

}
