package com.servinte.axioma.orm;

// Generated Apr 7, 2010 3:58:52 PM by Hibernate Tools 3.2.5.Beta

/**
 * ViewCensoHsubaId generated by hbm2java
 */
public class ViewCensoHsubaId implements java.io.Serializable {

	private String paciente;
	private String centroAtencion;
	private String area;
	private Integer habitacion;
	private String numeroCama;
	private String nombreCama;
	private Integer cuenta;

	public ViewCensoHsubaId() {
	}

	public ViewCensoHsubaId(String paciente, String centroAtencion,
			String area, Integer habitacion, String numeroCama,
			String nombreCama, Integer cuenta) {
		this.paciente = paciente;
		this.centroAtencion = centroAtencion;
		this.area = area;
		this.habitacion = habitacion;
		this.numeroCama = numeroCama;
		this.nombreCama = nombreCama;
		this.cuenta = cuenta;
	}

	public String getPaciente() {
		return this.paciente;
	}

	public void setPaciente(String paciente) {
		this.paciente = paciente;
	}

	public String getCentroAtencion() {
		return this.centroAtencion;
	}

	public void setCentroAtencion(String centroAtencion) {
		this.centroAtencion = centroAtencion;
	}

	public String getArea() {
		return this.area;
	}

	public void setArea(String area) {
		this.area = area;
	}

	public Integer getHabitacion() {
		return this.habitacion;
	}

	public void setHabitacion(Integer habitacion) {
		this.habitacion = habitacion;
	}

	public String getNumeroCama() {
		return this.numeroCama;
	}

	public void setNumeroCama(String numeroCama) {
		this.numeroCama = numeroCama;
	}

	public String getNombreCama() {
		return this.nombreCama;
	}

	public void setNombreCama(String nombreCama) {
		this.nombreCama = nombreCama;
	}

	public Integer getCuenta() {
		return this.cuenta;
	}

	public void setCuenta(Integer cuenta) {
		this.cuenta = cuenta;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ViewCensoHsubaId))
			return false;
		ViewCensoHsubaId castOther = (ViewCensoHsubaId) other;

		return ((this.getPaciente() == castOther.getPaciente()) || (this
				.getPaciente() != null
				&& castOther.getPaciente() != null && this.getPaciente()
				.equals(castOther.getPaciente())))
				&& ((this.getCentroAtencion() == castOther.getCentroAtencion()) || (this
						.getCentroAtencion() != null
						&& castOther.getCentroAtencion() != null && this
						.getCentroAtencion().equals(
								castOther.getCentroAtencion())))
				&& ((this.getArea() == castOther.getArea()) || (this.getArea() != null
						&& castOther.getArea() != null && this.getArea()
						.equals(castOther.getArea())))
				&& ((this.getHabitacion() == castOther.getHabitacion()) || (this
						.getHabitacion() != null
						&& castOther.getHabitacion() != null && this
						.getHabitacion().equals(castOther.getHabitacion())))
				&& ((this.getNumeroCama() == castOther.getNumeroCama()) || (this
						.getNumeroCama() != null
						&& castOther.getNumeroCama() != null && this
						.getNumeroCama().equals(castOther.getNumeroCama())))
				&& ((this.getNombreCama() == castOther.getNombreCama()) || (this
						.getNombreCama() != null
						&& castOther.getNombreCama() != null && this
						.getNombreCama().equals(castOther.getNombreCama())))
				&& ((this.getCuenta() == castOther.getCuenta()) || (this
						.getCuenta() != null
						&& castOther.getCuenta() != null && this.getCuenta()
						.equals(castOther.getCuenta())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getPaciente() == null ? 0 : this.getPaciente().hashCode());
		result = 37
				* result
				+ (getCentroAtencion() == null ? 0 : this.getCentroAtencion()
						.hashCode());
		result = 37 * result
				+ (getArea() == null ? 0 : this.getArea().hashCode());
		result = 37
				* result
				+ (getHabitacion() == null ? 0 : this.getHabitacion()
						.hashCode());
		result = 37
				* result
				+ (getNumeroCama() == null ? 0 : this.getNumeroCama()
						.hashCode());
		result = 37
				* result
				+ (getNombreCama() == null ? 0 : this.getNombreCama()
						.hashCode());
		result = 37 * result
				+ (getCuenta() == null ? 0 : this.getCuenta().hashCode());
		return result;
	}

}
