package com.servinte.axioma.orm;

// Generated Apr 7, 2010 3:58:52 PM by Hibernate Tools 3.2.5.Beta

/**
 * ViewTempDxSecId generated by hbm2java
 */
public class ViewTempDxSecId implements java.io.Serializable {

	private Integer valoracion;
	private String acronimoDiagnostico;
	private Integer tipoCieDiagnostico;

	public ViewTempDxSecId() {
	}

	public ViewTempDxSecId(Integer valoracion, String acronimoDiagnostico,
			Integer tipoCieDiagnostico) {
		this.valoracion = valoracion;
		this.acronimoDiagnostico = acronimoDiagnostico;
		this.tipoCieDiagnostico = tipoCieDiagnostico;
	}

	public Integer getValoracion() {
		return this.valoracion;
	}

	public void setValoracion(Integer valoracion) {
		this.valoracion = valoracion;
	}

	public String getAcronimoDiagnostico() {
		return this.acronimoDiagnostico;
	}

	public void setAcronimoDiagnostico(String acronimoDiagnostico) {
		this.acronimoDiagnostico = acronimoDiagnostico;
	}

	public Integer getTipoCieDiagnostico() {
		return this.tipoCieDiagnostico;
	}

	public void setTipoCieDiagnostico(Integer tipoCieDiagnostico) {
		this.tipoCieDiagnostico = tipoCieDiagnostico;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ViewTempDxSecId))
			return false;
		ViewTempDxSecId castOther = (ViewTempDxSecId) other;

		return ((this.getValoracion() == castOther.getValoracion()) || (this
				.getValoracion() != null
				&& castOther.getValoracion() != null && this.getValoracion()
				.equals(castOther.getValoracion())))
				&& ((this.getAcronimoDiagnostico() == castOther
						.getAcronimoDiagnostico()) || (this
						.getAcronimoDiagnostico() != null
						&& castOther.getAcronimoDiagnostico() != null && this
						.getAcronimoDiagnostico().equals(
								castOther.getAcronimoDiagnostico())))
				&& ((this.getTipoCieDiagnostico() == castOther
						.getTipoCieDiagnostico()) || (this
						.getTipoCieDiagnostico() != null
						&& castOther.getTipoCieDiagnostico() != null && this
						.getTipoCieDiagnostico().equals(
								castOther.getTipoCieDiagnostico())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getValoracion() == null ? 0 : this.getValoracion()
						.hashCode());
		result = 37
				* result
				+ (getAcronimoDiagnostico() == null ? 0 : this
						.getAcronimoDiagnostico().hashCode());
		result = 37
				* result
				+ (getTipoCieDiagnostico() == null ? 0 : this
						.getTipoCieDiagnostico().hashCode());
		return result;
	}

}
