package com.servinte.axioma.orm;

// Generated Apr 7, 2010 3:58:52 PM by Hibernate Tools 3.2.5.Beta

/**
 * ViewDietasHsubaId generated by hbm2java
 */
public class ViewDietasHsubaId implements java.io.Serializable {

	private Integer consecutivoDieta;
	private Boolean viaOral;
	private String dieta;
	private Integer cuenta;
	private String profesionalResponsable;

	public ViewDietasHsubaId() {
	}

	public ViewDietasHsubaId(Integer consecutivoDieta, Boolean viaOral,
			String dieta, Integer cuenta, String profesionalResponsable) {
		this.consecutivoDieta = consecutivoDieta;
		this.viaOral = viaOral;
		this.dieta = dieta;
		this.cuenta = cuenta;
		this.profesionalResponsable = profesionalResponsable;
	}

	public Integer getConsecutivoDieta() {
		return this.consecutivoDieta;
	}

	public void setConsecutivoDieta(Integer consecutivoDieta) {
		this.consecutivoDieta = consecutivoDieta;
	}

	public Boolean getViaOral() {
		return this.viaOral;
	}

	public void setViaOral(Boolean viaOral) {
		this.viaOral = viaOral;
	}

	public String getDieta() {
		return this.dieta;
	}

	public void setDieta(String dieta) {
		this.dieta = dieta;
	}

	public Integer getCuenta() {
		return this.cuenta;
	}

	public void setCuenta(Integer cuenta) {
		this.cuenta = cuenta;
	}

	public String getProfesionalResponsable() {
		return this.profesionalResponsable;
	}

	public void setProfesionalResponsable(String profesionalResponsable) {
		this.profesionalResponsable = profesionalResponsable;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ViewDietasHsubaId))
			return false;
		ViewDietasHsubaId castOther = (ViewDietasHsubaId) other;

		return ((this.getConsecutivoDieta() == castOther.getConsecutivoDieta()) || (this
				.getConsecutivoDieta() != null
				&& castOther.getConsecutivoDieta() != null && this
				.getConsecutivoDieta().equals(castOther.getConsecutivoDieta())))
				&& ((this.getViaOral() == castOther.getViaOral()) || (this
						.getViaOral() != null
						&& castOther.getViaOral() != null && this.getViaOral()
						.equals(castOther.getViaOral())))
				&& ((this.getDieta() == castOther.getDieta()) || (this
						.getDieta() != null
						&& castOther.getDieta() != null && this.getDieta()
						.equals(castOther.getDieta())))
				&& ((this.getCuenta() == castOther.getCuenta()) || (this
						.getCuenta() != null
						&& castOther.getCuenta() != null && this.getCuenta()
						.equals(castOther.getCuenta())))
				&& ((this.getProfesionalResponsable() == castOther
						.getProfesionalResponsable()) || (this
						.getProfesionalResponsable() != null
						&& castOther.getProfesionalResponsable() != null && this
						.getProfesionalResponsable().equals(
								castOther.getProfesionalResponsable())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getConsecutivoDieta() == null ? 0 : this
						.getConsecutivoDieta().hashCode());
		result = 37 * result
				+ (getViaOral() == null ? 0 : this.getViaOral().hashCode());
		result = 37 * result
				+ (getDieta() == null ? 0 : this.getDieta().hashCode());
		result = 37 * result
				+ (getCuenta() == null ? 0 : this.getCuenta().hashCode());
		result = 37
				* result
				+ (getProfesionalResponsable() == null ? 0 : this
						.getProfesionalResponsable().hashCode());
		return result;
	}

}
