package com.servinte.axioma.orm;

// Generated Apr 7, 2010 3:58:52 PM by Hibernate Tools 3.2.5.Beta

/**
 * ViewTarifasIss generated by hbm2java
 */
public class ViewTarifasIss implements java.io.Serializable {

	private ViewTarifasIssId id;

	public ViewTarifasIss() {
	}

	public ViewTarifasIss(ViewTarifasIssId id) {
		this.id = id;
	}

	public ViewTarifasIssId getId() {
		return this.id;
	}

	public void setId(ViewTarifasIssId id) {
		this.id = id;
	}

}
