package com.servinte.axioma.orm;

// Generated Apr 7, 2010 3:58:52 PM by Hibernate Tools 3.2.5.Beta

/**
 * ViewDetServArtFactId generated by hbm2java
 */
public class ViewDetServArtFactId implements java.io.Serializable {

	private Integer codigofactura;
	private Integer numerosolicitud;
	private Integer codigoservicioarticulo;
	private String descripcionservicioarticulo;
	private Double valortotal;
	private Double valorajustes;
	private Double saldo;
	private String tipo;
	private Integer codigotiposolicitud;

	public ViewDetServArtFactId() {
	}

	public ViewDetServArtFactId(Integer codigofactura, Integer numerosolicitud,
			Integer codigoservicioarticulo, String descripcionservicioarticulo,
			Double valortotal, Double valorajustes, Double saldo, String tipo,
			Integer codigotiposolicitud) {
		this.codigofactura = codigofactura;
		this.numerosolicitud = numerosolicitud;
		this.codigoservicioarticulo = codigoservicioarticulo;
		this.descripcionservicioarticulo = descripcionservicioarticulo;
		this.valortotal = valortotal;
		this.valorajustes = valorajustes;
		this.saldo = saldo;
		this.tipo = tipo;
		this.codigotiposolicitud = codigotiposolicitud;
	}

	public Integer getCodigofactura() {
		return this.codigofactura;
	}

	public void setCodigofactura(Integer codigofactura) {
		this.codigofactura = codigofactura;
	}

	public Integer getNumerosolicitud() {
		return this.numerosolicitud;
	}

	public void setNumerosolicitud(Integer numerosolicitud) {
		this.numerosolicitud = numerosolicitud;
	}

	public Integer getCodigoservicioarticulo() {
		return this.codigoservicioarticulo;
	}

	public void setCodigoservicioarticulo(Integer codigoservicioarticulo) {
		this.codigoservicioarticulo = codigoservicioarticulo;
	}

	public String getDescripcionservicioarticulo() {
		return this.descripcionservicioarticulo;
	}

	public void setDescripcionservicioarticulo(
			String descripcionservicioarticulo) {
		this.descripcionservicioarticulo = descripcionservicioarticulo;
	}

	public Double getValortotal() {
		return this.valortotal;
	}

	public void setValortotal(Double valortotal) {
		this.valortotal = valortotal;
	}

	public Double getValorajustes() {
		return this.valorajustes;
	}

	public void setValorajustes(Double valorajustes) {
		this.valorajustes = valorajustes;
	}

	public Double getSaldo() {
		return this.saldo;
	}

	public void setSaldo(Double saldo) {
		this.saldo = saldo;
	}

	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	public Integer getCodigotiposolicitud() {
		return this.codigotiposolicitud;
	}

	public void setCodigotiposolicitud(Integer codigotiposolicitud) {
		this.codigotiposolicitud = codigotiposolicitud;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ViewDetServArtFactId))
			return false;
		ViewDetServArtFactId castOther = (ViewDetServArtFactId) other;

		return ((this.getCodigofactura() == castOther.getCodigofactura()) || (this
				.getCodigofactura() != null
				&& castOther.getCodigofactura() != null && this
				.getCodigofactura().equals(castOther.getCodigofactura())))
				&& ((this.getNumerosolicitud() == castOther
						.getNumerosolicitud()) || (this.getNumerosolicitud() != null
						&& castOther.getNumerosolicitud() != null && this
						.getNumerosolicitud().equals(
								castOther.getNumerosolicitud())))
				&& ((this.getCodigoservicioarticulo() == castOther
						.getCodigoservicioarticulo()) || (this
						.getCodigoservicioarticulo() != null
						&& castOther.getCodigoservicioarticulo() != null && this
						.getCodigoservicioarticulo().equals(
								castOther.getCodigoservicioarticulo())))
				&& ((this.getDescripcionservicioarticulo() == castOther
						.getDescripcionservicioarticulo()) || (this
						.getDescripcionservicioarticulo() != null
						&& castOther.getDescripcionservicioarticulo() != null && this
						.getDescripcionservicioarticulo().equals(
								castOther.getDescripcionservicioarticulo())))
				&& ((this.getValortotal() == castOther.getValortotal()) || (this
						.getValortotal() != null
						&& castOther.getValortotal() != null && this
						.getValortotal().equals(castOther.getValortotal())))
				&& ((this.getValorajustes() == castOther.getValorajustes()) || (this
						.getValorajustes() != null
						&& castOther.getValorajustes() != null && this
						.getValorajustes().equals(castOther.getValorajustes())))
				&& ((this.getSaldo() == castOther.getSaldo()) || (this
						.getSaldo() != null
						&& castOther.getSaldo() != null && this.getSaldo()
						.equals(castOther.getSaldo())))
				&& ((this.getTipo() == castOther.getTipo()) || (this.getTipo() != null
						&& castOther.getTipo() != null && this.getTipo()
						.equals(castOther.getTipo())))
				&& ((this.getCodigotiposolicitud() == castOther
						.getCodigotiposolicitud()) || (this
						.getCodigotiposolicitud() != null
						&& castOther.getCodigotiposolicitud() != null && this
						.getCodigotiposolicitud().equals(
								castOther.getCodigotiposolicitud())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getCodigofactura() == null ? 0 : this.getCodigofactura()
						.hashCode());
		result = 37
				* result
				+ (getNumerosolicitud() == null ? 0 : this.getNumerosolicitud()
						.hashCode());
		result = 37
				* result
				+ (getCodigoservicioarticulo() == null ? 0 : this
						.getCodigoservicioarticulo().hashCode());
		result = 37
				* result
				+ (getDescripcionservicioarticulo() == null ? 0 : this
						.getDescripcionservicioarticulo().hashCode());
		result = 37
				* result
				+ (getValortotal() == null ? 0 : this.getValortotal()
						.hashCode());
		result = 37
				* result
				+ (getValorajustes() == null ? 0 : this.getValorajustes()
						.hashCode());
		result = 37 * result
				+ (getSaldo() == null ? 0 : this.getSaldo().hashCode());
		result = 37 * result
				+ (getTipo() == null ? 0 : this.getTipo().hashCode());
		result = 37
				* result
				+ (getCodigotiposolicitud() == null ? 0 : this
						.getCodigotiposolicitud().hashCode());
		return result;
	}

}
