package com.sysmedica.dao.oracle;

import java.sql.Connection;
import java.sql.ResultSet;

import com.sysmedica.dao.FichaLesionesDao;
import com.sysmedica.dao.sqlbase.SqlBaseFichaLesionesDao;

public class OracleFichaLesionesDao implements FichaLesionesDao {

	private String secuenciaStr = "SELECT seq_fichas.nextval FROM dual";
	
	public int insertarFicha(Connection con,
								boolean notificar,
							    String loginUsuario,
							    int codigoFichaVIH,
							    int codigoPaciente,
							    String codigoDiagnostico,
							    int codigoNotificacion,
							    int numeroSolicitud,
							    int estado,
							    int codigoAseguradora,
								String nombreProfesional
							    )
	{
		return SqlBaseFichaLesionesDao.insertarFicha(con,
														numeroSolicitud,
														loginUsuario,
														codigoPaciente,
														codigoDiagnostico,
														estado,
														codigoAseguradora,
														nombreProfesional,
													    secuenciaStr);
	}



	public int modificarFicha(Connection con,
									String sire,
									boolean notificar,
								    String loginUsuario,
								    int codigoFichaInfecciones,
								    int codigoPaciente,
								    String codigoDiagnostico,
								    int codigoNotificacion,
								    int numeroSolicitud,
								    int estado,
								    
								    int estadoIngreso,
								    String fechaOcurrencia,
								    int horaOcurrencia,
								    String lugarOcurrencia,
								    int localidad,
								    String municipioOcurrencia,
								    String departamentoOcurrencia,
								    int armaFuego,
								    int armaCortopunzante,
								    int armaContundente,
								    int asfixia,
								    int intoxicacion,
								    int inmersion,
								    int explosivo,
								    int polvora,
								    int otracausa,
								    int caida,
								    int mordedura,
								    int vivienda,
								    int lugarTrabajo,
								    int lugarEstudio,
								    int taberna,
								    int establecimientoPublico,
								    int viaPublica,
								    int otroLugar,
								    int lesionAccidenteTrabajo,
								    int codigoArp,
								    int actividadDuranteHecho,
								    int lesionIntencional,
								    int tipoLesion,
								    int tipoVehiculo,
								    int condicionLesionado,
								    int tipoViolencia,
								    int agresor,
								    int denunciado,
								    int consumoAlcohol,
								    int consumoOtrasSustancias,
								    String impresionDiagnostica,
								    int gravedadLesion,
								    int unidadGeneradora,
								    int fueraBogota
								    )
	{
		return SqlBaseFichaLesionesDao.modificarFicha(con,
													sire,
													notificar,
												    loginUsuario,
												    codigoFichaInfecciones,
												    codigoPaciente,
												    codigoDiagnostico,
												    codigoNotificacion,
												    numeroSolicitud,
												    estado,
												    
												    estadoIngreso,
												    fechaOcurrencia,
												    horaOcurrencia,
												    lugarOcurrencia,
												    localidad,
												    municipioOcurrencia,
												    departamentoOcurrencia,
												    armaFuego,
												    armaCortopunzante,
												    armaContundente,
												    asfixia,
												    intoxicacion,
												    inmersion,
												    explosivo,
												    polvora,
												    otracausa,
												    caida,
												    mordedura,
												    vivienda,
												    lugarTrabajo,
												    lugarEstudio,
												    taberna,
												    establecimientoPublico,
												    viaPublica,
												    otroLugar,
												    lesionAccidenteTrabajo,
												    codigoArp,
												    actividadDuranteHecho,
												    lesionIntencional,
												    tipoLesion,
												    tipoVehiculo,
												    condicionLesionado,
												    tipoViolencia,
												    agresor,
												    denunciado,
												    consumoAlcohol,
												    consumoOtrasSustancias,
												    impresionDiagnostica,
												    gravedadLesion,
												    unidadGeneradora,
												    fueraBogota);
	}




	public ResultSet consultaTodoFicha(Connection con, int codigo)
	{
		return SqlBaseFichaLesionesDao.consultarTodoFichaLesiones(con,codigo);
	}
	
	
	
	public ResultSet consultaDatosPaciente(Connection con, int codigo)
	{
		return SqlBaseFichaLesionesDao.consultarDatosPaciente(con,codigo);
	}
	
	
	
	public int insertarFichaCompleta(Connection con,
										int numeroSolicitud,
										String login,
										int codigoPaciente,
										String codigoDiagnostico,
										int estado,
										int codigoAseguradora,
										String nombreProfesional,
									    
									    int estadoIngreso,
									    String fechaOcurrencia,
									    int horaOcurrencia,
									    String lugarOcurrencia,
									    int localidad,
									    String municipioOcurrencia,
									    String departamentoOcurrencia,
									    int armaFuego,
									    int armaCortopunzante,
									    int armaContundente,
									    int asfixia,
									    int intoxicacion,
									    int inmersion,
									    int explosivo,
									    int polvora,
									    int otracausa,
									    int caida,
									    int mordedura,
									    int vivienda,
									    int lugarTrabajo,
									    int lugarEstudio,
									    int taberna,
									    int establecimientoPublico,
									    int viaPublica,
									    int otroLugar,
									    int lesionAccidenteTrabajo,
									    int codigoArp,
									    int actividadDuranteHecho,
									    int lesionIntencional,
									    int tipoLesion,
									    int tipoVehiculo,
									    int condicionLesionado,
									    int tipoViolencia,
									    int agresor,
									    int denunciado,
									    int consumoAlcohol,
									    int consumoOtrasSustancias,
									    String impresionDiagnostica,
									    int gravedadLesion,
									    int unidadGeneradora,
									    int fueraBogota,
									    boolean activa
									   )
	{
		return SqlBaseFichaLesionesDao.insertarFichaCompleta(con,
																numeroSolicitud,
																login,
																codigoPaciente,
																codigoDiagnostico,
																estado,
																codigoAseguradora,
																nombreProfesional,
															    secuenciaStr,
															    
															    estadoIngreso,
															    fechaOcurrencia,
															    horaOcurrencia,
															    lugarOcurrencia,
															    localidad,
															    municipioOcurrencia,
															    departamentoOcurrencia,
															    armaFuego,
															    armaCortopunzante,
															    armaContundente,
															    asfixia,
															    intoxicacion,
															    inmersion,
															    explosivo,
															    polvora,
															    otracausa,
															    caida,
															    mordedura,
															    vivienda,
															    lugarTrabajo,
															    lugarEstudio,
															    taberna,
															    establecimientoPublico,
															    viaPublica,
															    otroLugar,
															    lesionAccidenteTrabajo,
															    codigoArp,
															    actividadDuranteHecho,
															    lesionIntencional,
															    tipoLesion,
															    tipoVehiculo,
															    condicionLesionado,
															    tipoViolencia,
															    agresor,
															    denunciado,
															    consumoAlcohol,
															    consumoOtrasSustancias,
															    impresionDiagnostica,
															    gravedadLesion,
															    unidadGeneradora,
															    fueraBogota,
															    activa);
	}
}
